import type { Metadata } from "next";
import SitePage from "@/components/SitePage";

export const metadata: Metadata = {
  title: "Uttarakhand Tour Packages from Hyderabad | Yatra & Holidays",
  description: "Explore Uttarakhand tour packages from Hyderabad for Char Dham, Kedarnath, Badrinath and Himalayan holidays with route planning and Telugu-friendly support.",
  alternates: { canonical: "/uttarakhand-tour-packages-from-hyderabad" },
  robots: { index: true, follow: true, "max-image-preview": "large" },
  openGraph: {
    title: "Uttarakhand Tour Packages from Hyderabad | Yatra & Holidays",
    description: "Explore Uttarakhand tour packages from Hyderabad for Char Dham, Kedarnath, Badrinath and Himalayan holidays with route planning and Telugu-friendly support.",
    url: "/uttarakhand-tour-packages-from-hyderabad",
    siteName: "On A Trip Holidays",
    type: "website",
  },
};

export default function Page() {
  return (
    <SitePage>
      <nav className="nav"><a className="brand" href="/"><img alt="On A Trip Holidays" decoding="async" loading="lazy" src="assets/logo.png" /></a>
<div className="navlinks"><a href="/packages">Packages</a><a href="/pilgrimage">Pilgrimage</a><a href="/blogs">Blogs</a><a href="/about">About</a><a href="/contact">Contact</a></div>
<a className="wa" href="https://wa.me/919182894146?text=Hi%20On%20A%20Trip%20Holidays%2C%20I%20want%20a%20tour%20quote">WhatsApp Us</a></nav>
<main><section className="oat-region-hero"><div className="eyebrow">ON A TRIP HOLIDAYS • HYDERABAD</div><section className="oat-v15-hero"><div className="oat-v15-hero-inner"><div className="oat-v15-kicker">ON A TRIP HOLIDAYS • HYDERABAD</div><h1>Uttarakhand Tour Packages from Hyderabad</h1><p>Char Dham • Kedarnath • Himalayan escapes. Explore a clean, well-planned holiday or pilgrimage journey with practical itinerary guidance, stay and transport options, and Telugu-friendly support.</p><div className="oat-v15-actions"><a className="oat-v15-btn" href="https://wa.me/919182894146?text=Hi%20On%20A%20Trip%20Holidays%2C%20I%20want%20the%20latest%20price%20and%20dates%20for%20Uttarakhand%20Tour%20Packages%20from%20Hyderabad">Get Latest Price & Dates</a><a className="oat-v15-btn alt" href="#itinerary">View Itinerary</a></div></div></section><section className="oat-v15-facts"><div className="oat-v15-fact"><strong>📍 Departure</strong><span>Hyderabad</span></div><div className="oat-v15-fact"><strong>🗣️ Support</strong><span>Telugu-friendly assistance</span></div><div className="oat-v15-fact"><strong>👨‍👩‍👧 Travel style</strong><span>Group & customised options</span></div><div className="oat-v15-fact"><strong>📲 Enquiry</strong><span>Latest dates & pricing on WhatsApp</span></div></section><div className="oat-v16-trail"><a href="/">Home</a>  ›  <a href="/packages">Tour Packages</a>  ›  Hyderabad Packages</div>
<div className="oat-v16-bar"><div className="oat-v16-bar-inner"><div><strong>Planning from Hyderabad?</strong><div className="oat-v16-mini">Get the latest route, dates, inclusions and price on WhatsApp.</div></div><a href="https://wa.me/919182894146?text=Hi%20On%20A%20Trip%20Holidays%2C%20I%20want%20the%20latest%20package%20details%20from%20Hyderabad.">Get Latest Details →</a></div></div><section className="oat-v15-section"><h2>Destination Highlights</h2><div className="oat-v15-gallery"><figure><img alt="Uttarakhand Tour Packages from Hyderabad destination travel photograph" decoding="async" loading="lazy" src="https://images.pexels.com/photos/19271393/pexels-photo-19271393.jpeg?auto=compress&amp;cs=tinysrgb&amp;w=1600" /><figcaption>Signature view</figcaption></figure><figure><img alt="Uttarakhand Tour Packages from Hyderabad destination travel photograph" decoding="async" loading="lazy" src="https://images.pexels.com/photos/12151764/pexels-photo-12151764.jpeg?auto=compress&amp;cs=tinysrgb&amp;w=1600" /><figcaption>Travel highlight</figcaption></figure><figure><img alt="Uttarakhand Tour Packages from Hyderabad destination travel photograph" decoding="async" loading="lazy" src="https://images.pexels.com/photos/37677036/pexels-photo-37677036.jpeg?auto=compress&amp;cs=tinysrgb&amp;w=1600" /><figcaption>Explore the destination</figcaption></figure></div></section><section className="oat-v15-section"><h2>Plan your trip with clarity</h2><div className="oat-v15-route"><article><b>01 • Choose your dates</b><span>Share preferred dates and group size so we can confirm the latest available option.</span></article><article><b>02 • Get the right itinerary</b><span>Compare route, hotel, transport and sightseeing choices before you book.</span></article><article><b>03 • Enquire directly</b><span>Use WhatsApp for the latest package details and personalised assistance.</span></article></div></section><section className="oat-v15-cta"><h2>Ready to plan your trip from Hyderabad?</h2><p>Send your travel dates and group size. We’ll help you understand the latest itinerary, package inclusions and available options.</p><a className="oat-v15-btn" href="https://wa.me/919182894146?text=Hi%20On%20A%20Trip%20Holidays%2C%20please%20share%20the%20latest%20itinerary%20and%20price">WhatsApp On A Trip Holidays</a></section><p>Discover Uttarakhand with a dedicated mix of pilgrimage and Himalayan holiday planning. Start with Char Dham, Kedarnath or Do Dham, or enquire about Rishikesh, Haridwar, Mussoorie and Auli routes.</p></section>
<section className="oat-grid"><article className="oat-card"><h2>Char Dham Yatra</h2><p>Yamunotri, Gangotri, Kedarnath and Badrinath pilgrimage planning with Telugu-first group support.</p><a href="/char-dham-yatra-packages-from-hyderabad">Explore Char Dham →</a></article><article className="oat-card"><h2>Kedarnath Yatra</h2><p>Explore Kedarnath pilgrimage packages from Hyderabad with route, stay and travel assistance.</p><a href="/kedarnath-yatra-packages-from-hyderabad">Explore Kedarnath →</a></article><article className="oat-card"><h2>Do Dham Yatra</h2><p>Plan a Kedarnath and Badrinath pilgrimage with group itinerary support.</p><a href="/do-dham-yatra-packages-from-hyderabad">Explore Do Dham →</a></article><article className="oat-card"><h2>Uttarakhand Holidays</h2><p>For non-pilgrimage travel, ask about Rishikesh, Haridwar, Mussoorie, Auli and future seasonal routes.</p><a href="/packages">Explore Uttarakhand holidays →</a></article></section>
<section className="oat-cta"><h2>Planning a trip from Hyderabad?</h2><p>Tell us your travel dates, group size and preferred route. We can suggest the right itinerary, transport and stay options.</p>
<a href="https://wa.me/919182894146?text=Hi%20On%20A%20Trip%20Holidays%2C%20I%20want%20a%20tour%20quote">Get itinerary & price on WhatsApp</a></section>
<section className="oat-faq"><h2>Frequently Asked Questions</h2><details><summary>Can I travel to Uttarakhand from Hyderabad with a Telugu group?</summary><p>Yes. On A Trip Holidays focuses on Telugu-friendly group travel and can assist with Uttarakhand pilgrimage and holiday itineraries.</p></details><details><summary>Which Uttarakhand trip should I choose?</summary><p>Char Dham, Kedarnath and Do Dham are pilgrimage-focused. Rishikesh, Haridwar, Mussoorie and Auli are suitable for holiday and adventure planning.</p></details><details><summary>Can Uttarakhand packages be customised?</summary><p>Yes. Customisation can depend on travel dates, group size, route, hotel category and transport preference.</p></details></section></main>
<section className="oat-v15-section"><h2>How to plan Uttarakhand Tour Packages from Hyderabad</h2><div className="oat-v16-steps"><div className="oat-v16-step"><b>1</b><h3>Share your dates</h3><p>Tell us your preferred travel dates, number of travellers and departure city.</p></div><div className="oat-v16-step"><b>2</b><h3>Choose your trip</h3><p>Compare the route, stay plan, transport and inclusions that suit your group.</p></div><div className="oat-v16-step"><b>3</b><h3>Confirm your booking</h3><p>Our team helps with the next booking steps and current trip requirements.</p></div></div><div className="oat-v16-note">Package dates, availability, prices and inclusions can change. Confirm the latest details before booking.</div><div className="oat-v16-cta"><div><h3>Need the latest package details?</h3><p>Message On A Trip Holidays for current dates, pricing and inclusions.</p></div><a href="https://wa.me/919182894146?text=Hi%20On%20A%20Trip%20Holidays%2C%20please%20share%20the%20latest%20package%20details%20from%20Hyderabad.">WhatsApp Us</a></div></section>
    </SitePage>
  );
}
