import {NextResponse} from "next/server";
import {cookies} from "next/headers";
import {crmSupabaseConfig,getCrmSession} from "@/lib/crm-auth";
async function ctx(){const session=await getCrmSession();if(!session)return null;const token=(await cookies()).get("oat_crm_access")?.value||"";const {url,key}=crmSupabaseConfig();return{session,token,url,key}}
function h(c:any,extra:any={}){return{apikey:c.key,Authorization:`Bearer ${c.token}`,...extra}}
const tables:any={suppliers:"crm_suppliers",supplier_bookings:"crm_supplier_bookings",ledger:"crm_supplier_ledger"};
export async function GET(req:Request){const c=await ctx();if(!c)return NextResponse.json({error:"Unauthorized"},{status:401});const p=new URL(req.url).searchParams;const resource=p.get("resource")||"suppliers";if(!tables[resource])return NextResponse.json({error:"Invalid resource"},{status:400});const q=new URLSearchParams({select:"*",limit:"200",offset:"0"});for(const k of ["supplier_id","booking_id","supplier_booking_id","id"]){const v=p.get(k);if(v)q.set(k,v)}q.set("order",resource==="ledger"?"entry_date.desc":"created_at.desc");const r=await fetch(`${c.url}/rest/v1/${tables[resource]}?${q}`,{headers:h(c),cache:"no-store"});let data:any[]=[];try{data=await r.json()}catch{data=[]}return NextResponse.json(data,{status:r.status})}
export async function POST(req:Request){const c=await ctx();if(!c)return NextResponse.json({error:"Unauthorized"},{status:401});const b=await req.json();const resource=b.resource||"suppliers";if(!tables[resource])return NextResponse.json({error:"Invalid resource"},{status:400});const d={...(b.data||{}),created_by:c.session.user.id};if(resource==="ledger"){d.debit=Math.max(0,Number(d.debit||0));d.credit=Math.max(0,Number(d.credit||0));if(!d.supplier_id)return NextResponse.json({error:"Supplier is required"},{status:400})}const r=await fetch(`${c.url}/rest/v1/${tables[resource]}`,{method:"POST",headers:h(c,{"Content-Type":"application/json",Prefer:"return=representation"}),body:JSON.stringify(d)});let data:any=null;try{data=await r.json()}catch{data=null}return NextResponse.json(data,{status:r.status})}
export async function PATCH(req:Request){const c=await ctx();if(!c)return NextResponse.json({error:"Unauthorized"},{status:401});const b=await req.json();const resource=b.resource||"suppliers";if(!tables[resource]||!b.id)return NextResponse.json({error:"Resource and id are required"},{status:400});const d={...(b.data||{})};delete d.id;const r=await fetch(`${c.url}/rest/v1/${tables[resource]}?id=eq.${encodeURIComponent(b.id)}`,{method:"PATCH",headers:h(c,{"Content-Type":"application/json",Prefer:"return=representation"}),body:JSON.stringify(d)});let data:any=null;try{data=await r.json()}catch{data=null}return NextResponse.json(data,{status:r.status})}
