from pathlib import Path
import re, json, html
root=Path('/mnt/data/v34work')
base='https://www.onatripholidays.com'
logo='assets/logo.png'
nav='''<nav class="nav"><a class="brand" href="index.html"><img src="assets/logo.png" alt="On A Trip Holidays"></a><div class="navlinks"><a href="packages.html">Packages</a><a href="pilgrimage.html">Pilgrimage</a><a href="packages.html#batches">Batches</a><a href="blogs.html">Blogs</a><a href="about.html">About</a><a href="contact.html">Contact</a></div><a class="wa" href="https://wa.me/919182894146?text=Hi%20On%20A%20Trip%20Holidays%2C%20I%20want%20a%20travel%20quote">WhatsApp Us</a></nav>'''
footer='''<footer><div><div class="footlogo"><img src="assets/logo.png" alt="On A Trip Holidays"></div><p>Telugu-first travel support from Hyderabad for pilgrimage, domestic, adventure and international holidays.</p></div><div><h4>Explore</h4><a href="packages.html">All Packages</a><a href="pilgrimage.html">Pilgrimage</a><a href="packages.html#batches">Batch Dates</a><a href="blogs.html">Travel Blog</a></div><div><h4>Popular</h4><a href="package-kashmir.html">Kashmir</a><a href="package-ladakh.html">Ladakh</a><a href="package-char-dham.html">Char Dham</a><a href="package-kerala.html">Kerala</a></div><div><h4>Contact</h4><a href="tel:+919182894146">+91 91828 94146</a><a href="https://wa.me/919182894146">WhatsApp</a><a href="https://www.instagram.com/onatriphyd/">Instagram</a><a href="admin.html">Admin</a></div><div class="copy">© 2026 On A Trip Holidays. All rights reserved.</div></footer>'''

def page(title, desc, canonical, body, schema=None):
    schema = schema or {"@context":"https://schema.org","@type":"TravelAgency","name":"On A Trip Holidays","url":base,"telephone":"+91 91828 94146"}
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(title)}</title><meta name="description" content="{html.escape(desc)}"><link rel="canonical" href="{canonical}"><meta name="robots" content="index,follow,max-image-preview:large"><meta property="og:type" content="website"><meta property="og:title" content="{html.escape(title)}"><meta property="og:description" content="{html.escape(desc)}"><meta property="og:url" content="{canonical}"><meta property="og:site_name" content="On A Trip Holidays"><meta name="twitter:card" content="summary_large_image"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script><link rel="stylesheet" href="style.css"></head><body>{nav}{body}{footer}</body></html>'''

def hero(kicker,h1,intro,cta='View Packages'):
    return f'''<section class="hero"><div class="hero-copy"><div class="eyebrow">{kicker}</div><h1>{h1}</h1><p>{intro}</p><div class="hero-actions"><a class="btn" href="packages.html">{cta}</a><a class="btn secondary" href="https://wa.me/919182894146?text=Hi%20On%20A%20Trip%20Holidays%2C%20I%20want%20a%20custom%20trip">Plan My Trip</a></div></div></section>'''

def faq(items):
    return '<section class="section"><div class="head"><div><div class="eyebrow">FAQ</div><h2>Frequently asked questions</h2></div></div><div class="faq-grid">'+''.join(f'<details><summary>{html.escape(q)}</summary><p>{html.escape(a)}</p></details>' for q,a in items)+'</div></section>'

landing=[
('hyderabad-to-kashmir-tour-packages.html','Kashmir Tour Packages from Hyderabad | On A Trip Holidays','Kashmir tour packages from Hyderabad with Srinagar, Gulmarg, Pahalgam and Sonamarg. Explore group and customised Kashmir holidays with Telugu travel support.','Kashmir','package-kashmir.html','Kashmir packages from Hyderabad are ideal for families, couples and friends looking for lakes, mountains, meadows and relaxed sightseeing.','Srinagar • Gulmarg • Pahalgam • Sonamarg'),
('hyderabad-to-ladakh-tour-packages.html','Ladakh Tour Packages from Hyderabad | Leh Ladakh Trips','Leh Ladakh tour packages from Hyderabad covering Leh, Nubra, Pangong and high-altitude routes. Get group and customised Ladakh trip planning with Telugu support.','Ladakh','package-ladakh.html','Plan a Ladakh adventure from Hyderabad with acclimatisation-friendly routing, mountain landscapes, monasteries, Pangong Lake and optional adventure upgrades.','Leh • Nubra • Pangong • Khardung La'),
('hyderabad-to-char-dham-yatra.html','Char Dham Yatra from Hyderabad | On A Trip Holidays','Char Dham Yatra packages from Hyderabad covering Yamunotri, Gangotri, Kedarnath and Badrinath with organised transport, stays, meals and Telugu support.','Char Dham Yatra','package-char-dham.html','A carefully planned Char Dham journey for pilgrims travelling from Hyderabad, with clear day-wise routing and practical preparation guidance.','Yamunotri • Gangotri • Kedarnath • Badrinath'),
('hyderabad-to-kedarnath-yatra.html','Kedarnath Yatra from Hyderabad | Package & Travel Guide','Kedarnath Yatra packages from Hyderabad with travel planning, accommodation, transfers and practical trek preparation guidance.','Kedarnath Yatra','package-kedarnath.html','Plan a comfortable Kedarnath journey with clear travel stages, stay information and preparation tips for the mountain route.','Kedarnath • Sonprayag • Gaurikund • Guptkashi'),
('hyderabad-to-manali-tour-packages.html','Manali Tour Packages from Hyderabad | On A Trip Holidays','Manali tour packages from Hyderabad for families, couples and friends covering Manali, Solang Valley, Rohtang region and nearby Himalayan attractions.','Manali','package-manali.html','Enjoy a balanced Himachal holiday with scenic drives, mountain viewpoints, local sightseeing and time to relax in Manali.','Manali • Solang Valley • Kullu • Kasol'),
('hyderabad-to-kerala-tour-packages.html','Kerala Tour Packages from Hyderabad | On A Trip Holidays','Kerala tour packages from Hyderabad covering Munnar, Thekkady, Alleppey and Kerala backwaters. Compare group and customised holidays.','Kerala','package-kerala.html','A practical Kerala holiday combining tea plantations, wildlife, backwaters and relaxed resort stays.','Munnar • Thekkady • Alleppey • Kochi'),
('hyderabad-to-sikkim-tour-packages.html','Sikkim Tour Packages from Hyderabad | Gangtok & Pelling','Sikkim tour packages from Hyderabad covering Gangtok, Pelling and scenic Himalayan attractions with flexible itineraries and travel support.','Sikkim','package-sikkim.html','Discover Sikkim with a balanced itinerary for families and friends, including mountain viewpoints, monasteries and local experiences.','Gangtok • Pelling • Tsomgo Lake • Nathula'),
('hyderabad-to-nepal-tour-packages.html','Nepal Tour Packages from Hyderabad | Kathmandu & Pokhara','Nepal tour packages from Hyderabad covering Kathmandu, Pokhara and optional Muktinath with practical route planning and travel support.','Nepal','package-nepal.html','Combine heritage, Himalayan scenery and spiritual experiences in a well-paced Nepal holiday from Hyderabad.','Kathmandu • Pokhara • Muktinath • Chitwan'),
('hyderabad-to-thailand-tour-packages.html','Thailand Tour Packages from Hyderabad | Bangkok & Pattaya','Thailand tour packages from Hyderabad for families, couples and friends covering Bangkok, Pattaya and popular island or city experiences.','Thailand','package-thailand.html','Plan a first Thailand holiday with the right balance of sightseeing, shopping, leisure and transfers.','Bangkok • Pattaya • Phuket • Coral Island'),
('hyderabad-to-spiti-valley-tour.html','Spiti Valley Tour from Hyderabad | Himachal Adventure Packages','Spiti Valley tour packages from Hyderabad with Kinnaur, Kaza, Key Monastery and high-altitude Himalayan landscapes.','Spiti Valley','package-spiti.html','A road-trip style Himalayan journey for travellers who want remote villages, dramatic valleys and an adventurous route.','Shimla • Kinnaur • Tabo • Kaza • Chandratal'),
('hyderabad-to-rajasthan-tour-packages.html','Rajasthan Tour Packages from Hyderabad | Jaipur, Jaisalmer & Udaipur','Rajasthan tour packages from Hyderabad covering Jaipur, Jaisalmer, Jodhpur and Udaipur with cultural sightseeing and flexible holiday planning.','Rajasthan','package-rajasthan.html','Explore forts, palaces, desert landscapes and heritage cities with a practical Rajasthan itinerary.','Jaipur • Jodhpur • Jaisalmer • Udaipur'),
('hyderabad-to-amarnath-yatra.html','Amarnath Yatra from Hyderabad | Travel & Package Guide','Amarnath Yatra packages from Hyderabad with practical route planning, accommodation, transfers and preparation guidance.','Amarnath Yatra','package-amarnath.html','Plan the sacred Amarnath journey with attention to travel dates, registration requirements, weather and walking preparation.','Srinagar • Pahalgam/Baltal • Amarnath'),
]
for slug,title,desc,name,pkg,intro,places in landing:
    body=hero('HYDERABAD TRAVEL PACKAGES',title,intro)
    body+=f'''<section class="section"><div class="head"><div><div class="eyebrow">PLAN WITH CONFIDENCE</div><h2>{name} from Hyderabad</h2></div><p>Popular route: {places}</p></div><div class="grid"><article class="blog"><h3>Who is this trip for?</h3><p>Families, couples, friends and travellers who want a professionally organised holiday with clear inclusions, practical routing and support before and during the journey.</p></article><article class="blog"><h3>What you can plan</h3><p>Choose a group departure or request a customised itinerary based on your dates, budget, hotel preference, traveller age and preferred pace.</p></article><article class="blog"><h3>Why book with On A Trip?</h3><p>Telugu-first assistance, transparent itinerary planning, WhatsApp support and destination-specific guidance from a Hyderabad travel team.</p></article></div></section>'''
    body+=f'''<section class="section"><div class="head"><div><div class="eyebrow">FEATURED PACKAGE</div><h2>{name} package</h2></div></div><div class="cta-card"><h3>See the complete day-wise itinerary</h3><p>Check route, stays, meals, inclusions, exclusions, important notes and enquiry options.</p><a class="btn" href="{pkg}">View {name} Package</a></div></section>'''
    body+=faq([(f'How much does a {name} package from Hyderabad cost?','The final price depends on travel dates, room type, group size, hotel category, transport and inclusions. Contact us for a current quote.'),(f'Can I customise a {name} trip from Hyderabad?','Yes. We can adjust duration, hotels, sightseeing, transport and travel dates around your requirements.'),(f'Do you provide Telugu travel support?','Yes. On A Trip Holidays is designed for Telugu-speaking travellers and provides support during trip planning and coordination.')])
    schema={"@context":"https://schema.org","@type":"TouristDestination","name":f"{name} Tour Packages from Hyderabad","description":desc,"url":f"{base}/{slug}"}
    (root/slug).write_text(page(title,desc,f'{base}/{slug}',body,schema),encoding='utf-8')

blogs=[
('kashmir-trip-cost-from-hyderabad.html','Kashmir Trip Cost from Hyderabad: Complete Budget Guide','Kashmir trip cost from Hyderabad depends on travel season, hotels, transport, sightseeing and trip length. Learn how to plan a realistic Kashmir budget.',['Kashmir','Hyderabad','Budget']),
('kashmir-itinerary-6-days.html','Kashmir 6 Days Itinerary: Srinagar, Gulmarg, Pahalgam & Sonamarg','A practical Kashmir 6 days itinerary covering Srinagar, Gulmarg, Pahalgam and Sonamarg, with route planning and travel tips.',['Kashmir','Itinerary']),
('ladakh-trip-cost-from-hyderabad.html','Ladakh Trip Cost from Hyderabad: Budget, Hotels & Transport','Understand the main costs of a Ladakh trip from Hyderabad including travel, hotels, local transport, permits and optional activities.',['Ladakh','Hyderabad','Budget']),
('ladakh-packing-list.html','Ladakh Packing List: What to Carry for a Leh Ladakh Trip','A practical Ladakh packing checklist covering warm layers, medicines, documents, sun protection, footwear and high-altitude essentials.',['Ladakh','Packing']),
('ladakh-acclimatization-guide.html','Ladakh Acclimatization Guide: How to Plan the First Two Days','Learn why acclimatisation matters in Ladakh and how to plan the first days in Leh before travelling to higher-altitude places.',['Ladakh','Health & Safety']),
('umling-la-travel-guide.html','Umling La Travel Guide: Route, Altitude & Planning Tips','Plan an Umling La trip with route considerations, altitude, weather, permits and practical tips for high-altitude travel.',['Ladakh','Umling La']),
('char-dham-from-hyderabad-cost.html','Char Dham Yatra Cost from Hyderabad: What Affects the Price','Understand the main cost factors for Char Dham Yatra from Hyderabad including travel, rooms, meals, vehicle type and season.',['Char Dham','Hyderabad']),
('char-dham-packing-list.html','Char Dham Yatra Packing List for Families & Senior Travellers','A practical Char Dham packing checklist covering clothing, footwear, medicines, documents, rain protection and useful pilgrimage items.',['Char Dham','Packing']),
('kedarnath-from-hyderabad-route.html','Kedarnath from Hyderabad: Route, Travel Options & Planning','Understand the journey from Hyderabad to Kedarnath, including travel stages, Sonprayag planning, walking preparation and stay considerations.',['Kedarnath','Hyderabad']),
('kedarnath-senior-citizens-guide.html','Kedarnath for Senior Citizens: Planning a Safer, Comfortable Trip','Practical planning considerations for senior travellers visiting Kedarnath, including pace, accommodation, weather and walking support.',['Kedarnath','Families']),
('manali-trip-cost-from-hyderabad.html','Manali Trip Cost from Hyderabad: Complete Budget Guide','Learn how travel mode, hotel category, sightseeing and season affect the cost of a Manali holiday from Hyderabad.',['Manali','Hyderabad']),
('kerala-itinerary-6-days.html','Kerala 6 Days Itinerary: Munnar, Thekkady & Alleppey','A balanced Kerala itinerary for first-time travellers covering hill stations, wildlife and backwaters.',['Kerala','Itinerary']),
('sikkim-trip-cost-from-hyderabad.html','Sikkim Trip Cost from Hyderabad: Budget & Planning Guide','Plan a Sikkim holiday from Hyderabad with a clear view of transport, hotels, sightseeing and seasonal costs.',['Sikkim','Hyderabad']),
('nepal-trip-cost-from-hyderabad.html','Nepal Trip Cost from Hyderabad: Kathmandu, Pokhara & Muktinath','Understand the key expenses and routing options for a Nepal holiday from Hyderabad.',['Nepal','Hyderabad']),
('thailand-trip-cost-from-hyderabad.html','Thailand Trip Cost from Hyderabad: Family & Couple Budget Guide','A practical guide to estimating Thailand holiday costs from Hyderabad, including flights, hotels, transfers and sightseeing.',['Thailand','Hyderabad']),
('spiti-best-time.html','Best Time to Visit Spiti Valley: Month-by-Month Guide','Learn when to visit Spiti for road conditions, weather, clear mountain views and different travel experiences.',['Spiti Valley','Best Time']),
('rajasthan-itinerary-7-days.html','Rajasthan 7 Days Itinerary: Jaipur, Jodhpur, Jaisalmer & Udaipur','A practical seven-day Rajasthan route covering major heritage cities and desert experiences.',['Rajasthan','Itinerary']),
('amarnath-yatra-registration-guide.html','Amarnath Yatra Registration & Preparation Guide','A practical planning guide covering registration, documents, travel preparation, weather and route considerations for Amarnath Yatra.',['Amarnath','Pilgrimage']),
('vaishno-devi-from-hyderabad.html','Vaishno Devi Yatra from Hyderabad: Route & Travel Guide','Plan a Vaishno Devi journey from Hyderabad with Katra stay, travel options and practical yatra preparation.',['Vaishno Devi','Hyderabad']),
('best-time-visit-manali.html','Best Time to Visit Manali: Snow, Summer & Family Travel','Compare Manali seasons for snow, sightseeing, road trips and family holidays.',['Manali','Best Time']),
('best-time-visit-ladakh.html','Best Time to Visit Ladakh: Month-by-Month Travel Guide','Compare Ladakh months for road access, weather, crowds and high-altitude sightseeing.',['Ladakh','Best Time']),
('best-time-visit-char-dham.html','Best Time for Char Dham Yatra: Season & Planning Guide','Understand the pilgrimage season, weather patterns and practical timing considerations before booking Char Dham.',['Char Dham','Best Time']),
('telugu-travel-support-hyderabad.html','Telugu Travel Support in Hyderabad: Why Local Guidance Helps','How Telugu-first travel assistance can make pilgrimage and holiday planning easier for families travelling from Telangana and Andhra Pradesh.',['Telugu Travel','Hyderabad']),
('family-travel-himalayas-guide.html','Himalayan Family Trips: How to Choose the Right Destination','Compare Kashmir, Himachal, Uttarakhand and Sikkim for family travel based on pace, weather and sightseeing.',['Family Travel','Himalayas']),
]
for slug,title,desc,tags in blogs:
    topic=title.split(':')[0]
    body=f'''<section class="section article"><div class="eyebrow">ON A TRIP TRAVEL GUIDE</div><h1>{topic}</h1><p class="lead">{desc}</p><p>This original guide is designed to answer the questions travellers usually ask before booking: how long to stay, what to expect, how to budget and how to build a comfortable route. Exact conditions, prices and operational arrangements can change by season, so confirm current details before travel.</p><h2>How to plan the trip</h2><p>Start with your travel dates and departure city, then decide whether you want a group departure or a private/customised holiday. Compare the total journey time, hotel location, meal plan, sightseeing and daily travel rather than choosing a package on price alone.</p><h2>What to check before booking</h2><ul><li>Pickup and drop location</li><li>Hotel category and room sharing</li><li>Daily travel distance and approximate drive time</li><li>Meals included and dietary preferences</li><li>Entry tickets, permits and activity charges</li><li>Weather and route conditions for your dates</li><li>Cancellation and payment terms</li></ul><h2>Make your itinerary comfortable</h2><p>A good holiday leaves enough time for rest, sightseeing and unexpected delays. Avoid packing too many attractions into one day. For mountain and pilgrimage routes, allow additional buffer time because road conditions and weather can affect schedules.</p><div class="cta-card"><h3>Want a personalised itinerary?</h3><p>Tell us your dates, traveller count, departure city and approximate budget. Our team can suggest a practical route.</p><a class="btn" href="https://wa.me/919182894146?text=Hi%20On%20A%20Trip%20Holidays%2C%20I%20want%20a%20custom%20itinerary">Plan My Trip on WhatsApp</a></div></section>'''
    body+=faq([('Can I customise the itinerary?','Yes. Customisation can include duration, hotels, sightseeing, transport and travel dates.'),('How early should I book?','Earlier booking generally gives more choice of hotels and departure dates, especially during peak seasons. Availability and pricing vary.'),('Can you help with the right package?','Yes. Share your dates, group size, departure city and budget and we can recommend suitable options.')])
    schema={"@context":"https://schema.org","@type":"Article","headline":title,"description":desc,"author":{"@type":"Organization","name":"On A Trip Holidays"},"publisher":{"@type":"Organization","name":"On A Trip Holidays"},"mainEntityOfPage":f"{base}/{slug}"}
    (root/slug).write_text(page(title,desc,f'{base}/{slug}',body,schema),encoding='utf-8')

# Update blogs index with new SEO content links
p=root/'blogs.html'; txt=p.read_text(encoding='utf-8')
insert='''<section class="seo-blog-grid"><div class="seo-guide-inner"><div class="eyebrow">HYDERABAD TRAVEL SEO GUIDES</div><h2>Popular Travel Searches & Planning Guides</h2><p>Original guides for travellers searching from Hyderabad and Telugu-speaking markets.</p><div class="blog-grid">'''
for slug,title,desc,tags in blogs:
    insert+=f'<article class="seo-blog-card"><div class="eyebrow">{html.escape(tags[0].upper())}</div><h3><a href="{slug}">{html.escape(title)}</a></h3><p>{html.escape(desc)}</p><a href="{slug}">Read guide →</a></article>'
insert+='</div></div></section>'
# place before footer
idx=txt.find('<footer>')
if idx!=-1: txt=txt[:idx]+insert+txt[idx:]
p.write_text(txt,encoding='utf-8')

# Add SEO nav link on homepage if absent and a Hyderabad search block before footer
for fn in ['index.html','packages.html','pilgrimage.html']:
    p=root/fn; t=p.read_text(encoding='utf-8')
    if 'Hyderabad Travel Guides' not in t:
        block='''<section class="section seo-city-links"><div class="head"><div><div class="eyebrow">TRAVEL FROM HYDERABAD</div><h2>Popular Hyderabad Travel Searches</h2></div><p>Explore destination guides and packages built around common travel searches from Hyderabad.</p></div><div class="grid">'''
        for slug,title,desc,*_ in landing[:8]:
            short=title.split('|')[0]
            block+=f'<article class="blog"><h3><a href="{slug}">{html.escape(short)}</a></h3><p>{html.escape(desc)}</p></article>'
        block+='</div></section>'
        pos=t.find('<footer>')
        if pos!=-1:t=t[:pos]+block+t[pos:]
    p.write_text(t,encoding='utf-8')

# sitemap
urls=['index.html','packages.html','pilgrimage.html','blogs.html']+[x[0] for x in landing]+[x[0] for x in blogs]
for f in root.glob('package-*.html'): urls.append(f.name)
for f in root.glob('blog-*.html'): urls.append(f.name)
for f in root.glob('*-guide.html'): urls.append(f.name)
lines=['<?xml version="1.0" encoding="UTF-8"?>','<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
for u in sorted(set(urls)):
    lines.append(f'<url><loc>{base}/{u}</loc><changefreq>weekly</changefreq><priority>{"0.9" if u in [x[0] for x in landing] else "0.7"}</priority></url>')
lines.append('</urlset>')
(root/'sitemap.xml').write_text('\n'.join(lines),encoding='utf-8')
(root/'robots.txt').write_text(f'User-agent: *\nAllow: /\nDisallow: /admin\nDisallow: /crm\nDisallow: /admin-dashboard\nSitemap: {base}/sitemap.xml\n',encoding='utf-8')
(root/'README_V34_SEO_CONTENT.txt').write_text('V34: Expanded original SEO content inspired by competitor information architecture. Added 12 Hyderabad destination landing pages and 24 original travel guides, strengthened internal linking, FAQ/Article/TouristDestination schema, and regenerated sitemap/robots. Content is original and should be reviewed for current pricing, dates and operational details before publishing.\n',encoding='utf-8')
