import {NextResponse} from "next/server";
import {cookies} from "next/headers";
import {crmSupabaseConfig,getCrmSession} from "@/lib/crm-auth";

async function ctx(){const session=await getCrmSession();if(!session)return null;const token=(await cookies()).get("oat_crm_access")?.value||"";const {url,key}=crmSupabaseConfig();return {session,token,url,key}}
function h(c:any,extra:any={}){return {apikey:c.key,Authorization:`Bearer ${c.token}`,...extra}}
async function db(c:any,path:string,init:any={}){const r=await fetch(`${c.url}/rest/v1/${path}`,{...init,headers:h(c,{"Content-Type":"application/json",...(init.headers||{})}),cache:"no-store"});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.message||d?.error||"Database request failed");return d}
function num(v:any){const n=Number(v);return Number.isFinite(n)?n:0}
export async function GET(req:Request){try{const c=await ctx();if(!c)return NextResponse.json({error:"Unauthorized"},{status:401});const p=new URL(req.url).searchParams;const bookingId=p.get("booking_id");const invoiceId=p.get("invoice_id");const paymentId=p.get("payment_id");if(invoiceId)return NextResponse.json(await db(c,`crm_invoices?id=eq.${encodeURIComponent(invoiceId)}&select=*`));if(paymentId)return NextResponse.json(await db(c,`crm_payments?id=eq.${encodeURIComponent(paymentId)}&select=*`));if(bookingId){const [b,pay,inv]=await Promise.all([db(c,`crm_bookings?id=eq.${encodeURIComponent(bookingId)}&select=*`),db(c,`crm_payments?booking_id=eq.${encodeURIComponent(bookingId)}&select=*&order=payment_date.desc`),db(c,`crm_invoices?booking_id=eq.${encodeURIComponent(bookingId)}&select=*&order=created_at.desc`)]);return NextResponse.json({booking:b?.[0]||null,payments:pay||[],invoices:inv||[]})}const [pay,inv]=await Promise.all([db(c,"crm_payments?select=*&order=created_at.desc&limit=200"),db(c,"crm_invoices?select=*&order=created_at.desc&limit=200")]);return NextResponse.json({payments:pay||[],invoices:inv||[]})}catch(e:any){return NextResponse.json({error:e.message||"Finance request failed"},{status:500})}}
export async function POST(req:Request){try{const c=await ctx();if(!c)return NextResponse.json({error:"Unauthorized"},{status:401});const body=await req.json();const type=body?.type;if(type==="invoice"){const booking=body.booking_id?((await db(c,`crm_bookings?id=eq.${encodeURIComponent(body.booking_id)}&select=*`))||[])[0]:null;const total=num(body.total??booking?.total_amount);const paid=num(booking?.paid_amount);const payload={invoice_no:body.invoice_no||`INV-${new Date().toISOString().slice(0,7).replace("-","")}-${Math.random().toString(36).slice(2,7).toUpperCase()}`,booking_id:body.booking_id||null,quotation_id:body.quotation_id||null,customer_id:body.customer_id||booking?.customer_id||null,invoice_date:body.invoice_date||new Date().toISOString().slice(0,10),due_date:body.due_date||null,subtotal:num(body.subtotal??total),discount:num(body.discount),tax:num(body.tax),tcs:num(body.tcs),total,paid_amount:paid,balance_amount:Math.max(0,total-paid),status:total>0&&paid>=total?"paid":paid>0?"partially_paid":"issued",notes:body.notes||null,created_by:c.session.user.id};return NextResponse.json(await db(c,"crm_invoices",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(payload)}))}if(type==="payment"){const bookingId=body.booking_id;const amount=num(body.amount);if(!bookingId||amount<=0)return NextResponse.json({error:"Booking and positive payment amount are required"},{status:400});const booking=((await db(c,`crm_bookings?id=eq.${encodeURIComponent(bookingId)}&select=*`))||[])[0];if(!booking)return NextResponse.json({error:"Booking not found"},{status:404});const remaining=Math.max(0,num(booking.total_amount)-num(booking.paid_amount));if(amount>remaining)return NextResponse.json({error:`Payment exceeds remaining balance of ₹${Math.round(remaining).toLocaleString("en-IN")}`},{status:400});const payload={receipt_no:body.receipt_no||`RC-${new Date().toISOString().slice(2,10).replace(/-/g,"")}-${Math.random().toString(36).slice(2,6).toUpperCase()}`,booking_id:bookingId,quotation_id:body.quotation_id||booking.quotation_id||null,customer_id:body.customer_id||booking.customer_id||null,payment_date:body.payment_date||new Date().toISOString().slice(0,10),amount,method:body.method||"bank_transfer",reference:body.reference||null,status:"received",notes:body.notes||null,created_by:c.session.user.id};const payment=(await db(c,"crm_payments",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(payload)}))||[];return NextResponse.json(payment)}return NextResponse.json({error:"Invalid finance operation"},{status:400})}catch(e:any){return NextResponse.json({error:e.message||"Finance operation failed"},{status:500})}}
