import type {Metadata} from "next";
import PolicyPage from "@/components/PolicyPage";
export const metadata:Metadata={title:"Cancellation & Refund Policy | On A Trip Holidays",description:"Cancellation, amendment and refund policy for On A Trip Holidays travel packages, pilgrimage tours, domestic holidays and international trips."};
export default function Cancellation(){return <PolicyPage kicker="ON A TRIP HOLIDAYS" title="Cancellation & Refund Policy" intro="We understand that travel plans can change. This policy explains how cancellations, amendments and refunds are handled for On A Trip Holidays bookings." updated="10 September 2026" sections={[
 {title:"1. Cancellation Rules",children:<p>Cancellation charges depend on the package, departure date, supplier rules, tickets already issued, hotel or transport commitments and the cancellation terms communicated in your booking confirmation. The specific cancellation schedule for a confirmed package takes priority over this general policy.</p>},
 {title:"2. How to Cancel",children:<p>Cancellation requests should be sent to On A Trip Holidays through the official contact details used for your booking. A cancellation is considered received when our team acknowledges the request in writing. The date and time of the acknowledged request may be used to determine applicable charges.</p>},
 {title:"3. Typical Package Cancellation Structure",children:<ul><li>Advance cancellation: charges may be lower when suppliers allow cancellation without significant commitment.</li><li>Closer to departure: hotel, vehicle, activity and other supplier charges may increase and can become partly or fully non-refundable.</li><li>Very close to departure or no-show: the booking may be non-refundable depending on supplier rules.</li><li>Flight, train, permit, visa and special-event components may follow separate rules from the land package.</li></ul>},
 {title:"4. Supplier & Ticket Cancellation Charges",children:<p>Airline tickets, railway tickets, hotels, permits, activities, transport and other third-party services are subject to their own fare and cancellation rules. Any amount that a supplier retains or charges will be deducted before a refund is calculated where applicable.</p>},
 {title:"5. Non-Refundable Components",children:<p>Payments identified as non-refundable in the quotation, booking voucher or supplier terms may not be refundable after confirmation or issuance. This can include certain promotional fares, permits, special-event bookings, convenience or service charges, visa fees and supplier deposits.</p>},
 {title:"6. Amendments & Date Changes",children:<p>Changes to traveller names, dates, room categories, vehicles, routes or services are subject to availability and supplier charges. A change may be treated as a cancellation and rebooking where the relevant supplier does not permit amendments.</p>},
 {title:"7. Partial Cancellation",children:<p>If one or more travellers, rooms or services are removed from a booking, the revised price and refund are recalculated based on the supplier commitments remaining in the booking. Promotional discounts or group pricing may also change after a partial cancellation.</p>},
 {title:"8. Refund Processing",children:<p>Where a refund is approved, we will initiate it after the applicable supplier refunds or confirms the refundable amount. Processing time can vary by supplier, bank, payment method and transaction type. Refunds will normally be returned to the original payment source or another verified method agreed by the company where appropriate.</p>},
 {title:"9. Force Majeure & Supplier Cancellation",children:<p>If a trip or service is disrupted by circumstances beyond reasonable control such as severe weather, natural disasters, government restrictions, strikes, civil unrest or other force-majeure events, the available refund, credit or rescheduling option will depend on the amount recovered from the relevant suppliers and applicable rules.</p>},
 {title:"10. No-Show & Unused Services",children:<p>Failure to join a trip, late arrival, voluntary early departure or non-use of a confirmed service generally does not create an automatic right to a refund. Any refund for unused services is subject to the relevant supplier's rules.</p>},
 {title:"11. Travel Insurance Claims",children:<p>Where cancellation or disruption is covered by travel insurance, the customer may need to claim directly with the insurer. Insurance coverage, exclusions, documentation and claim decisions are governed by the insurer's policy.</p>},
 {title:"12. Important Note for Fixed Departures",children:<p>Group departures and pilgrimage packages may involve advance vehicle, hotel, meal, permit and ticket commitments. Their cancellation schedule may therefore be stricter than a flexible private holiday. The exact terms will be provided before or at the time of booking.</p>},
 {title:"13. Contact for Cancellation Requests",children:<div className="policy-contact"><strong>On A Trip Holidays</strong><p>Phone / WhatsApp: +91 91828 94146<br/>Email: Travel@onatripholidays.com<br/>Hyderabad, Telangana 500036</p></div>}
]}/>}
