import type {Metadata} from "next";
import PolicyPage from "@/components/PolicyPage";
export const metadata:Metadata={title:"Booking Terms & Conditions | On A Trip Holidays",description:"Booking terms and conditions for On A Trip Holidays tours, pilgrimage journeys, domestic holidays and international travel packages."};
export default function Terms(){return <PolicyPage kicker="ON A TRIP HOLIDAYS" title="Booking Terms & Conditions" intro="Please read these booking terms carefully before confirming a tour, pilgrimage, holiday package, transport service or customized travel arrangement with On A Trip Holidays." updated="10 September 2026" sections={[
{title:"1. About Our Travel Services",paragraphs:["On A Trip Holidays arranges and facilitates travel services including tour packages, pilgrimage journeys, hotels, transportation, sightseeing, activities, flights, trains, buses, visas and travel insurance where applicable.","Some services are supplied by independent airlines, hotels, transport operators, activity providers, government authorities or other third-party suppliers. Their applicable rules may also apply to your booking."]},
{title:"2. Booking Confirmation",paragraphs:["A booking is considered confirmed only after the required payment has been received and On A Trip Holidays has issued written confirmation, a booking voucher, itinerary or other confirmation through an authorized communication channel.","Availability and prices can change until the booking is confirmed. A quotation or enquiry does not by itself guarantee availability or a final price."]},
{title:"3. Prices, Taxes & Payments",bullets:["Package prices are based on the inclusions stated in the quotation or booking confirmation.","Government taxes, entry fees, permits, fuel surcharges, airline charges or supplier price changes may affect the final cost where applicable.","Payment schedules and balance-payment deadlines will be communicated at the time of booking.","Any bank, payment gateway, currency conversion or transaction charges applicable to a payment may be payable by the customer."]},
{title:"4. Itinerary & Service Changes",paragraphs:["Travel plans can be affected by weather, road conditions, traffic, government restrictions, permits, airline or railway schedules, hotel availability and other operational circumstances. On A Trip Holidays may adjust the sequence of sightseeing, accommodation or transport when reasonably required to operate the journey safely and practically. Any material change will be communicated to the customer as soon as reasonably possible."]},
{title:"5. Traveller Responsibilities",bullets:["Provide accurate names, contact details, dates and travel-document information.","Carry valid identification, passports, visas, permits and other documents required for the journey.","Follow airline, hotel, transport, destination and government rules.","Arrive at departure points and activity locations at the communicated reporting time.","Inform our team about relevant dietary, mobility or other service requirements as early as possible."]},
{title:"6. Flights, Trains, Hotels & Third-Party Services",paragraphs:["When a booking includes services provided by a third party, the supplier's fare rules, terms, cancellation rules and operating conditions may apply. On A Trip Holidays will assist with coordination and communication, but cannot control supplier decisions such as schedule changes, operational disruptions, overbooking or service availability."]},
{title:"7. Travel Documents & Visa",paragraphs:["For international travel, the traveller is responsible for holding valid passports, visas, permits and other required documents. Visa processing assistance, where offered, does not guarantee approval. Government authorities and consulates make the final decision on visa issuance."]},
{title:"8. Travel Insurance",paragraphs:["Where travel insurance is included or purchased, coverage is governed by the insurer's policy wording, exclusions, limits and claim procedure. Customers should review the policy and contact the insurer for claims or coverage decisions."]},
{title:"9. Special Requests",paragraphs:["Requests such as room preferences, specific vehicles, dietary requirements, early check-in, adjoining rooms or special activities are subject to availability unless expressly confirmed in writing."]},
{title:"10. Communication & Customer Consent",paragraphs:["By submitting an enquiry or making a booking, you authorize On A Trip Holidays to contact you regarding your enquiry, booking, itinerary, payment, schedule changes and travel support through phone, WhatsApp, SMS and email. Promotional communication is handled according to the consent provided by you and applicable law."]},
{title:"11. Force Majeure",paragraphs:["On A Trip Holidays is not responsible for delay, cancellation or inability to provide a service caused by circumstances beyond reasonable control, including natural disasters, severe weather, war, civil unrest, strikes, government restrictions, epidemics, road closures or supplier operational disruption. Refunds or alternatives in such circumstances will be handled according to the applicable supplier and booking policy."]},
{title:"12. Policy Updates",paragraphs:["These terms may be updated when our services, supplier requirements or applicable regulations change. The terms applicable to a confirmed booking are those communicated for that booking, together with the relevant supplier conditions."]},
{title:"13. Contact",paragraphs:["On A Trip Holidays | Hyderabad, Telangana 500036 | Phone: +91 91828 94146 | Email: Travel@onatripholidays.com"]}
]}/>}
