import {NextResponse} from "next/server";
import {getAdminSession,supabaseConfig} from "@/lib/admin-auth";
import {packages as sitePackages} from "@/lib/site-data";

export const dynamic="force-dynamic";

async function db(path:string,token:string,init?:RequestInit){const {url,key}=supabaseConfig();return fetch(`${url}/rest/v1/${path}`,{...init,headers:{apikey:key,Authorization:`Bearer ${token}`,"Content-Type":"application/json",Prefer:"return=representation",...(init?.headers||{})},cache:"no-store"});}
function canEdit(role:string){return ["super_admin","content_manager"].includes(role)}

export async function GET(){const s=await getAdminSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});try{const r=await db("packages?select=*&order=updated_at.desc",s.token);const data=await r.json();return NextResponse.json(data,{status:r.status});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to load packages"},{status:500});}}

export async function POST(req:Request){const s=await getAdminSession();if(!s||!canEdit(s.profile.role))return NextResponse.json({error:"You do not have permission to create packages."},{status:403});try{const body=await req.json();
 if(body.seed===true){const rows=sitePackages.map(p=>({slug:p.slug,name:p.name,category:p.category,duration:p.duration,route:p.route,from_location:p.from,price:p.price,description:p.description,image:p.image,highlights:p.highlights||[],meals:p.meals||null,batch:p.batch||null,visible:p.visible!==false,parent_slug:p.parentSlug||null,status:p.visible===false?"draft":"published",itinerary:[],inclusions:[],exclusions:[],gallery:[]}));const r=await db("packages?on_conflict=slug",s.token,{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(rows)});if(!r.ok)return NextResponse.json({error:await r.text()},{status:r.status});return NextResponse.json({ok:true,count:rows.length});}
 const row={slug:String(body.slug||""),name:String(body.name||""),category:body.category,duration:body.duration||"",route:body.route||"",from_location:body.from_location||"",price:body.price||"",description:body.description||"",image:body.image||"",highlights:Array.isArray(body.highlights)?body.highlights:[],meals:body.meals||null,batch:body.batch||null,visible:body.visible!==false,status:body.status||"draft",parent_slug:body.parent_slug||null,itinerary:body.itinerary||[],inclusions:body.inclusions||[],exclusions:body.exclusions||[],gallery:body.gallery||[],seo_title:body.seo_title||null,seo_description:body.seo_description||null,seo_keywords:body.seo_keywords||null,itinerary_pdf_url:body.itinerary_pdf_url||null};
 if(!row.slug||!row.name||!row.category)return NextResponse.json({error:"Slug, name and category are required."},{status:400});const r=await db("packages",s.token,{method:"POST",body:JSON.stringify(row)});const data=await r.json();if(!r.ok)return NextResponse.json({error:data?.message||data?.details||"Unable to create package"},{status:r.status});await db("admin_audit_logs",s.token,{method:"POST",body:JSON.stringify({actor_id:s.user.id,action:"create",entity_type:"package",entity_id:data?.[0]?.id,after_data:data?.[0]})});return NextResponse.json(data[0]);
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to create package"},{status:500});}}

export async function PATCH(req:Request){const s=await getAdminSession();if(!s||!canEdit(s.profile.role))return NextResponse.json({error:"You do not have permission to edit packages."},{status:403});try{const body=await req.json();const {id,...changes}=body;if(!id)return NextResponse.json({error:"Package id is required."},{status:400});const before=await db(`packages?id=eq.${encodeURIComponent(id)}&select=*`,s.token);const beforeData=(await before.json())?.[0]||null;const r=await db(`packages?id=eq.${encodeURIComponent(id)}`,s.token,{method:"PATCH",body:JSON.stringify({...changes,updated_at:new Date().toISOString()})});const data=await r.json();if(!r.ok)return NextResponse.json({error:data?.message||data?.details||"Unable to update package"},{status:r.status});await db("admin_audit_logs",s.token,{method:"POST",body:JSON.stringify({actor_id:s.user.id,action:"update",entity_type:"package",entity_id:id,before_data:beforeData,after_data:data?.[0]})});return NextResponse.json(data[0]);}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to update package"},{status:500});}}

export async function DELETE(req:Request){const s=await getAdminSession();if(!s||s.profile.role!=="super_admin")return NextResponse.json({error:"Only Super Admin can delete packages."},{status:403});try{const {id}=await req.json();if(!id)return NextResponse.json({error:"Package id is required."},{status:400});const r=await db(`packages?id=eq.${encodeURIComponent(id)}`,s.token,{method:"DELETE"});if(!r.ok)return NextResponse.json({error:await r.text()},{status:r.status});await db("admin_audit_logs",s.token,{method:"POST",body:JSON.stringify({actor_id:s.user.id,action:"delete",entity_type:"package",entity_id:id})});return NextResponse.json({ok:true});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to delete package"},{status:500});}}
