import type {Metadata} from "next";
import PolicyPage from "@/components/PolicyPage";
export const metadata:Metadata={title:"Privacy Policy | On A Trip Holidays",description:"Privacy policy explaining how On A Trip Holidays collects, uses, protects and communicates travel enquiry and booking information."};
export default function Privacy(){return <PolicyPage kicker="ON A TRIP HOLIDAYS" title="Company Privacy Policy" intro="Your privacy matters to us. This policy explains how On A Trip Holidays handles information shared through our website, enquiries, bookings and travel-support channels." updated="10 September 2026" sections={[
{title:"1. Information We Collect",paragraphs:["Depending on the service you request, we may collect your name, phone number, email address, travel dates, destination, number of travellers, booking preferences and information needed to arrange travel services.","For international or regulated services, additional information such as passport or visa details may be required when necessary for the service."]},
{title:"2. Information You Provide Through Enquiry Forms",paragraphs:["When you submit a package enquiry, we use the information you provide to understand your travel requirement, respond to you, prepare quotations, arrange follow-up and assist with booking. Required consent may also allow us to send service-related communications and, where separately permitted, promotional updates."]},
{title:"3. How We Use Your Information",bullets:["Respond to travel enquiries and requests.","Prepare quotations, itineraries and booking information.","Confirm and manage travel services with relevant suppliers.","Communicate booking confirmations, changes, reminders and support information.","Process payments or coordinate payment-related information where applicable.","Improve our website, customer service and travel offerings.","Prevent fraud, misuse and unauthorized activity."]},
{title:"4. Sharing Information With Travel Partners",paragraphs:["We may share information that is reasonably necessary with airlines, hotels, transport providers, activity operators, insurance providers, visa-service partners, destination suppliers and other service providers involved in fulfilling your booking. We do not share information with unrelated parties merely for their independent use without an appropriate purpose or permission where required."]},
{title:"5. WhatsApp, Phone, SMS & Email",paragraphs:["Our team may use phone calls, WhatsApp, SMS or email to respond to enquiries and provide booking or travel-support information. If you provide promotional consent, we may also send offers, travel updates or relevant promotional messages. You can ask us to stop promotional communications at any time, subject to messages necessary to service an active booking."]},
{title:"6. Payments & Sensitive Information",paragraphs:["Customers should never share passwords, OTPs, CVV numbers or other authentication secrets with our staff over chat or phone. Payment details are handled through the applicable payment provider or authorized process. We do not ask customers to disclose an OTP for completing a booking on their behalf."]},
{title:"7. Website Analytics & Cookies",paragraphs:["Our website may use essential cookies, analytics tools or similar technologies to keep the website working, understand usage and improve performance. Third-party services may process limited technical information according to their own policies."]},
{title:"8. Data Security",paragraphs:["We take reasonable administrative and technical measures to protect information against unauthorized access, misuse, alteration or disclosure. No internet transmission or storage system can be guaranteed to be completely secure."]},
{title:"9. Data Retention",paragraphs:["We retain information for as long as reasonably necessary for the purpose for which it was collected, including booking records, customer support, accounting, legal, tax and dispute-resolution requirements."]},
{title:"10. Your Choices & Requests",paragraphs:["You may contact us to request clarification about information associated with your enquiry or booking, request correction of inaccurate details, or ask about promotional communication preferences. Some information may need to be retained where required for an active booking or legal or accounting obligations."]},
{title:"11. Children",paragraphs:["Our services are intended to be arranged by adults or with appropriate involvement of a parent or guardian. We do not knowingly seek unnecessary personal information from children."]},
{title:"12. Changes to This Policy",paragraphs:["We may update this policy from time to time to reflect changes in our services, technology or applicable requirements. The latest version will be published on this page."]},
{title:"13. Contact Us About Privacy",paragraphs:["On A Trip Holidays | Privacy enquiries: Travel@onatripholidays.com | Phone: +91 91828 94146 | Hyderabad, Telangana 500036"]}
]}/>}
