"use client";
import {useState} from "react";
import "@/app/admin/admin.css";
import AdminPackages from "@/components/AdminPackages";

type Props={name:string;role:string};
const sections=[
 ["Overview","Dashboard","◈"],
 ["Content","Packages","▣"],["Content","Itineraries","▤"],["Content","Destinations","⌖"],["Content","Offers","%"],["Content","Blogs","✎"],["Content","Reviews","★"],
 ["Operations","Batches","◷"],["Operations","Vehicles & Hotels","▱"],["Operations","Enquiries","◎"],
 ["Growth","SEO","⌕"],["Growth","Media Library","▧"],
 ["System","Users & Permissions","♙"],["System","Audit Log","≡"],["System","Settings","⚙"]
];
export default function AdminDashboard({name,role}:Props){const [active,setActive]=useState("Dashboard");const [busy,setBusy]=useState(false);async function logout(){setBusy(true);await fetch("/api/admin/logout",{method:"POST"});location.href="/admin/login"}return <div className="admin-shell"><aside className="admin-sidebar"><div className="admin-brand"><div className="admin-mark small">OAT</div><div><b>ON A TRIP</b><span>Admin Control Center</span></div></div><nav>{sections.map(([group,label,icon],i)=><div key={label}>{(i===0||sections[i-1][0]!==group)&&<small>{group}</small>}<button className={active===label?"active":""} onClick={()=>setActive(label)}><i>{icon}</i>{label}</button></div>)}</nav><div className="admin-user"><strong>{name}</strong><span>{role.replaceAll("_"," ")}</span><button onClick={logout}>{busy?"Signing out…":"Sign out"}</button></div></aside><main className="admin-main"><header className="admin-top"><div><span className="admin-kicker">CONTROL CENTER</span><h1>{active}</h1></div><a href="/" target="_blank" rel="noreferrer">View website ↗</a></header>{active==="Dashboard"?<DashboardHome role={role} onNavigate={setActive}/>:active==="Packages"?<AdminPackages role={role}/>:<ModulePlaceholder title={active}/>}</main></div>}
function DashboardHome({role,onNavigate}:{role:string;onNavigate:(x:string)=>void}){return <><div className="admin-welcome"><div><h2>Good day 👋</h2><p>Your website operations at a glance.</p></div><div className="live-pill"><span/> Website content system ready</div></div><div className="admin-stats"><Stat n="Live" label="Website"/><Stat n="CMS" label="Content system"/><Stat n="6" label="Admin roles"/><Stat n="24/7" label="Content access"/></div><div className="admin-grid"><section className="admin-panel"><div className="panel-head"><div><span className="admin-kicker">QUICK ACTIONS</span><h3>Manage your website</h3></div></div><div className="quick-grid"><button onClick={()=>onNavigate("Packages")}><b>＋</b><span>New Package</span><small>Create or edit a destination package</small></button><button onClick={()=>onNavigate("Itineraries")}><b>⇧</b><span>Upload Itinerary</span><small>Add a PDF or day-wise plan</small></button><button onClick={()=>onNavigate("Batches")}><b>◷</b><span>New Batch</span><small>Add a departure date</small></button><button onClick={()=>onNavigate("Settings")}><b>⚙</b><span>Website Settings</span><small>Contact and business details</small></button></div></section><section className="admin-panel"><div className="panel-head"><div><span className="admin-kicker">SAFE PUBLISHING</span><h3>Draft → Review → Publish</h3></div></div><p className="panel-copy">Prepare content as drafts, preview changes, approve them and publish only when ready. Every important change can be recorded in the audit history.</p><div className="workflow"><span>Draft</span><b>→</b><span>Review</span><b>→</b><span>Publish</span></div></section></div><section className="admin-panel"><div className="panel-head"><div><span className="admin-kicker">CURRENT ROLE</span><h3>{role.replaceAll("_"," ")}</h3></div></div><p className="panel-copy">Your access is controlled by Supabase Row Level Security. Sensitive actions such as deleting packages remain restricted to Super Admin.</p></section></>}
function Stat({n,label}:{n:string;label:string}){return <div className="admin-stat"><strong>{n}</strong><span>{label}</span></div>}
function ModulePlaceholder({title}:{title:string}){return <section className="admin-panel module-placeholder"><div className="module-icon">{title==="Packages"?"▣":"✦"}</div><span className="admin-kicker">MODULE READY</span><h2>{title}</h2><p>This module is part of the On A Trip CMS foundation. The database and permission layer are prepared so this screen can manage live website content.</p><div className="coming">Next module connection is ready to be added without changing the public website.</div></section>}
