"use client";
import {useEffect,useState} from "react";
import "@/app/admin/admin.css";
type P={id:string;slug:string;name:string;category:string;duration:string;route:string;from_location:string;price:string;description:string;image:string;highlights:string[];meals?:string;batch?:string;visible:boolean;status:string;itinerary_pdf_url?:string};
const blank={slug:"",name:"",category:"Domestic",duration:"",route:"",from_location:"",price:"",description:"",image:"",highlights:[],meals:"",batch:"",visible:true,status:"draft",itinerary_pdf_url:""};
export default function AdminPackages({role}:{role:string}){const [items,setItems]=useState<P[]>([]);const [editing,setEditing]=useState<any>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const canEdit=['super_admin','content_manager'].includes(role);
async function load(){setLoading(true);const r=await fetch('/api/admin/packages');const d=await r.json();if(!r.ok)setError(d.error||'Unable to load packages');else setItems(d);setLoading(false)}useEffect(()=>{load()},[]);
async function save(){setSaving(true);setError("");const payload={...editing,highlights:Array.isArray(editing.highlights)?editing.highlights:editing.highlights.split('\n').map((x:string)=>x.trim()).filter(Boolean)};const r=await fetch('/api/admin/packages',{method:editing.id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)setError(d.error||'Unable to save');else{setEditing(null);await load()}setSaving(false)}
return <div className="admin-packages"><div className="package-toolbar"><div><span className="admin-kicker">CONTENT</span><h2>Packages</h2><p>Manage the live package catalogue without editing website code.</p></div>{canEdit&&<button className="admin-primary" onClick={()=>setEditing({...blank})}>＋ New Package</button>}</div>{error&&<div className="admin-error">{error}</div>}{loading?<div className="admin-panel">Loading packages…</div>:<div className="admin-package-list">{items.map(p=><div className="admin-package-row" key={p.id}><div className="admin-package-thumb" style={{backgroundImage:`url(${p.image})`}}/><div className="admin-package-info"><b>{p.name}</b><span>{p.category} · {p.duration} · {p.from_location}</span></div><strong>{p.price}</strong><span className={`status ${p.status}`}>{p.status}</span>{canEdit&&<button className="edit-btn" onClick={()=>setEditing({...p,highlights:(p.highlights||[]).join('\n')})}>Edit</button>}</div>)}</div>}{editing&&<div className="admin-modal-backdrop"><section className="admin-modal"><div className="modal-head"><div><span className="admin-kicker">PACKAGE EDITOR</span><h2>{editing.id?'Edit package':'New package'}</h2></div><button onClick={()=>setEditing(null)}>×</button></div><div className="form-grid">{[['name','Package name'],['slug','URL slug'],['duration','Duration'],['route','Route'],['from_location','Starting location'],['price','Price'],['image','Main image URL'],['meals','Meals'],['batch','Batch / departure'],['itinerary_pdf_url','Itinerary PDF URL']].map(([k,l])=><label key={k}>{l}<input value={editing[k]||''} onChange={e=>setEditing({...editing,[k]:e.target.value})}/></label>)}<label>Category<select value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}><option>Pilgrimage</option><option>Domestic</option><option>International</option></select></label><label>Status<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value})}><option>draft</option><option>review</option><option>published</option><option>archived</option></select></label><label className="full">Description<textarea rows={4} value={editing.description||''} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><label className="full">Highlights — one per line<textarea rows={5} value={Array.isArray(editing.highlights)?editing.highlights.join('\n'):editing.highlights||''} onChange={e=>setEditing({...editing,highlights:e.target.value})}/></label></div><label className="check"><input type="checkbox" checked={!!editing.visible} onChange={e=>setEditing({...editing,visible:e.target.checked})}/> Visible on website</label>{error&&<div className="admin-error">{error}</div>}<div className="modal-actions"><button className="cancel" onClick={()=>setEditing(null)}>Cancel</button><button className="admin-primary" onClick={save} disabled={saving}>{saving?'Saving…':'Save package'}</button></div></section></div>}</div>}
