"use client";
import {useEffect,useState} from "react";
import "@/app/admin/admin.css";
type P={id:string;name:string;duration:string;itinerary?:{day:string;title:string;details:string}[];itinerary_pdf_url?:string};
const blank={day:"Day 1",title:"",details:""};
export default function AdminItineraries({role}:{role:string}){const [items,setItems]=useState<P[]>([]);const [selected,setSelected]=useState("");const [days,setDays]=useState<any[]>([]);const [pdf,setPdf]=useState("");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");const canEdit=["super_admin","content_manager"].includes(role);
 useEffect(()=>{fetch("/api/admin/packages").then(r=>r.json()).then(d=>{setItems(Array.isArray(d)?d:[]);setLoading(false)}).catch(()=>{setError("Unable to load packages");setLoading(false)})},[]);
 function choose(id:string){const p=items.find(x=>x.id===id);setSelected(id);setDays(Array.isArray(p?.itinerary)?p!.itinerary:[]);setPdf(p?.itinerary_pdf_url||"");setMessage("");}
 function addDay(){setDays(x=>[...x,{...blank,day:`Day ${x.length+1}`}])}
 function update(i:number,k:string,v:string){setDays(x=>x.map((d,n)=>n===i?{...d,[k]:v}:d))}
 function remove(i:number){setDays(x=>x.filter((_,n)=>n!==i).map((d,n)=>({...d,day:`Day ${n+1}`})))}
 async function save(){const p=items.find(x=>x.id===selected);if(!p)return;setSaving(true);setError("");setMessage("");try{const r=await fetch("/api/admin/packages",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:p.id,itinerary:days,itinerary_pdf_url:pdf})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to save itinerary");setItems(x=>x.map(a=>a.id===p.id?{...a,itinerary:days,itinerary_pdf_url:pdf}:a));setMessage("Itinerary saved successfully.")}catch(e){setError(e instanceof Error?e.message:"Unable to save itinerary")}finally{setSaving(false)}}
 return <div className="admin-itineraries"><div className="package-toolbar"><div><span className="admin-kicker">CONTENT CMS</span><h2>Itinerary Manager</h2><p>Edit SEO-friendly day-wise itineraries and attach the full PDF.</p></div></div>{error&&<div className="admin-error">{error}</div>}{message&&<div className="admin-success">{message}</div>}{loading?<div className="admin-panel">Loading packages…</div>:<><div className="admin-panel itinerary-select"><label>Select package<select value={selected} onChange={e=>choose(e.target.value)}><option value="">Choose a package…</option>{items.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div>{selected&&<div className="itinerary-editor"><div className="admin-panel"><div className="panel-head"><span className="admin-kicker">FULL ITINERARY PDF</span><h3>Document link</h3></div><label className="form-label">PDF URL<input className="wide-input" value={pdf} onChange={e=>setPdf(e.target.value)} placeholder="https://…/itinerary.pdf"/></label></div><div className="admin-panel"><div className="panel-head"><span className="admin-kicker">DAY-WISE CONTENT</span><h3>{days.length} day(s)</h3></div>{days.map((d,i)=><article className="day-editor" key={i}><div className="day-number">{d.day||`Day ${i+1}`}</div><div className="day-fields"><input value={d.title||""} onChange={e=>update(i,"title",e.target.value)} placeholder="Day title / route"/><textarea rows={3} value={d.details||""} onChange={e=>update(i,"details",e.target.value)} placeholder="Detailed itinerary, sightseeing, meals, hotel and travel notes…"/></div><button className="delete-btn" onClick={()=>remove(i)}>Remove</button></article>)}<div className="itinerary-actions"><button className="admin-secondary" onClick={addDay} disabled={!canEdit}>＋ Add day</button><button className="admin-primary" onClick={save} disabled={!canEdit||saving}>{saving?"Saving…":"Save itinerary"}</button></div>{!canEdit&&<p className="panel-copy">Your role can view this itinerary but cannot edit it.</p>}</div></div>}</>}</div>}
