"use client";
import {useEffect,useState} from "react";
type User={id:string;name:string;email:string;role:string;is_active:boolean;auth_user_id?:string|null};
export default function AdminSalesUsers(){
 const [users,setUsers]=useState<User[]>([]),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 async function load(){const r=await fetch("/api/admin/sales-users",{cache:"no-store"});const d=await r.json().catch(()=>null);if(r.ok)setUsers(Array.isArray(d?.users)?d.users:[]);else setError(d?.error||"Could not load users")}
 useEffect(()=>{load()},[]);
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");setError("");try{const r=await fetch("/api/admin/sales-users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,email,password})});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error||"Could not create salesperson");setMessage(`Sales user ${name} created successfully.`);setName("");setEmail("");setPassword("");await load()}catch(e){setError(e instanceof Error?e.message:"Could not create salesperson")}finally{setBusy(false)}}
 return <section className="admin-panel"><div className="panel-head"><div><span className="admin-kicker">SALES TEAM</span><h3>Create new sales user</h3></div></div><p className="panel-copy">Creates the Supabase login and CRM salesperson profile together.</p><form onSubmit={create} style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr)) auto",gap:10,marginTop:18}}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Full name" required/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Login email" required/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Temporary password" minLength={6} required/><button className="admin-primary-btn" disabled={busy}>{busy?"Creating…":"＋ Create Sales User"}</button></form>{message&&<div className="admin-success">{message}</div>}{error&&<div className="admin-error">{error}</div>}<div style={{overflowX:"auto",marginTop:20}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th>NAME</th><th>EMAIL</th><th>ROLE</th><th>STATUS</th></tr></thead><tbody>{users.map(u=><tr key={u.id||u.auth_user_id}><td><b>{u.name}</b></td><td>{u.email}</td><td>{u.role}</td><td>{u.is_active!==false?"Active":"Inactive"}</td></tr>)}</tbody></table>{!users.length&&<div style={{padding:20,opacity:.55}}>No sales users yet.</div>}</div></section>
}