"use client";
import {useState} from "react";
import "@/app/admin/admin.css";

type Props={name:string;role:string};
const sections=[
 ["Overview","Dashboard","◈"],
 ["Content","Packages","▣"],["Content","Itineraries","▤"],["Content","Destinations","⌖"],["Content","Offers","%"],["Content","Blogs","✎"],["Content","Reviews","★"],
 ["Operations","Batches","◷"],["Operations","Vehicles & Hotels","▱"],["Operations","Enquiries","◎"],
 ["Growth","SEO","⌕"],["Growth","Media Library","▧"],
 ["System","Users & Permissions","♙"],["System","Audit Log","≡"],["System","Settings","⚙"]
];
export default function AdminDashboard({name,role}:Props){const [active,setActive]=useState("Dashboard");const [busy,setBusy]=useState(false);async function logout(){setBusy(true);await fetch("/api/admin/logout",{method:"POST"});location.href="/admin/login"}return <div className="admin-shell"><aside className="admin-sidebar"><div className="admin-brand"><div className="admin-mark small">OAT</div><div><b>ON A TRIP</b><span>Admin Control Center</span></div></div><nav>{sections.map(([group,label,icon],i)=><div key={label}>{(i===0||sections[i-1][0]!==group)&&<small>{group}</small>}<button className={active===label?"active":""} onClick={()=>setActive(label)}><i>{icon}</i>{label}</button></div>)}</nav><div className="admin-user"><strong>{name}</strong><span>{role.replaceAll("_"," ")}</span><button onClick={logout}>{busy?"Signing out…":"Sign out"}</button></div></aside><main className="admin-main"><header className="admin-top"><div><span className="admin-kicker">CONTROL CENTER</span><h1>{active}</h1></div><a href="/" target="_blank" rel="noreferrer">View website ↗</a></header>{active==="Dashboard"?<DashboardHome/>:<ModulePlaceholder title={active}/>}</main></div>}
function DashboardHome(){return <><div className="admin-welcome"><div><h2>Good day 👋</h2><p>Your website operations at a glance.</p></div><div className="live-pill"><span/> Website content system ready</div></div><div className="admin-stats"><Stat n="—" label="Packages"/><Stat n="—" label="Upcoming Batches"/><Stat n="—" label="Enquiries"/><Stat n="—" label="Published Offers"/></div><div className="admin-grid"><section className="admin-panel"><div className="panel-head"><div><span className="admin-kicker">QUICK ACTIONS</span><h3>Manage your website</h3></div></div><div className="quick-grid"><button><b>＋</b><span>New Package</span><small>Create a destination package</small></button><button><b>⇧</b><span>Upload Itinerary</span><small>Add a PDF or day-wise plan</small></button><button><b>◷</b><span>New Batch</span><small>Add a departure date</small></button><button><b>⚙</b><span>Website Settings</span><small>Contact and business details</small></button></div></section><section className="admin-panel"><div className="panel-head"><div><span className="admin-kicker">SAFE PUBLISHING</span><h3>Draft → Review → Publish</h3></div></div><p className="panel-copy">Future content changes can be prepared as drafts, previewed, approved and published without editing the website code.</p><div className="workflow"><span>Draft</span><b>→</b><span>Review</span><b>→</b><span>Publish</span></div></section></div><section className="admin-panel"><div className="panel-head"><div><span className="admin-kicker">SECURITY</span><h3>Role-based access & audit history</h3></div></div><p className="panel-copy">Super Admin, Content Manager, Sales Manager, Operations Manager, Finance Manager and Developer roles are supported. Important package and content changes will be recorded in the audit log.</p></section></>}
function Stat({n,label}:{n:string;label:string}){return <div className="admin-stat"><strong>{n}</strong><span>{label}</span></div>}
function ModulePlaceholder({title}:{title:string}){return <section className="admin-panel module-placeholder"><div className="module-icon">{title==="Packages"?"▣":"✦"}</div><span className="admin-kicker">MODULE READY</span><h2>{title}</h2><p>This module is part of the On A Trip CMS foundation. The database and permission layer are prepared so this screen can manage live website content.</p><div className="coming">Next: connect this module to Supabase data.</div></section>}
