"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import type {CrmSession} from "@/lib/crm-auth";

type Lead=Record<string,any>;
const stages=["New","Contacted","Qualified","Hot","Quote Sent","Follow-up","Booked","Lost"];
const services=["Full Package","Flight","Hotel","Transport","Visa","Custom"];
const sources=["Website","Meta Ads","Instagram","Facebook","WhatsApp","Google","Walk-in","Referral","B2B","Sheet Import","Other"];
const cols=[["id","Query ID"],["query_text","Query"],["name","Customer Name"],["customer_type","Type"],["service_type","Service"],["destination","Travel"],["travel_date","Travel Date"],["travellers","Pax"],["status","Stage"],["company_name","Client / Company"],["phone","Phone"],["email","Email"],["source","Source"],["branch","Branch"],["priority","Priority"],["salesperson","Owner"],["value","Value"],["budget","Budget"],["follow_up","Follow-up"],["from_destination","From"],["to_destination","To"],["return_date","Return Date"],["adults","Adults"],["children","Children"],["infants","Infants"],["created_at","Created Date"],["notes","Notes"]];
const defaultCols=["id","name","customer_type","service_type","destination","travel_date","travellers","status","company_name","source","priority","salesperson","value","follow_up"];
const emptyForm={name:"",phone:"",whatsapp:"",email:"",query_text:"",customer_type:"Client",company_name:"",service_type:"Full Package",from_destination:"",to_destination:"",destination:"",status:"New",source:"Website",branch:"Hyderabad",priority:"Normal",value:"",budget:"",travel_date:"",return_date:"",adults:"1",children:"0",infants:"0",travellers:"1",follow_up:"",notes:""};
const money=(v:any)=>{const n=Number(v||0);return n?"₹"+Math.round(n).toLocaleString("en-IN"):"—"};
const dateText=(v:any)=>{if(!v)return "—";const d=new Date(String(v));return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})};
const parseCsv=(text:string)=>text.trim().split(/\r?\n/).map(x=>x.split(",").map(y=>y.replace(/^"|"$/g,"")));

export default function CrmCompleteLeadManager({session,initialLeads}:{session:CrmSession;initialLeads:Lead[]}){
 const [leads,setLeads]=useState(initialLeads||[]),[search,setSearch]=useState(""),[stage,setStage]=useState("All"),[service,setService]=useState("All"),[source,setSource]=useState("All"),[branch,setBranch]=useState("All"),[owner,setOwner]=useState("All"),[priority,setPriority]=useState("All"),[customerType,setCustomerType]=useState("All"),[follow,setFollow]=useState("All"),[advanced,setAdvanced]=useState(false),[columns,setColumns]=useState(defaultCols),[columnPanel,setColumnPanel]=useState(false),[selected,setSelected]=useState<string[]>([]),[edit,setEdit]=useState<Lead|null>(null),[form,setForm]=useState<any>(emptyForm),[owners,setOwners]=useState<any[]>([]),[notice,setNotice]=useState(""),[error,setError]=useState(""),[bulkStage,setBulkStage]=useState(""),[bulkOwner,setBulkOwner]=useState(""),[saved,setSaved]=useState<any[]>([]),[savedPanel,setSavedPanel]=useState(false);
 const file=useRef<HTMLInputElement>(null);
 const isAdmin=session.profile.role==="admin";
 useEffect(()=>{if(edit&&edit.id&&!edit.__new){fetch("/api/crm/leads/activity?enquiry_id="+encodeURIComponent(String(edit.id))).then(r=>r.ok?r.json():[]).then(d=>setActivities(Array.isArray(d)?d:[])).catch(()=>setActivities([]))}else setActivities([])},[edit]);
 useEffect(()=>{try{const x=localStorage.getItem("oat-lead-columns");if(x)setColumns(JSON.parse(x));const s=localStorage.getItem("oat-lead-views");if(s)setSaved(JSON.parse(s))}catch{};fetch("/api/crm/users").then(r=>r.ok?r.json():null).then(d=>setOwners((d?.users||[]).filter((x:any)=>x.role==="salesperson"&&x.is_active!==false))).catch(()=>{})},[]);
 const branchList=useMemo(()=>Array.from(new Set(leads.map(x=>x.branch).filter(Boolean))).sort(),[leads]);
 const ownerList=useMemo(()=>Array.from(new Set(leads.map(x=>x.salesperson).filter(Boolean))).sort(),[leads]);
 const filtered=useMemo(()=>leads.filter(l=>{const hay=[l.name,l.phone,l.whatsapp,l.email,l.destination,l.dest,l.company_name,l.salesperson,l.source,l.status,l.priority,l.branch,l.query_text,l.notes].join(" ").toLowerCase();if(search&&!hay.includes(search.toLowerCase()))return false;if(stage!=="All"&&l.status!==stage)return false;if(service!=="All"&&l.service_type!==service)return false;if(source!=="All"&&l.source!==source)return false;if(branch!=="All"&&l.branch!==branch)return false;if(owner!=="All"&&l.salesperson!==owner)return false;if(priority!=="All"&&l.priority!==priority)return false;if(customerType!=="All"&&(l.customer_type||"Client")!==customerType)return false;if(follow!=="All"){if(follow==="No Follow-up"&&l.follow_up)return false;const d=l.follow_up?new Date(l.follow_up):null;const t=new Date();t.setHours(0,0,0,0);if(follow==="Overdue"&&(!d||d>=t))return false;if(follow==="Upcoming"&&(!d||d<t))return false;if(follow==="Today"&&(!d||d.toDateString()!==t.toDateString()))return false}return true}),[leads,search,stage,service,source,branch,owner,priority,customerType,follow]);
 const setF=(k:string,v:any)=>setForm((x:any)=>({...x,[k]:v}));
 const openEdit=(l:Lead)=>{setEdit(l);setForm({...emptyForm,...l,destination:l.destination||l.dest||"",travellers:String(l.travellers||1),adults:String(l.adults||1),children:String(l.children||0),infants:String(l.infants||0),value:l.value==null?"":String(l.value),budget:l.budget==null?"":String(l.budget),travel_date:String(l.travel_date||"").slice(0,10),return_date:String(l.return_date||"").slice(0,10),follow_up:String(l.follow_up||"").slice(0,10)});setError("")};
 const newLead=()=>{setEdit({__new:true});setForm({...emptyForm});setError("")};
 async function save(e:any){e.preventDefault();setError("");const p={...form,dest:form.destination,to_destination:form.to_destination||form.destination,value:form.value===""?null:Number(form.value),budget:form.budget===""?null:Number(form.budget),travel_date:form.travel_date||null,return_date:form.return_date||null,follow_up:form.follow_up||null,travellers:Number(form.travellers)||0,adults:Number(form.adults)||0,children:Number(form.children)||0,infants:Number(form.infants)||0};try{const r=await fetch("/api/crm/leads",{method:edit&&edit.__new?"POST":"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(edit&&edit.__new?p:{id:edit.id,...p})});const d=await r.json();if(!r.ok)throw new Error(d?.error||"Could not save lead");const item=Array.isArray(d)?d[0]:d;setLeads(x=>edit&&edit.__new?[item,...x]:x.map(a=>String(a.id)===String(edit.id)?{...a,...item,...p}:a));setEdit(null);setNotice(edit&&edit.__new?"Lead created":"Lead updated")}catch(e){setError(e instanceof Error?e.message:"Save failed")}}
 async function bulkUpdate(){if(!selected.length)return;try{for(const id of selected){if(bulkStage)await fetch("/api/crm/leads",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status:bulkStage})});if(bulkOwner){const u=owners.find((x:any)=>String(x.id)===bulkOwner);if(u)await fetch("/api/crm/leads/assign",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,user_id:u.auth_user_id||u.user_id})})}}setNotice(String(selected.length)+" leads updated");setSelected([]);window.location.reload()}catch{setError("Bulk update failed")}}
 function toggle(id:string){setSelected(x=>x.includes(id)?x.filter(a=>a!==id):[...x,id])}
 function toggleCol(k:string){setColumns(x=>{const n=x.includes(k)?x.filter(a=>a!==k):[...x,k];localStorage.setItem("oat-lead-columns",JSON.stringify(n));return n})}
 function exportCsv(){const header=cols.map(x=>x[1]);const rows=filtered.map(l=>cols.map(x=>x[0]==="id"?"OAT-"+l.id:(l[x[0]]??"")));const csv=[header,...rows].map(r=>r.map(x=>"""+String(x).replace(/"/g,'""')+""").join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="on-a-trip-leads.csv";a.click()}
 function importCsv(f:File){f.text().then(async t=>{const rows=parseCsv(t),head=rows.shift()||[];let n=0;for(const row of rows){const p:any={};head.forEach((h,i)=>p[h.trim().toLowerCase().replace(/[^a-z0-9]+(.)/g,(_:string,c:string)=>c.toUpperCase())]=row[i]||"");if(p.name||p.phone||p.email){const r=await fetch("/api/crm/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)});if(r.ok)n++}}setNotice(String(n)+" leads imported");window.location.reload()}).catch(()=>setError("Import failed"))}
 async function addActivity(){if(!edit||edit.__new||!activityText.trim())return;const r=await fetch("/api/crm/leads/activity",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({enquiry_id:edit.id,activity_type:"note",subject:"Sales note",body:activityText.trim()})});if(r.ok){const d=await r.json();setActivities(a=>[d,...a]);setActivityText("")}}
 function downloadSample(){const h=["Name","Phone","WhatsApp","Email","Customer Type","Company Name","Service Type","From Destination","To Destination","Destination","Travel Date","Return Date","Adults","Children","Infants","Stage","Source","Branch","Priority","Lead Value","Budget","Follow-up","Notes"];const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([h.join(",")+"\n"],{type:"text/csv"}));a.download="on-a-trip-lead-import-sample.csv";a.click()}
 function saveView(){const name=prompt("Saved view name");if(!name)return;const v={name,search,stage,service,source,branch,owner,priority,customerType,follow,columns};const next=[...saved.filter(x=>x.name!==name),v];setSaved(next);localStorage.setItem("oat-lead-views",JSON.stringify(next));setNotice("View saved")}
 function applyView(v:any){setSearch(v.search);setStage(v.stage);setService(v.service);setSource(v.source);setBranch(v.branch);setOwner(v.owner);setPriority(v.priority);setCustomerType(v.customerType);setFollow(v.follow);setColumns(v.columns);setSavedPanel(false)}
 const all=filtered.length>0&&filtered.every(l=>selected.includes(String(l.id)));
 return <section className="complete-leads"><div className="complete-leads-head"><div><span>LEAD & QUERY MANAGEMENT</span><h1>All Queries / Leads</h1><p>Complete sales workspace: customer, trip, pax, source, owner, stage, value and follow-up.</p></div><div className="complete-head-actions"><button onClick={newLead}>＋ Query</button><button onClick={downloadSample}>Sample</button><button onClick={()=>file.current?.click()}>⇧ Import</button><button onClick={exportCsv}>⇩ Export</button><button onClick={()=>setSavedPanel(true)}>Saved Views</button><button onClick={()=>setAdvanced(!advanced)}>⚙ Advance Search</button><input ref={file} hidden type="file" accept=".csv" onChange={e=>{const f=e.target.files?.[0];if(f)importCsv(f)}}/></div></div>
 <div className="complete-filterbar"><select value={stage} onChange={e=>setStage(e.target.value)}><option>All</option>{stages.map(x=><option key={x}>{x}</option>)}</select><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search queries, client, company, destination…"/><select value={service} onChange={e=>setService(e.target.value)}><option>All</option>{services.map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>setAdvanced(!advanced)}>Advance Search</button><button onClick={saveView}>Save View</button><button onClick={()=>setColumnPanel(!columnPanel)}>Displayed Columns</button></div>
 {advanced&&<div className="complete-advanced"><select value={source} onChange={e=>setSource(e.target.value)}><option>All Sources</option>{sources.map(x=><option key={x}>{x}</option>)}</select><select value={branch} onChange={e=>setBranch(e.target.value)}><option>All Branches</option>{branchList.map(x=><option key={x}>{x}</option>)}</select><select value={owner} onChange={e=>setOwner(e.target.value)}><option>All Owners</option>{ownerList.map(x=><option key={x}>{x}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)}><option>All Priority</option><option>Urgent</option><option>High</option><option>Normal</option></select><select value={customerType} onChange={e=>setCustomerType(e.target.value)}><option>All Types</option><option>Client</option><option>Company</option></select><select value={follow} onChange={e=>setFollow(e.target.value)}><option>All Follow-ups</option><option>Overdue</option><option>Today</option><option>Upcoming</option><option>No Follow-up</option></select><button onClick={()=>{setSearch("");setStage("All");setService("All");setSource("All");setBranch("All");setOwner("All");setPriority("All");setCustomerType("All");setFollow("All")}}>Clear</button></div>}
 {columnPanel&&<div className="complete-columns"><b>Displayed Columns</b>{cols.map(x=><label key={x[0]}><input type="checkbox" checked={columns.includes(x[0])} onChange={()=>toggleCol(x[0])}/>{x[1]}</label>)}</div>}
 <div className="complete-meta"><span><b>{filtered.length}</b> records</span><span>Selected {selected.length}</span></div>
 {selected.length>0&&<div className="complete-bulk"><b>{selected.length} selected</b><select value={bulkStage} onChange={e=>setBulkStage(e.target.value)}><option value="">Stage…</option>{stages.map(x=><option key={x}>{x}</option>)}</select>{isAdmin&&<select value={bulkOwner} onChange={e=>setBulkOwner(e.target.value)}><option value="">Owner…</option>{owners.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select>}<button onClick={bulkUpdate}>Apply</button><button onClick={()=>setSelected([])}>Clear</button></div>}
 <div className="complete-table-wrap"><table><thead><tr><th><input type="checkbox" checked={all} onChange={()=>setSelected(all?[]:filtered.map(l=>String(l.id)))}/></th>{columns.map(k=><th key={k}>{cols.find(x=>x[0]===k)?.[1]}</th>)}<th>Actions</th></tr></thead><tbody>{filtered.map(l=><tr key={String(l.id)}><td><input type="checkbox" checked={selected.includes(String(l.id))} onChange={()=>toggle(String(l.id))}/></td>{columns.map(k=><td key={k}>{k==="id"?"OAT-"+l.id:k==="travel_date"||k==="return_date"||k==="follow_up"||k==="created_at"?dateText(l[k]):k==="value"||k==="budget"?money(l[k]):k==="status"?<span className="lead-pill">{l[k]||"New"}</span>:k==="travellers"?String(l[k]||((Number(l.adults)||0)+(Number(l.children)||0)+(Number(l.infants)||0))):String(l[k]||"—")}</td>)}<td><button className="lead-open-btn" onClick={()=>openEdit(l)}>Edit</button></td></tr>)}</tbody></table></div>
 {savedPanel&&<div className="complete-overlay" onMouseDown={()=>setSavedPanel(false)}><aside className="complete-panel" onMouseDown={e=>e.stopPropagation()}><header><h2>Saved Views</h2><button onClick={()=>setSavedPanel(false)}>✕</button></header>{saved.map(v=><button key={v.name} onClick={()=>applyView(v)}>{v.name}</button>)}{!saved.length&&<p>No saved views yet.</p>}</aside></div>}
 {edit&&<div className="complete-overlay" onMouseDown={()=>setEdit(null)}><aside className="complete-drawer" onMouseDown={e=>e.stopPropagation()}><header><div><span>EDIT QUERY</span><h2>{edit.__new?"New Query":edit.name||"Query"}</h2></div><button onClick={()=>setEdit(null)}>✕</button></header><form onSubmit={save}>
 <div className="drawer-section"><h3>Travel For</h3><div className="radio-row"><label><input type="radio" checked={form.customer_type!=="Company"} onChange={()=>setF("customer_type","Client")}/> Client</label><label><input type="radio" checked={form.customer_type==="Company"} onChange={()=>setF("customer_type","Company")}/> Company</label></div><div className="lead-form-grid"><label>Customer Name<input required value={form.name} onChange={e=>setF("name",e.target.value)}/></label><label>Phone<input value={form.phone} onChange={e=>setF("phone",e.target.value)}/></label><label>WhatsApp<input value={form.whatsapp} onChange={e=>setF("whatsapp",e.target.value)}/></label><label>Email<input type="email" value={form.email} onChange={e=>setF("email",e.target.value)}/></label><label>Company Name<input value={form.company_name} onChange={e=>setF("company_name",e.target.value)}/></label><label>Query<input value={form.query_text} onChange={e=>setF("query_text",e.target.value)}/></label></div></div>
 <div className="drawer-section"><h3>Trip Details</h3><div className="lead-form-grid"><label>Service Type<select value={form.service_type} onChange={e=>setF("service_type",e.target.value)}>{services.map(x=><option key={x}>{x}</option>)}</select></label><label>Travel Date<input type="date" value={form.travel_date} onChange={e=>setF("travel_date",e.target.value)}/></label><label>Return Date<input type="date" value={form.return_date} onChange={e=>setF("return_date",e.target.value)}/></label><label>From Destination<input value={form.from_destination} onChange={e=>setF("from_destination",e.target.value)}/></label><label>To Destination<input value={form.to_destination} onChange={e=>setF("to_destination",e.target.value)}/></label><label>Destination<input value={form.destination} onChange={e=>setF("destination",e.target.value)}/></label></div></div>
 <div className="drawer-section"><h3>Pax Info</h3><div className="lead-form-grid"><label>Adults<input type="number" min="0" value={form.adults} onChange={e=>setF("adults",e.target.value)}/></label><label>Child<input type="number" min="0" value={form.children} onChange={e=>setF("children",e.target.value)}/></label><label>Infant<input type="number" min="0" value={form.infants} onChange={e=>setF("infants",e.target.value)}/></label><label>Total Pax<input type="number" min="0" value={form.travellers} onChange={e=>setF("travellers",e.target.value)}/></label></div></div>
 <div className="drawer-section"><h3>Sales & Follow-up</h3><div className="lead-form-grid"><label>Stage<select value={form.status} onChange={e=>setF("status",e.target.value)}>{stages.map(x=><option key={x}>{x}</option>)}</select></label><label>Priority<select value={form.priority} onChange={e=>setF("priority",e.target.value)}><option>Urgent</option><option>High</option><option>Normal</option></select></label><label>Source<select value={form.source} onChange={e=>setF("source",e.target.value)}>{sources.map(x=><option key={x}>{x}</option>)}</select></label><label>Branch<input value={form.branch} onChange={e=>setF("branch",e.target.value)}/></label><label>Lead Value<input value={form.value} onChange={e=>setF("value",e.target.value)}/></label><label>Budget<input value={form.budget} onChange={e=>setF("budget",e.target.value)}/></label><label>Follow-up<input type="date" value={form.follow_up} onChange={e=>setF("follow_up",e.target.value)}/></label></div></div>
 <div className="drawer-section"><h3>Notes</h3><textarea rows={5} value={form.notes} onChange={e=>setF("notes",e.target.value)}/></div><div className="drawer-section"><h3>Activity Timeline</h3><div className="lead-activity-list">{activities.map((a:any)=><div key={String(a.id)}><b>{a.subject||a.activity_type||"Activity"}</b><span>{a.body||""}</span><small>{dateText(a.created_at)}</small></div>)}{!activities.length&&<small>No activity recorded yet.</small>}</div>{edit&&!edit.__new&&<div className="lead-activity-add"><input value={activityText} onChange={e=>setActivityText(e.target.value)} placeholder="Add a sales note or activity…"/><button type="button" onClick={addActivity}>Add</button></div>}</div>{error&&<div className="crm-v2-form-error">{error}</div>}<footer><button type="button" onClick={()=>setEdit(null)}>Cancel</button><button className="primary" type="submit">Save Query</button></footer></form></aside></div>}
 </section>
}
