"use client";

import {useMemo,useState} from "react";
import type {CrmSession} from "@/lib/crm-auth";

type Lead=Record<string,unknown>&{id?:string|number;name?:string;phone?:string;email?:string;dest?:string;destination?:string;status?:string;salesperson?:string;source?:string;branch?:string;priority?:string;value?:string|number;follow_up?:string;travel_date?:string;travellers?:number;created_at?:string};

const stages=["New","Contacted","Qualified","Hot","Quote Sent","Follow-up","Booked","Lost"];
const score=(l:Lead)=>{let n=0;const status=String(l.status||"");const priority=String(l.priority||"");if(status==="Hot")n+=45;if(status==="Qualified")n+=25;if(status==="Quote Sent")n+=20;if(status==="Follow-up")n+=15;if(status==="Booked")n+=100;if(priority==="Urgent")n+=30;if(priority==="High")n+=20;if(Number(l.value||0)>=100000)n+=15;else if(Number(l.value||0)>=50000)n+=10;if(l.travel_date)n+=10;if(l.phone)n+=5;return Math.min(n,100)};
function digits(v:unknown){return String(v||"").replace(/\D/g,"")}
function dateText(v:unknown){if(!v)return "—";const d=new Date(String(v));return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString("en-IN",{day:"2-digit",month:"short"})}

export default function CrmLeadOpsPanel({session,initialLeads}:{session:CrmSession;initialLeads:Lead[]}){
 const [open,setOpen]=useState(false); const [mode,setMode]=useState<"actions"|"duplicates"|"bulk">("actions");
 const [leads,setLeads]=useState(initialLeads||[]); const [selected,setSelected]=useState<string[]>([]); const [stage,setStage]=useState("Hot");
 const [owner,setOwner]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
 const active=useMemo(()=>leads.filter(l=>String(l.status||"").toLowerCase()!=="deleted"),[leads]);
 const owners=useMemo(()=>Array.from(new Set(active.map(l=>String(l.salesperson||"")).filter(Boolean))).sort(),[active]);
 const today=useMemo(()=>{const d=new Date();d.setHours(0,0,0,0);return d},[]);
 const overdue=useMemo(()=>active.filter(l=>{if(!l.follow_up)return false;const d=new Date(String(l.follow_up));return !Number.isNaN(d.getTime())&&d<today&&String(l.status||"")!=="Booked"}),[active,today]);
 const dueSoon=useMemo(()=>active.filter(l=>{if(!l.follow_up)return false;const d=new Date(String(l.follow_up));if(Number.isNaN(d.getTime()))return false;const max=new Date(today);max.setDate(max.getDate()+2);return d>=today&&d<=max}),[active,today]);
 const hot=useMemo(()=>[...active].filter(l=>score(l)>=45&&String(l.status||"")!=="Booked").sort((a,b)=>score(b)-score(a)).slice(0,6),[active]);
 const duplicates=useMemo(()=>{const m=new Map<string,Lead[]>();active.forEach(l=>{const p=digits(l.phone);if(!p)return;const arr=m.get(p)||[];arr.push(l);m.set(p,arr)});return [...m.entries()].filter(([,arr])=>arr.length>1)},[active]);
 const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 async function bulkUpdate(){if(!selected.length)return;setBusy(true);setMessage("");try{for(const id of selected){const body:any={id};if(mode==="bulk"&&stage)body.status=stage;if(mode==="bulk"&&owner)body.salesperson=owner;const r=await fetch("/api/crm/leads",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw new Error("One or more leads could not be updated")}setLeads(ls=>ls.map(l=>selected.includes(String(l.id))?{...l,...(stage?{status:stage}:{}),...(owner?{salesperson:owner}:{})}:l));setMessage(`${selected.length} leads updated`);setSelected([])}catch(e){setMessage(e instanceof Error?e.message:"Update failed")}finally{setBusy(false)}}
 function exportLeads(){const head=["ID","Name","Phone","Destination","Status","Priority","Value","Follow-up","Salesperson","Source"];const rows=active.map(l=>[l.id,l.name,l.phone,l.dest||l.destination,l.status,l.priority,l.value,l.follow_up,l.salesperson,l.source]);const csv=[head,...rows].map(r=>r.map(x=>`"${String(x??"").replace(/"/g,'""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`on-a-trip-leads-${new Date().toISOString().slice(0,10)}.csv`;a.click();setMessage(`${active.length} leads exported`)}
 return <>
  <button className="lead-ops-launch" onClick={()=>setOpen(true)} title="Lead Operations">⚡ <span>Lead Ops</span></button>
  {open&&<div className="lead-ops-backdrop" onMouseDown={()=>setOpen(false)}><aside className="lead-ops-panel" onMouseDown={e=>e.stopPropagation()}>
   <header><div><span>ON A TRIP CRM</span><h2>Lead Operations</h2><p>Act on leads before opportunities go cold.</p></div><button onClick={()=>setOpen(false)}>✕</button></header>
   <div className="lead-ops-stats"><button onClick={()=>setMode("actions")}><b>{overdue.length}</b><span>Overdue</span></button><button onClick={()=>setMode("actions")}><b>{dueSoon.length}</b><span>Due next 48h</span></button><button onClick={()=>setMode("actions")}><b>{hot.length}</b><span>Hot leads</span></button><button onClick={()=>setMode("duplicates")}><b>{duplicates.length}</b><span>Duplicates</span></button></div>
   <div className="lead-ops-tabs"><button className={mode==="actions"?"active":""} onClick={()=>setMode("actions")}>Needs action</button><button className={mode==="duplicates"?"active":""} onClick={()=>setMode("duplicates")}>Duplicates</button><button className={mode==="bulk"?"active":""} onClick={()=>setMode("bulk")}>Bulk update</button></div>
   {mode==="actions"&&<div className="lead-ops-list">{[...overdue,...dueSoon,...hot.filter(l=>!overdue.includes(l)&&!dueSoon.includes(l))].slice(0,12).map(l=><div className="lead-ops-row" key={String(l.id)}><div><b>{String(l.name||"Unnamed")}</b><span>{String(l.dest||l.destination||"No destination")} · {String(l.status||"New")}</span><small>{l.follow_up?`Follow-up ${dateText(l.follow_up)}`:`Score ${score(l)}/100`}</small></div><div className="lead-ops-row-actions"><button onClick={()=>{window.open(`tel:${digits(l.phone)}`)}}>☎</button><button onClick={()=>{const p=digits(l.phone);if(p)window.open(`https://wa.me/${p.startsWith("91")?p:`91${p}`}`,"_blank")}}>WA</button></div></div>)}{!overdue.length&&!dueSoon.length&&!hot.length&&<div className="lead-ops-empty">No urgent lead actions right now.</div>}</div>}
   {mode==="duplicates"&&<div className="lead-ops-list">{duplicates.map(([p,arr])=><div className="lead-ops-duplicate" key={p}><strong>{p}</strong>{arr.map(l=><label key={String(l.id)}><input type="checkbox" checked={selected.includes(String(l.id))} onChange={()=>toggle(String(l.id))}/><span>{String(l.name||"Unnamed")} · {String(l.status||"New")} · {String(l.dest||l.destination||"—")}</span></label>)}<small>Review these records before merging.</small></div>)}{!duplicates.length&&<div className="lead-ops-empty">No duplicate phone numbers found.</div>}</div>}
   {mode==="bulk"&&<div className="lead-ops-bulk"><p>Select leads from the list below, then apply one action.</p><div className="lead-ops-controls"><label>Stage<select value={stage} onChange={e=>setStage(e.target.value)}>{stages.map(s=><option key={s}>{s}</option>)}</select></label><label>Salesperson<select value={owner} onChange={e=>setOwner(e.target.value)}><option value="">No change</option>{owners.map(o=><option key={o}>{o}</option>)}</select></label></div><button className="lead-ops-primary" disabled={!selected.length||busy} onClick={bulkUpdate}>{busy?"Updating…":`Apply to ${selected.length} selected`}</button><div className="lead-ops-select-list">{active.slice(0,60).map(l=><label key={String(l.id)}><input type="checkbox" checked={selected.includes(String(l.id))} onChange={()=>toggle(String(l.id))}/><span><b>{String(l.name||"Unnamed")}</b><small>{String(l.phone||"")} · {String(l.dest||l.destination||"—")}</small></span></label>)}</div></div>}
   <footer><button onClick={exportLeads}>⇩ Export all leads</button><span>{message}</span><em>{session.profile.role==="admin"?"Admin controls enabled":"Sales workspace"}</em></footer>
  </aside></div>}
 </>;
}
