"use client";
import {useEffect,useState} from "react";
type User={auth_user_id:string;name:string};
type Rule={id:string;name:string;is_active:boolean;priority:number;source?:string|null;branch?:string|null;destination?:string|null;lead_priority?:string|null;assignee_user_id?:string|null;assignee_name?:string|null;distribution_mode:string};
export default function CrmLeadDistribution(){
 const [open,setOpen]=useState(false),[rules,setRules]=useState<Rule[]>([]),[users,setUsers]=useState<User[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[name,setName]=useState(""),[source,setSource]=useState(""),[branch,setBranch]=useState(""),[destination,setDestination]=useState(""),[priority,setPriority]=useState(""),[assignee,setAssignee]=useState("");
 async function load(){const [r,u]=await Promise.all([fetch("/api/crm/lead-distribution"),fetch("/api/crm/users")]);const rd=await r.json().catch(()=>({}));const ud=await u.json().catch(()=>({}));setRules(Array.isArray(rd.rules)?rd.rules:[]);setUsers(Array.isArray(ud.users)?ud.users.filter((x:any)=>x.role==="salesperson"&&x.is_active!==false&&x.auth_user_id).map((x:any)=>({auth_user_id:x.auth_user_id,name:x.name||x.salesperson})):[])}
 useEffect(()=>{if(open)load()},[open]);
 async function add(){setBusy(true);setMsg("");try{const u=users.find(x=>x.auth_user_id===assignee);const r=await fetch("/api/crm/lead-distribution",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,source:source||null,branch:branch||null,destination:destination||null,lead_priority:priority||null,assignee_user_id:assignee||null,assignee_name:u?.name||null,priority:rules.length+1})});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error||"Could not create rule");setName("");setSource("");setBranch("");setDestination("");setPriority("");setAssignee("");await load();setMsg("Rule created")}catch(e){setMsg(e instanceof Error?e.message:"Could not create rule")}finally{setBusy(false)}}
 async function remove(id:string){if(!confirm("Delete this distribution rule?"))return;await fetch("/api/crm/lead-distribution",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});load()}
 async function auto(){setBusy(true);setMsg("");try{const r=await fetch("/api/crm/lead-distribution/apply",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error||"Could not distribute leads");setMsg((d.assigned||0)+" unassigned leads distributed")}catch(e){setMsg(e instanceof Error?e.message:"Distribution failed")}finally{setBusy(false)}}
 const input={padding:"9px 10px",border:"1px solid #d9e0e5",borderRadius:8,fontSize:12} as React.CSSProperties;
 return <><button className="lead-ops-launch" style={{right:130}} onClick={()=>setOpen(true)}>⚙ <span>Distribution</span></button>{open&&<div style={{position:"fixed",inset:0,zIndex:2000,background:"rgba(0,0,0,.35)",display:"flex",justifyContent:"flex-end"}} onMouseDown={()=>setOpen(false)}><aside onMouseDown={e=>e.stopPropagation()} style={{width:"min(560px,100%)",height:"100%",background:"#fff",padding:24,overflow:"auto",boxShadow:"-10px 0 40px rgba(0,0,0,.15)"}}><div style={{display:"flex",justifyContent:"space-between"}}><div><small>CRM ADMIN</small><h2 style={{margin:"4px 0"}}>Lead Distribution Rules</h2><p style={{opacity:.65,fontSize:12}}>Route new and unassigned leads to the right salesperson.</p></div><button onClick={()=>setOpen(false)}>✕</button></div><button disabled={busy} onClick={auto} style={{width:"100%",padding:12,border:0,borderRadius:9,background:"#111",color:"#fff",fontWeight:800,margin:"10px 0 18px"}}>{busy?"Working…":"⚡ Auto-distribute unassigned leads"}</button><section style={{padding:14,border:"1px solid #e5eaee",borderRadius:12}}><b>Create rule</b><div style={{display:"grid",gap:8,marginTop:10}}><input style={input} placeholder="Rule name e.g. Hyderabad Meta Leads" value={name} onChange={e=>setName(e.target.value)}/><input style={input} placeholder="Source (optional) e.g. Meta Ads" value={source} onChange={e=>setSource(e.target.value)}/><input style={input} placeholder="Branch (optional)" value={branch} onChange={e=>setBranch(e.target.value)}/><input style={input} placeholder="Destination contains (optional)" value={destination} onChange={e=>setDestination(e.target.value)}/><select style={input} value={priority} onChange={e=>setPriority(e.target.value)}><option value="">Any lead priority</option><option>Normal</option><option>High</option><option>Urgent</option></select><select style={input} value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Round-robin / automatic</option>{users.map(u=><option key={u.auth_user_id} value={u.auth_user_id}>{u.name}</option>)}</select><button disabled={busy||!name} onClick={add} style={{padding:11,border:0,borderRadius:8,background:"#f15a24",color:"#fff",fontWeight:800}}>＋ Add Distribution Rule</button></div></section>{msg&&<p style={{fontWeight:700}}>{msg}</p>}<div style={{marginTop:18,display:"grid",gap:8}}>{rules.map(r=><div key={r.id} style={{border:"1px solid #e5eaee",borderRadius:10,padding:12}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><b>{r.name}</b><button onClick={()=>remove(r.id)} style={{color:"#b42318",border:0,background:"transparent"}}>Delete</button></div><small>Priority {r.priority} · {r.assignee_name||"Round-robin"}{r.source?" · "+r.source:""}{r.branch?" · "+r.branch:""}{r.destination?" · "+r.destination:""}</small></div>)}</div></aside></div>}</>
}