"use client";
import {useState} from "react";
type User={id:string;name:string;email:string;role:string;is_active:boolean;auth_user_id?:string|null};
export default function CrmUserManager({initialUsers}:{initialUsers:User[]}){
 const [users,setUsers]=useState(initialUsers),[open,setOpen]=useState(false),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");setError("");try{const r=await fetch("/api/crm/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,email,password})});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error||"Could not create user");setUsers(v=>[...(v||[]),{id:d.user.id,name,email,role:"salesperson",is_active:true,auth_user_id:d.user.id}]);setMessage(`Sales user ${name} created successfully.`);setName("");setEmail("");setPassword("");setOpen(false)}catch(e){setError(e instanceof Error?e.message:"Could not create user")}finally{setBusy(false)}}
 return <><div style={{display:"flex",justifyContent:"flex-end",marginBottom:18}}><button onClick={()=>{setOpen(v=>!v);setError("");setMessage("")}} style={{padding:"12px 18px",border:0,borderRadius:10,background:"#111",color:"#fff",fontWeight:800,fontSize:15}}>{open?"✕ Close":"＋ Add New User"}</button></div>
 {open&&<section style={{background:"#fff",borderRadius:18,padding:20,marginBottom:18,border:"1px solid #e5eaee"}}><h3 style={{marginTop:0}}>Create CRM Sales User</h3><p style={{opacity:.65}}>Only CRM admins can create accounts. The new user can immediately sign in to the CRM.</p><form onSubmit={create} style={{display:"grid",gap:12}}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Full name" required/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Login email" required/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Temporary password" minLength={6} required/><button disabled={busy} style={{padding:13,border:0,borderRadius:10,background:"#f15a24",color:"#fff",fontWeight:800}}>{busy?"Creating…":"Create User"}</button></form>{message&&<p style={{color:"green",fontWeight:700}}>{message}</p>}{error&&<p style={{color:"#b42318",fontWeight:700}}>{error}</p>}</section>}
 <section style={{background:"#fff",borderRadius:18,overflow:"hidden",border:"1px solid #e5eaee"}}><div style={{padding:"18px 20px",borderBottom:"1px solid #e5eaee",fontWeight:800}}>CRM User Directory</div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:650}}><thead><tr><th style={{textAlign:"left",padding:14,fontSize:11}}>USER</th><th style={{textAlign:"left",padding:14,fontSize:11}}>ROLE</th><th style={{textAlign:"left",padding:14,fontSize:11}}>SALESPERSON</th><th style={{textAlign:"left",padding:14,fontSize:11}}>ACCESS</th></tr></thead><tbody>{users.map(u=><tr key={u.id||u.auth_user_id} style={{borderTop:"1px solid #edf0f2"}}><td style={{padding:14}}><b>{u.email}</b></td><td style={{padding:14}}>{u.role}</td><td style={{padding:14}}>{u.name||"—"}</td><td style={{padding:14,fontWeight:700}}>{u.is_active!==false?"✓ Active":"Inactive"}</td></tr>)}</tbody></table></div></section></>
}