"use client";
import {useState} from "react";
type User={id:string;name:string;email:string;role:string;is_active:boolean;auth_user_id?:string|null};

export default function CrmUserManager({initialUsers}:{initialUsers:User[]}){
 const [users,setUsers]=useState(initialUsers),[open,setOpen]=useState(false),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[showPassword,setShowPassword]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[editing,setEditing]=useState<User|null>(null),[editName,setEditName]=useState(""),[editEmail,setEditEmail]=useState(""),[editRole,setEditRole]=useState("salesperson"),[resetUser,setResetUser]=useState<User|null>(null),[resetPassword,setResetPassword]=useState(""),[showResetPassword,setShowResetPassword]=useState(false);

 async function call(method:string,body:any){const r=await fetch("/api/crm/users",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error||"Request failed");return d}
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");setError("");try{const d=await call("POST",{name,email,password});setUsers(v=>[...v,{id:d.user.id,name,email,role:"salesperson",is_active:true,auth_user_id:d.user.id}]);setMessage(`Sales user ${name} created successfully.`);setName("");setEmail("");setPassword("");setOpen(false)}catch(e){setError(e instanceof Error?e.message:"Could not create user")}finally{setBusy(false)}}
 function startEdit(u:User){setEditing(u);setEditName(u.name);setEditEmail(u.email);setEditRole(u.role)}
 async function saveEdit(e:React.FormEvent){e.preventDefault();if(!editing)return;setBusy(true);setError("");try{await call("PUT",{id:editing.id,name:editName,email:editEmail,role:editRole});setUsers(v=>v.map(u=>u.id===editing.id?{...u,name:editName,email:editEmail,role:editRole}:u));setMessage("User updated successfully.");setEditing(null)}catch(e){setError(e instanceof Error?e.message:"Could not update user")}finally{setBusy(false)}}
 async function resetPassword(e:React.FormEvent){e.preventDefault();if(!resetUser)return;setBusy(true);setError("");try{await call("PATCH",{action:"reset-password",id:resetUser.id,password:resetPassword});setMessage(`Password reset for ${resetUser.email}.`);setResetPassword("");setResetUser(null)}catch(e){setError(e instanceof Error?e.message:"Could not reset password")}finally{setBusy(false)}}
 async function deleteUser(u:User){if(!confirm(`Delete ${u.email}? This permanently removes the CRM account and login.`))return;setBusy(true);setError("");try{await call("DELETE",{id:u.id});setUsers(v=>v.filter(x=>x.id!==u.id));setMessage(`${u.email} deleted.`)}catch(e){setError(e instanceof Error?e.message:"Could not delete user")}finally{setBusy(false)}}
 const input={padding:"10px 12px",border:"1px solid #d9e0e5",borderRadius:8,fontSize:14} as React.CSSProperties;
 const action={padding:"7px 10px",border:"1px solid #d9e0e5",borderRadius:7,background:"#fff",fontWeight:700,cursor:"pointer"} as React.CSSProperties;
 return <><div style={{display:"flex",justifyContent:"flex-end",marginBottom:18}}><button onClick={()=>{setOpen(v=>!v);setError("");setMessage("")}} style={{padding:"12px 18px",border:0,borderRadius:10,background:"#111",color:"#fff",fontWeight:800,fontSize:15}}>{open?"✕ Close":"＋ Add New User"}</button></div>
 {open&&<section style={{background:"#fff",borderRadius:18,padding:20,marginBottom:18,border:"1px solid #e5eaee"}}><h3 style={{marginTop:0}}>Create CRM Sales User</h3><p style={{opacity:.65}}>Only CRM admins can create accounts. The new user can immediately sign in to the CRM.</p><form onSubmit={create} style={{display:"grid",gap:12}}><input style={input} value={name} onChange={e=>setName(e.target.value)} placeholder="Full name" required/><input style={input} type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Login email" required/><div style={{display:"flex",gap:8}}><input style={{...input,flex:1}} type={showPassword?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Temporary password" minLength={6} required/><button type="button" onClick={()=>setShowPassword(v=>!v)} style={action}>{showPassword?"Hide":"Show"} Password</button></div><button disabled={busy} style={{padding:13,border:0,borderRadius:10,background:"#f15a24",color:"#fff",fontWeight:800}}>{busy?"Creating…":"Create User"}</button></form></section>}
 {editing&&<section style={{background:"#fff",borderRadius:18,padding:20,marginBottom:18,border:"1px solid #e5eaee"}}><h3 style={{marginTop:0}}>Edit User</h3><form onSubmit={saveEdit} style={{display:"grid",gap:12}}><input style={input} value={editName} onChange={e=>setEditName(e.target.value)} placeholder="Full name" required/><input style={input} type="email" value={editEmail} onChange={e=>setEditEmail(e.target.value)} placeholder="Login email" required/><select style={input} value={editRole} onChange={e=>setEditRole(e.target.value)}><option value="salesperson">Salesperson</option><option value="admin">Admin</option><option value="accountant">Accountant</option><option value="operations">Operations</option><option value="manager">Manager</option><option value="staff">Staff</option></select><div><button disabled={busy} style={{padding:"10px 14px",border:0,borderRadius:8,background:"#111",color:"#fff",fontWeight:800}}>Save Changes</button> <button type="button" onClick={()=>setEditing(null)} style={action}>Cancel</button></div></form></section>}
 {resetUser&&<section style={{background:"#fff",borderRadius:18,padding:20,marginBottom:18,border:"1px solid #e5eaee"}}><h3 style={{marginTop:0}}>Reset Password</h3><p style={{opacity:.65}}>Set a new password for {resetUser.email}.</p><form onSubmit={resetPassword} style={{display:"grid",gap:12}}><div style={{display:"flex",gap:8}}><input style={{...input,flex:1}} type={showResetPassword?"text":"password"} value={resetPassword} onChange={e=>setResetPassword(e.target.value)} placeholder="New password" minLength={6} required/><button type="button" onClick={()=>setShowResetPassword(v=>!v)} style={action}>{showResetPassword?"Hide":"Show"} Password</button></div><div><button disabled={busy} style={{padding:"10px 14px",border:0,borderRadius:8,background:"#111",color:"#fff",fontWeight:800}}>Reset Password</button> <button type="button" onClick={()=>setResetUser(null)} style={action}>Cancel</button></div></form></section>}
 {message&&<p style={{color:"green",fontWeight:700}}>{message}</p>}{error&&<p style={{color:"#b42318",fontWeight:700}}>{error}</p>}
 <section style={{background:"#fff",borderRadius:18,overflow:"hidden",border:"1px solid #e5eaee"}}><div style={{padding:"18px 20px",borderBottom:"1px solid #e5eaee",fontWeight:800}}>CRM User Directory</div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:900}}><thead><tr><th style={{textAlign:"left",padding:14,fontSize:11}}>USER</th><th style={{textAlign:"left",padding:14,fontSize:11}}>ROLE</th><th style={{textAlign:"left",padding:14,fontSize:11}}>SALESPERSON</th><th style={{textAlign:"left",padding:14,fontSize:11}}>ACCESS</th><th style={{textAlign:"left",padding:14,fontSize:11}}>ACTIONS</th></tr></thead><tbody>{users.map(u=><tr key={u.id||u.auth_user_id} style={{borderTop:"1px solid #edf0f2"}}><td style={{padding:14}}><b>{u.email}</b></td><td style={{padding:14}}>{u.role}</td><td style={{padding:14}}>{u.name||"—"}</td><td style={{padding:14,fontWeight:700}}>{u.is_active!==false?"✓ Active":"Inactive"}</td><td style={{padding:14,display:"flex",gap:6,flexWrap:"wrap"}}><button onClick={()=>startEdit(u)} style={action}>Edit</button><button onClick={()=>{setResetUser(u);setShowResetPassword(false);setResetPassword("")}} style={action}>Reset Password</button><button onClick={()=>deleteUser(u)} disabled={busy} style={{...action,color:"#b42318"}}>Delete</button></td></tr>)}</tbody></table></div></section></>
}