"use client";
import {useMemo,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import * as XLSX from "xlsx";
import type {CrmSession} from "@/lib/crm-auth";

type Lead=Record<string,unknown>&{id?:string|number;name?:string;phone?:string;email?:string;dest?:string;destination?:string;status?:string;salesperson?:string;source?:string;sourceCategory?:string;branch?:string;priority?:string;value?:string|number;notes?:string;message?:string;follow?:string;date?:string;trav?:number;created_at?:string;callback_request?:unknown;payment_status?:string;remaining_payment?:string|number};
const stages=["New","Contacted","Qualified","Hot","Quote Sent","Follow-up","Booked","Lost"];
const sources=["Website","Meta Ads","Instagram","Facebook","WhatsApp","Google","Walk-in"];
const branches=["Hyderabad","Vijayawada"];

export default function CrmWorkspace({session,initialLeads}:{session:CrmSession;initialLeads:Lead[]}){
 const router=useRouter(); const [leads,setLeads]=useState(initialLeads); const [view,setView]=useState<"dashboard"|"leads"|"followups"|"quotations"|"settings">("dashboard");
 const [q,setQ]=useState(""); const [stage,setStage]=useState("All"); const [source,setSource]=useState("All"); const [branch,setBranch]=useState("All");
 const [modal,setModal]=useState<"new"|"detail"|"transfer"|"import"|null>(null); const [selected,setSelected]=useState<Lead|null>(null); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [salespeople,setSalespeople]=useState<{salesperson:string;email?:string}[]>([]);
 const [form,setForm]=useState<Record<string,string>>({name:"",phone:"",email:"",dest:"",value:"",branch:"Hyderabad",source:"Website",priority:"Normal",notes:"",status:"New",follow:"",date:"",trav:"2"});
 const fileRef=useRef<HTMLInputElement>(null); const isAdmin=session.profile.role==="admin";
 const accessible=useMemo(()=>leads.filter(l=>String(l.status||"").toLowerCase()!=="deleted"),[leads]);
 const filtered=useMemo(()=>accessible.filter(l=>{const hay=[l.name,l.phone,l.email,l.dest,l.destination,l.salesperson,l.source,l.status,l.branch,l.notes].join(" ").toLowerCase();return hay.includes(q.toLowerCase())&&(stage==="All"||String(l.status||"New")===stage)&&(source==="All"||String(l.source||"")===source)&&(branch==="All"||String(l.branch||"")===branch)}),[accessible,q,stage,source,branch]);
 const counts=useMemo(()=>Object.fromEntries(stages.map(s=>[s,accessible.filter(l=>String(l.status||"New")===s).length])),[accessible]);
 const followups=useMemo(()=>accessible.filter(l=>String(l.follow||"")||String(l.status||"")==="Follow-up"),[accessible]);
 const notifications=useMemo(()=>{const today=new Date();today.setHours(0,0,0,0);return accessible.flatMap(l=>{const out:string[]=[];if(l.follow){const d=new Date(String(l.follow)+"T00:00:00");if(!isNaN(d.getTime())&&d<=today)out.push(`Callback due: ${l.name||"Lead"}`)}const raw=l as any;if(l.callback_request||raw.request||raw.comments?.toString().match(/callback/i))out.push(`Callback request: ${l.name||"Lead"}`);if(l.remaining_payment||/pending|partial|remaining|due|outstanding|unpaid/i.test(String(l.payment_status||"")))out.push(`Payment pending: ${l.name||"Lead"}`);return out});},[accessible]);
 const setField=(k:string,v:string)=>setForm(x=>({...x,[k]:v}));
 async function logout(){await fetch("/api/crm/logout",{method:"POST"});router.push("/crm/login");router.refresh()}
 async function createLead(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");try{const payload={...form,travellers:Number(form.trav||0),travel_date:form.date||null,follow_up:form.follow||null};delete (payload as any).dest;delete (payload as any).trav;delete (payload as any).date;delete (payload as any).follow;const r=await fetch("/api/crm/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d?.message||d?.error||"Could not create lead");setModal(null);setNotice("Lead created successfully");router.refresh()}catch(e){setError(e instanceof Error?e.message:"Could not create lead")}finally{setSaving(false)}}
 async function updateLead(patch:Record<string,unknown>){if(!selected?.id)return;setSaving(true);setError("");try{const r=await fetch("/api/crm/leads",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:selected.id,...patch})});if(!r.ok)throw new Error("Update failed");setLeads(ls=>ls.map(x=>String(x.id)===String(selected.id)?{...x,...patch}:x));setSelected(x=>x?{...x,...patch}:x)}catch(e){setError(e instanceof Error?e.message:"Update failed")}finally{setSaving(false)}}
 async function deleteLead(id:string|number){if(!confirm("Delete this lead?"))return;const r=await fetch("/api/crm/leads",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});if(r.ok){setLeads(ls=>ls.filter(x=>String(x.id)!==String(id)));setModal(null)}}
 async function openTransfer(l:Lead){setSelected(l);setError("");setModal("transfer");if(!salespeople.length){const r=await fetch("/api/crm/users");const d=await r.json();if(r.ok)setSalespeople(d.users||[])}}
 async function transfer(){if(!selected?.id)return;const owner=(document.getElementById("crm-transfer-owner") as HTMLSelectElement)?.value;if(!owner)return setError("Select a salesperson.");setSaving(true);const r=await fetch("/api/crm/transfer",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:selected.id,salesperson:owner})});if(!r.ok){const d=await r.json();setError(d.error||"Transfer failed")}else{setLeads(ls=>ls.map(x=>String(x.id)===String(selected.id)?{...x,salesperson:owner}:x));setModal(null);setNotice(`Lead transferred to ${owner}`)}setSaving(false)}
 function openQuotation(l:Lead){const p=new URLSearchParams({leadId:String(l.id||""),name:String(l.name||""),phone:String(l.phone||""),destination:String(l.dest||l.destination||""),travelDate:String(l.date||""),travellers:String(l.trav||"")});try{localStorage.setItem("onatrip_selected_lead",JSON.stringify(l))}catch{};router.push(`/admin-ai-itinerary.html?${p.toString()}`)}
 function exportExcel(){const rows=filtered.map(l=>({Name:l.name||"",Phone:l.phone||"",Email:l.email||"",Destination:l.dest||l.destination||"",TravelDate:l.date||"",Travellers:l.trav||"",Value:l.value||"",Branch:l.branch||"",Source:l.source||"",Priority:l.priority||"",Status:l.status||"",Salesperson:l.salesperson||"",FollowUp:l.follow||"",Notes:l.notes||"",Created:l.created_at||""}));const ws=XLSX.utils.json_to_sheet(rows);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Leads");XLSX.writeFile(wb,`on-a-trip-crm-${new Date().toISOString().slice(0,10)}.xlsx`)}
 async function importExcel(file:File){setError("");try{const wb=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:true});const ws=wb.Sheets[wb.SheetNames[0]];const raw=XLSX.utils.sheet_to_json<Record<string,unknown>>(ws,{defval:""});const rows=raw.map(r=>({name:String(r.Name??r.name??"").trim(),phone:String(r.Phone??r.phone??"").trim(),destination:String(r.Destination??r.destination??"").trim(),travel_date:r.TravelDate||r["Travel Date"]||null,travellers:Number(r.Travellers||r.travellers||0)||0,branch:String(r.Branch||r.branch||"Hyderabad"),source:String(r.Source||r.source||"Sheet Import"),priority:String(r.Priority||r.priority||"Normal"),status:String(r.Status||r.status||"New"),value:String(r.Value||r.value||""),follow_up:r.FollowUp||r["Follow-up"]||null,notes:String(r.Notes||r.notes||"")})).filter(r=>r.name||r.phone||r.destination);const r=await fetch("/api/crm/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({rows})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Import failed");setNotice(`${d.imported} lead(s) imported • ${d.skipped} skipped`);router.refresh()}catch(e){setError(e instanceof Error?e.message:"Could not import sheet")}finally{if(fileRef.current)fileRef.current.value=""}}
 function openLead(l:Lead){setSelected(l);setError("");setModal("detail")}
 const whatsapp=(l:Lead)=>{let p=String(l.phone||"").replace(/\D/g,"");if(p.length===10)p="91"+p;window.open(`https://wa.me/${p}?text=${encodeURIComponent(`Hi ${l.name||""}, this is On A Trip Holidays. Regarding your ${l.dest||"travel"} enquiry. I can share the latest package, batch and offer details.`)}`,"_blank")};
 return <main className="crm-shell"><aside className="crm-sidebar"><div className="crm-brand"><div className="crm-mark">OAT</div><div><b>ON A TRIP</b><span>HOLIDAYS CRM</span></div></div><nav><button className={view==="dashboard"?"active":""} onClick={()=>setView("dashboard")}>⌂ <span>Dashboard</span></button><button className={view==="leads"?"active":""} onClick={()=>setView("leads")}>◉ <span>Leads</span></button><button className={view==="followups"?"active":""} onClick={()=>setView("followups")}>↻ <span>Follow-ups <i>{followups.length}</i></span></button><button className={view==="quotations"?"active":""} onClick={()=>setView("quotations")}>▣ <span>Quotations</span></button><button className={view==="settings"?"active":""} onClick={()=>setView("settings")}>⚙ <span>CRM Settings</span></button></nav><div className="crm-user"><b>{session.profile.salesperson||session.user.email||"Admin"}</b><span>{isAdmin?"Administrator":"Salesperson"}</span><button onClick={logout}>Logout</button></div></aside>
 <section className="crm-content"><header className="crm-top"><div><span className="crm-kicker">ON A TRIP HOLIDAYS</span><strong>{isAdmin?"CRM Control Center":"Sales CRM"}</strong></div><div className="crm-top-actions"><button onClick={()=>setView("leads")}>⌕ Search CRM</button><button className="notification-btn" onClick={()=>setView("followups")}>🔔 {notifications.length?`(${notifications.length})`:""}</button><button onClick={()=>router.push("/")}>Website ↗</button></div></header>{notice&&<div className="crm-notice" onClick={()=>setNotice("")}>{notice}</div>}
 {view==="dashboard"&&<Dashboard counts={counts} total={accessible.length} followups={followups.length} notifications={notifications.length} onNew={()=>setModal("new")} onLeads={()=>setView("leads")} onFollow={()=>setView("followups")} onStage={(s)=>{setStage(s);setView("leads")}} />}
 {view==="leads"&&<section className="crm-page"><div className="crm-heading"><div><span className="crm-kicker">LEADS HUB</span><h1>{isAdmin?"All Real Enquiries":"My Leads"}</h1><p>{isAdmin?"Company-wide enquiry pipeline.":`Leads assigned to ${session.profile.salesperson||"your profile"}.`}</p></div><div className="heading-actions"><button onClick={()=>setView("dashboard")}>← Dashboard</button><button className="primary" onClick={()=>setModal("new")}>＋ New Lead</button></div></div><div className="crm-filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search customer, phone, destination…"/><select value={stage} onChange={e=>setStage(e.target.value)}><option>All</option>{stages.map(s=><option key={s}>{s}</option>)}</select><select value={source} onChange={e=>setSource(e.target.value)}><option>All</option>{sources.map(s=><option key={s}>{s}</option>)}</select><select value={branch} onChange={e=>setBranch(e.target.value)}><option>All</option>{branches.map(s=><option key={s}>{s}</option>)}</select><button onClick={exportExcel}>⇩ Export</button><button onClick={()=>fileRef.current?.click()}>⇧ Import</button><input ref={fileRef} type="file" accept=".xlsx,.xls,.csv" hidden onChange={e=>e.target.files?.[0]&&importExcel(e.target.files[0])}/></div><div className="crm-panel"><div className="result-line"><b>{filtered.length} leads</b><span>{stage} · {source} · {branch}</span></div><LeadTable leads={filtered} onOpen={openLead} onDelete={isAdmin?deleteLead:undefined} onTransfer={isAdmin?openTransfer:undefined} onQuote={openQuotation} onWhatsApp={whatsapp}/></div></section>}
 {view==="followups"&&<section className="crm-page"><div className="crm-heading"><div><span className="crm-kicker">FOLLOW-UP CENTER</span><h1>Callbacks & Follow-ups</h1><p>Prioritize leads that need action today.</p></div><button onClick={()=>setView("leads")}>Open Leads →</button></div><div className="crm-panel"><LeadTable leads={followups} onOpen={openLead} onTransfer={isAdmin?openTransfer:undefined} onQuote={openQuotation} onWhatsApp={whatsapp}/></div></section>}
 {view==="quotations"&&<section className="crm-page"><div className="crm-heading"><div><span className="crm-kicker">QUOTATION CENTER</span><h1>Generate Quotations</h1><p>Choose a lead and continue to the existing AI itinerary/quotation workflow.</p></div></div><div className="crm-panel"><LeadTable leads={accessible.filter(l=>["Qualified","Hot","Quote Sent","Booked"].includes(String(l.status||"New")))} onOpen={openLead} onQuote={openQuotation} onWhatsApp={whatsapp}/></div></section>}
 {view==="settings"&&<section className="crm-page"><div className="crm-heading"><div><span className="crm-kicker">CRM SETTINGS</span><h1>Workspace settings</h1><p>CRM configuration areas from the original application, now inside the Next.js workspace.</p></div></div><div className="crm-grid"><div className="crm-panel settings-card"><h2>Lead stages</h2>{stages.map(s=><div key={s} className="setting-row"><span>{s}</span><b>{counts[s]}</b></div>)}</div><div className="crm-panel settings-card"><h2>Sources</h2>{sources.map(s=><div key={s} className="setting-row"><span>{s}</span><span>Active</span></div>)}</div></div></section>}
 </section>
 {modal==="new"&&<Modal title="Create enquiry" kicker="NEW LEAD" close={()=>setModal(null)}><form className="form-grid" onSubmit={createLead}>{[["name","Customer name",""],["phone","Phone / WhatsApp",""],["email","Email",""],["dest","Destination / Package",""],["date","Travel date","date"],["trav","Travellers","number"],["value","Expected value",""],["follow","Next follow-up","date"]].map(([k,l,t])=><label key={k}>{l}<input type={t||"text"} value={form[k]} onChange={e=>setField(k,e.target.value)} required={k==="name"||k==="phone"}/></label>)}<label>Branch<select value={form.branch} onChange={e=>setField("branch",e.target.value)}>{branches.map(x=><option key={x}>{x}</option>)}</select></label><label>Source<select value={form.source} onChange={e=>setField("source",e.target.value)}>{sources.map(x=><option key={x}>{x}</option>)}</select></label><label>Priority<select value={form.priority} onChange={e=>setField("priority",e.target.value)}><option>Normal</option><option>High</option><option>Hot</option></select></label><label className="full">Notes<textarea value={form.notes} onChange={e=>setField("notes",e.target.value)} rows={4}/></label>{error&&<p className="crm-error full">{error}</p>}<div className="modal-actions full"><button type="button" onClick={()=>setModal(null)}>Cancel</button><button className="primary" disabled={saving}>{saving?"Creating…":"Create Lead"}</button></div></form></Modal>}
 {modal==="detail"&&selected&&<Modal title={selected.name||"Lead"} kicker="LEAD DETAILS" close={()=>setModal(null)}><div className="detail-grid">{[["Phone",selected.phone],["Destination",selected.dest||selected.destination],["Travel Date",selected.date],["Travellers",selected.trav],["Status",selected.status],["Priority",selected.priority],["Branch",selected.branch],["Source",selected.source],["Expected Value",selected.value],["Follow-up",selected.follow]].map(([k,v])=><div key={String(k)}><span>{k}</span><b>{String(v||"—")}</b></div>)}</div><div className="detail-notes"><span>Notes</span><p>{String(selected.notes||"No notes added.")}</p><span>Customer Message</span><p>{String(selected.message||"No message.")}</p></div><label className="status-editor">Update status<select value={String(selected.status||"New")} onChange={e=>updateLead({status:e.target.value})}>{stages.map(s=><option key={s}>{s}</option>)}</select></label>{error&&<p className="crm-error">{error}</p>}<div className="modal-actions"><button className="whatsapp" onClick={()=>whatsapp(selected)}>WhatsApp</button><a href={selected.phone?`tel:${selected.phone}`:"#"}>Call</a><button className="primary" onClick={()=>openQuotation(selected)}>Generate Quotation</button>{isAdmin&&<button className="danger" onClick={()=>deleteLead(selected.id!)}>Delete</button>}<button onClick={()=>setModal(null)}>Close</button></div></Modal>}
 {modal==="transfer"&&selected&&<Modal title="Transfer Lead" kicker="LEAD OWNERSHIP" close={()=>setModal(null)}><p className="muted-line">{selected.name||"Lead"} • Current owner: {selected.salesperson||"Unassigned"}</p><label>Transfer to salesperson<select id="crm-transfer-owner" defaultValue=""><option value="">Select salesperson</option>{salespeople.map(u=><option key={u.salesperson} value={u.salesperson}>{u.salesperson}{u.email?` • ${u.email}`:""}</option>)}</select></label>{error&&<p className="crm-error">{error}</p>}<div className="modal-actions"><button onClick={()=>setModal(null)}>Cancel</button><button className="primary" disabled={saving} onClick={transfer}>{saving?"Transferring…":"Transfer Lead"}</button></div></Modal>}
 </main>
}
function Dashboard({counts,total,followups,notifications,onNew,onLeads,onFollow,onStage}:{counts:Record<string,number>;total:number;followups:number;notifications:number;onNew:()=>void;onLeads:()=>void;onFollow:()=>void;onStage:(s:string)=>void}){return <section className="crm-page"><div className="crm-welcome"><div><span>CRM WORKSPACE</span><h1>Sales Control Center</h1><p>Manage enquiries, ownership, follow-ups and quotations from one place.</p></div><button className="primary" onClick={onNew}>＋ New Lead</button></div><div className="crm-stats"><button onClick={onLeads}><strong>{total}</strong><span>Total Leads</span></button><button onClick={onFollow}><strong>{followups}</strong><span>Follow-ups</span></button><button onClick={onFollow}><strong>{notifications}</strong><span>Notifications</span></button><button onClick={()=>onStage("Booked")}><strong>{counts.Booked||0}</strong><span>Booked</span></button></div><div className="crm-panel"><div className="panel-head"><div><span>SALES PIPELINE</span><h2>Lead stages</h2></div><button onClick={onLeads}>View all</button></div><div className="pipeline">{stages.map(s=><button key={s} onClick={()=>onStage(s)}><b>{counts[s]||0}</b><span>{s}</span></button>)}</div></div></section>}
function LeadTable({leads,onOpen,onDelete,onTransfer,onQuote,onWhatsApp}:{leads:Lead[];onOpen:(l:Lead)=>void;onDelete?:(id:string|number)=>void;onTransfer?:(l:Lead)=>void;onQuote?:(l:Lead)=>void;onWhatsApp?:(l:Lead)=>void}){return <div className="crm-table-wrap"><table><thead><tr><th>Customer</th><th>Phone</th><th>Destination</th><th>Status</th><th>Owner</th><th>Follow-up</th><th>Actions</th></tr></thead><tbody>{leads.map((l,i)=><tr key={String(l.id??i)}><td><button className="link-btn" onClick={()=>onOpen(l)}><b>{String(l.name||"Unknown")}</b><small>{String(l.email||"")}</small></button></td><td>{String(l.phone||"—")}</td><td>{String(l.dest||l.destination||"—")}</td><td><span className={`crm-pill ${String(l.status||"New").toLowerCase().replace(/\s/g,"-")}`}>{String(l.status||"New")}</span></td><td>{String(l.salesperson||"Unassigned")}</td><td>{String(l.follow||"—")}</td><td className="lead-actions"><button onClick={()=>onWhatsApp?.(l)} title="WhatsApp">WA</button>{onQuote&&<button onClick={()=>onQuote(l)} title="Quotation">Quote</button>}{onTransfer&&<button onClick={()=>onTransfer(l)} title="Transfer">Transfer</button>}{onDelete&&<button className="mini-danger" onClick={()=>onDelete(l.id!)}>Delete</button>}</td></tr>)}{!leads.length&&<tr><td colSpan={7} className="crm-empty">No matching leads.</td></tr>}</tbody></table></div>}
function Modal({title,kicker,close,children}:{title:string;kicker:string;close:()=>void;children:React.ReactNode}){return <div className="crm-modal-bg"><div className="crm-modal"><div className="modal-head"><div><span>{kicker}</span><h2>{title}</h2></div><button onClick={close}>×</button></div>{children}</div></div>}
