"use client";
import {useMemo,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import type {CrmSession} from "@/lib/crm-auth";

type XlsxApi={utils:{json_to_sheet:(rows:unknown[])=>unknown;book_new:()=>unknown;book_append_sheet:(wb:unknown,ws:unknown,name:string)=>void;sheet_to_json:<T=Record<string,unknown>>(ws:unknown,opts?:Record<string,unknown>)=>T[]};writeFile:(wb:unknown,name:string)=>void;read:(data:ArrayBuffer,opts:Record<string,unknown>)=>{Sheets:Record<string,unknown>;SheetNames:string[]}};
declare global{interface Window{XLSX:XlsxApi}}

type Lead=Record<string,unknown>&{id?:string|number;name?:string;phone?:string;email?:string;dest?:string;destination?:string;status?:string;salesperson?:string;source?:string;branch?:string;priority?:string;value?:string|number;notes?:string;follow?:string;date?:string;trav?:number;created_at?:string;callback_request?:unknown;payment_status?:string;remaining_payment?:string|number};
const stages=["New","Contacted","Qualified","Hot","Quote Sent","Follow-up","Booked","Lost"];
const sources=["Website","Meta Ads","Instagram","Facebook","WhatsApp","Google","Walk-in","Sheet Import"];
const branches=["Hyderabad","Vijayawada"];

export default function CrmWorkspace({session,initialLeads}:{session:CrmSession;initialLeads:Lead[]}){
 const router=useRouter();const [leads,setLeads]=useState(initialLeads);const [view,setView]=useState<"dashboard"|"leads"|"followups"|"quotations"|"settings">("dashboard");
 const [q,setQ]=useState("");const [stage,setStage]=useState("All");const [source,setSource]=useState("All");const [branch,setBranch]=useState("All");const [option,setOption]=useState<"all"|"mine"|"unassigned"|"metaFailed"|"bin">("all");
 const [modal,setModal]=useState<"new"|"detail"|"transfer"|"quotation"|null>(null);const [selected,setSelected]=useState<Lead|null>(null);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [salespeople,setSalespeople]=useState<{salesperson:string;email?:string}[]>([]);const [searchOpen,setSearchOpen]=useState(false);
 const [form,setForm]=useState<Record<string,string>>({name:"",phone:"",email:"",dest:"",value:"",branch:"Hyderabad",source:"Website",priority:"Normal",notes:"",status:"New",follow:"",date:"",trav:"2",salesperson:""});
 const fileRef=useRef<HTMLInputElement>(null);const isAdmin=session.profile.role==="admin";
 const accessible=useMemo(()=>option==="bin"?leads.filter(l=>String(l.status||"").toLowerCase()==="deleted"):leads.filter(l=>String(l.status||"").toLowerCase()!=="deleted"),[leads,option]);
 const optionLeads=useMemo(()=>accessible.filter(l=>option==="all"||option==="bin"?true:option==="mine"?String(l.salesperson||"")===String(session.profile.salesperson||""):option==="unassigned"?!l.salesperson:option==="metaFailed"&&/meta/i.test(String(l.source||""))&&/fail|invalid|error/i.test(JSON.stringify(l))),[accessible,option,session.profile.salesperson]);
 const filtered=useMemo(()=>optionLeads.filter(l=>{const hay=[l.name,l.phone,l.email,l.dest,l.destination,l.salesperson,l.source,l.status,l.branch,l.notes].join(" ").toLowerCase();return hay.includes(q.toLowerCase())&&(stage==="All"||String(l.status||"New")===stage)&&(source==="All"||String(l.source||"")===source)&&(branch==="All"||String(l.branch||"")===branch)}),[optionLeads,q,stage,source,branch]);
 const counts=useMemo(()=>Object.fromEntries(stages.map(s=>[s,leads.filter(l=>String(l.status||"New")===s).length])),[leads]);
 const followups=useMemo(()=>leads.filter(l=>String(l.status||"").toLowerCase()!=="deleted"&&(String(l.follow||"")||String(l.status||"")==="Follow-up")),[leads]);
 const notifications=useMemo(()=>{const today=new Date();today.setHours(0,0,0,0);return leads.filter(l=>String(l.status||"").toLowerCase()!=="deleted").flatMap(l=>{const out:string[]=[];if(l.follow){const d=new Date(String(l.follow)+"T00:00:00");if(!isNaN(d.getTime())&&d<=today)out.push(`Callback due: ${l.name||"Lead"}`)}const raw=l as any;if(l.callback_request||raw.request||String(raw.comments||"").match(/callback/i))out.push(`Callback request: ${l.name||"Lead"}`);if(l.remaining_payment||/pending|partial|remaining|due|outstanding|unpaid/i.test(String(l.payment_status||"")))out.push(`Payment pending: ${l.name||"Lead"}`);return out})},[leads]);
 const setField=(k:string,v:string)=>setForm(x=>({...x,[k]:v));
 async function logout(){await fetch("/api/crm/logout",{method:"POST"});router.push("/crm/login");router.refresh()}
 async function createLead(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");try{const payload={...form,travellers:Number(form.trav||0),travel_date:form.date||null,follow_up:form.follow||null};delete(payload as any).dest;delete(payload as any).trav;delete(payload as any).date;delete(payload as any).follow;const r=await fetch("/api/crm/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw Error(d?.message||d?.error||"Could not create lead");setModal(null);setNotice("Lead created successfully");router.refresh()}catch(e){setError(e instanceof Error?e.message:"Could not create lead")}finally{setSaving(false)}}
 async function updateLead(patch:Record<string,unknown>){if(!selected?.id)return;setSaving(true);setError("");try{const r=await fetch("/api/crm/leads",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:selected.id,...patch})});if(!r.ok){const d=await r.json().catch(()=>({}));throw Error(d.error||"Update failed")}setLeads(ls=>ls.map(x=>String(x.id)===String(selected.id)?{...x,...patch}:x));setSelected(x=>x?{...x,...patch}:x);setNotice("Lead updated") }catch(e){setError(e instanceof Error?e.message:"Update failed")}finally{setSaving(false)}}
 async function deleteLead(id:string|number){if(!confirm("Move this lead to the CRM Bin?"))return;const r=await fetch("/api/crm/leads",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});if(r.ok){setLeads(ls=>ls.map(x=>String(x.id)===String(id)?{...x,status:"Deleted"}:x));setModal(null);setNotice("Lead moved to Bin")}}
 async function openTransfer(l:Lead){setSelected(l);setError("");setModal("transfer");if(!salespeople.length){const r=await fetch("/api/crm/users");const d=await r.json();if(r.ok)setSalespeople(d.users||[])}}
 async function transfer(){if(!selected?.id)return;const owner=(document.getElementById("crm-transfer-owner") as HTMLSelectElement)?.value;if(!owner)return setError("Select a salesperson.");setSaving(true);const r=await fetch("/api/crm/transfer",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:selected.id,salesperson:owner})});if(!r.ok){const d=await r.json();setError(d.error||"Transfer failed")}else{setLeads(ls=>ls.map(x=>String(x.id)===String(selected.id)?{...x,salesperson:owner}:x));setModal(null);setNotice(`Lead transferred to ${owner}`)}setSaving(false)}
 function openQuotation(l:Lead){setSelected(l);setModal("quotation")}
 function continueQuotation(){if(!selected)return;try{localStorage.setItem("onatrip_selected_lead",JSON.stringify(selected))}catch{};const p=new URLSearchParams({leadId:String(selected.id||""),name:String(selected.name||""),phone:String(selected.phone||""),destination:String(selected.dest||selected.destination||""),travelDate:String(selected.date||""),travellers:String(selected.trav||"")});router.push(`/crm/itinerary?${p}`)}
 function exportExcel(){const XLSX=window.XLSX;if(!XLSX)return setError("Excel engine is still loading. Please try again.");const rows=filtered.map(l=>({Name:l.name||"",Phone:l.phone||"",Email:l.email||"",Destination:l.dest||l.destination||"",TravelDate:l.date||"",Travellers:l.trav||"",Value:l.value||"",Branch:l.branch||"",Source:l.source||"",Priority:l.priority||"",Status:l.status||"",Salesperson:l.salesperson||"",FollowUp:l.follow||"",Notes:l.notes||"",Created:l.created_at||""}));const ws=XLSX.utils.json_to_sheet(rows);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Leads");XLSX.writeFile(wb,`on-a-trip-crm-${new Date().toISOString().slice(0,10)}.xlsx`)}
 async function importExcel(file:File){setError("");try{const XLSX=window.XLSX;if(!XLSX)throw Error("Excel engine is still loading. Please try again.");const wb=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:true});const ws=wb.Sheets[wb.SheetNames[0]];const raw=XLSX.utils.sheet_to_json<Record<string,unknown>>(ws,{defval:""});const rows=raw.map(r=>({name:String(r.Name??r.name??"").trim(),phone:String(r.Phone??r.phone??"").trim(),email:String(r.Email??r.email??"").trim(),destination:String(r.Destination??r.destination??"").trim(),travel_date:r.TravelDate||r["Travel Date"]||null,travellers:Number(r.Travellers||r.travellers||0)||0,branch:String(r.Branch||r.branch||"Hyderabad"),source:String(r.Source||r.source||"Sheet Import"),priority:String(r.Priority||r.priority||"Normal"),status:String(r.Status||r.status||"New"),value:String(r.Value||r.value||""),follow_up:r.FollowUp||r["Follow-up"]||null,notes:String(r.Notes||r.notes||"")})).filter(r=>r.name||r.phone||r.destination);if(!rows.length)throw Error("No valid lead rows found.");const r=await fetch("/api/crm/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({rows})});const d=await r.json();if(!r.ok)throw Error(d.error||"Import failed");setNotice(`${d.imported} lead(s) imported • ${d.skipped} skipped`);router.refresh()}catch(e){setError(e instanceof Error?e.message:"Could not import sheet")}finally{if(fileRef.current)fileRef.current.value=""}}
 function openLead(l:Lead){setSelected(l);setError("");setModal("detail")};const whatsapp=(l:Lead)=>{let p=String(l.phone||"").replace(/\D/g,"");if(p.length===10)p="91"+p;window.open(`https://wa.me/${p}?text=${encodeURIComponent(`Hi ${l.name||""}, this is On A Trip Holidays. Regarding your ${l.dest||"travel"} enquiry. I can share the latest package, batch and offer details.`)}`,"_blank")};
 return <main className="crm-shell"><aside className="crm-sidebar"><div className="crm-brand"><div className="crm-mark">OAT</div><div><b>ON A TRIP</b><span>HOLIDAYS CRM</span></div></div><nav><button className={view==="dashboard"?"active":""} onClick={()=>setView("dashboard")}>⌂ <span>Dashboard</span></button><button className={view==="leads"?"active":""} onClick={()=>setView("leads")}>◉ <span>Leads</span></button><button className={view==="followups"?"active":""} onClick={()=>setView("followups")}>↻ <span>Follow-ups <i>{followups.length}</i></span></button><button className={view==="quotations"?"active":""} onClick={()=>setView("quotations")}>▣ <span>Quotations</span></button><button className={view==="settings"?"active":""} onClick={()=>setView("settings")}>⚙ <span>CRM Settings</span></button></nav><div className="crm-user"><b>{session.profile.salesperson||session.user.email||"Admin"}</b><span>{isAdmin?"Administrator":"Salesperson"}</span><button onClick={logout}>Logout</button></div></aside><section className="crm-content"><header className="crm-top"><div><span className="crm-kicker">ON A TRIP HOLIDAYS</span><strong>{isAdmin?"CRM Control Center":"Sales CRM"}</strong></div><div className="crm-top-actions"><button onClick={()=>setSearchOpen(true)}>⌕ Search CRM</button><button className="notification-btn" onClick={()=>setView("followups")}>🔔 {notifications.length?`(${notifications.length})`:""}</button><button onClick={()=>router.push("/")}>Website ↗</button></div></header>{notice&&<div className="crm-notice" onClick={()=>setNotice("")}>{notice}</div>}
 {view==="dashboard"&&<Dashboard counts={counts} total={leads.filter(l=>String(l.status||"").toLowerCase()!=="deleted").length} followups={followups.length} notifications={notifications.length} onNew={()=>setModal("new")} onLeads={()=>setView("leads")} onFollow={()=>setView("followups")} onStage={(s)=>{setStage(s);setView("leads")}} />}
 {view==="leads"&&<section className="crm-page"><div className="crm-heading"><div><span className="crm-kicker">LEADS HUB</span><h1>{isAdmin?"Enquiries":"My Leads"}</h1><p>Manage, assign, follow up and convert enquiries.</p></div><div className="heading-actions"><button onClick={()=>setView("dashboard")}>← Dashboard</button><button className="primary" onClick={()=>setModal("new")}>＋ New Lead</button></div></div><div className="crm-option-tabs">{([['all','All Leads'],['mine','My Leads'],['unassigned','Unassigned'],['metaFailed','Meta Failed'],...(isAdmin?[['bin','Bin']]:[])] as const).map(([k,l])=><button key={k} className={option===k?"active":""} onClick={()=>setOption(k)}>{l}</button>)}</div><div className="crm-filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search customer, phone, destination…"/><select value={stage} onChange={e=>setStage(e.target.value)}><option>All</option>{stages.map(s=><option key={s}>{s}</option>)}</select><select value={source} onChange={e=>setSource(e.target.value)}><option>All</option>{sources.map(s=><option key={s}>{s}</option>)}</select><select value={branch} onChange={e=>setBranch(e.target.value)}><option>All</option>{branches.map(s=><option key={s}>{s}</option>)}</select><button onClick={exportExcel}>⇩ Export</button><button onClick={()=>fileRef.current?.click()}>⇧ Import</button><input ref={fileRef} type="file" accept=".xlsx,.xls,.csv" hidden onChange={e=>e.target.files?.[0]&&importExcel(e.target.files[0])}/></div>{error&&<div className="crm-error">{error}</div>}<div className="crm-panel"><div className="result-line"><b>{filtered.length} leads</b><span>{option} · {stage} · {source} · {branch}</span></div><LeadTable leads={filtered} onOpen={openLead} onDelete={isAdmin?deleteLead:undefined} onTransfer={isAdmin?openTransfer:undefined} onQuote={openQuotation} onWhatsApp={whatsapp}/></div></section>}
 {view==="followups"&&<section className="crm-page"><div className="crm-heading"><div><span className="crm-kicker">FOLLOW-UP CENTER</span><h1>Callbacks & Follow-ups</h1><p>Prioritize leads that need action.</p></div><button onClick={()=>setView("leads")}>Open Leads →</button></div><div className="crm-panel"><LeadTable leads={followups} onOpen={openLead} onDelete={isAdmin?deleteLead:undefined} onTransfer={isAdmin?openTransfer:undefined} onQuote={openQuotation} onWhatsApp={whatsapp}/></div></section>}
 {view==="quotations"&&<section className="crm-page"><div className="crm-heading"><div><span className="crm-kicker">QUOTATIONS</span><h1>Quotation Workspace</h1><p>Start an AI itinerary from any lead.</p></div><button className="primary" onClick={()=>setView("leads")}>Choose Lead →</button></div><div className="crm-panel empty-state"><h2>AI Itinerary & Quotation</h2><p>Select a lead from Leads Hub and continue to the native CRM itinerary builder.</p></div></section>}
 {view==="settings"&&<section className="crm-page"><div className="crm-heading"><div><span className="crm-kicker">SETTINGS</span><h1>CRM Settings</h1><p>Role-aware controls for your sales team.</p></div></div><div className="crm-grid"><div className="crm-panel"><h2>Access</h2><p><b>Role:</b> {session.profile.role}</p><p><b>Salesperson:</b> {session.profile.salesperson||"All team"}</p></div><div className="crm-panel"><h2>Pipeline</h2><div className="tag-list">{stages.map(s=><span className="crm-pill" key={s}>{s} · {counts[s]||0}</span>)}</div></div></div></section>}
 </section>
 {modal&&<Modal modal={modal} selected={selected} form={form} setField={setField} saving={saving} error={error} isAdmin={isAdmin} salespeople={salespeople} onClose={()=>{setModal(null);setError("")}} onCreate={createLead} onUpdate={updateLead} onDelete={deleteLead} onTransfer={transfer} onQuotation={continueQuotation} onWhatsApp={whatsapp}/>} {searchOpen&&<SearchOverlay leads={leads} onClose={()=>setSearchOpen(false)} onOpen={openLead}/>}</main>
}

function Dashboard({counts,total,followups,notifications,onNew,onLeads,onFollow,onStage}:{counts:Record<string,unknown>;total:number;followups:number;notifications:number;onNew:()=>void;onLeads:()=>void;onFollow:()=>void;onStage:(s:string)=>void}){return <section className="crm-page"><div className="crm-welcome"><div><span className="crm-kicker">TODAY'S CONTROL CENTER</span><h1>CRM Dashboard</h1><p>Track enquiries, sales pipeline, callbacks and conversion.</p></div><button className="primary" onClick={onNew}>＋ New Lead</button></div><div className="crm-stats"><div><span>Total Leads</span><b>{total}</b></div><div><span>Follow-ups</span><b>{followups}</b></div><div><span>Alerts</span><b>{notifications}</b></div><div><span>Booked</span><b>{Number(counts.Booked||0)}</b></div></div><div className="crm-grid"><div className="crm-panel"><div className="panel-title"><h2>Pipeline</h2><button onClick={onLeads}>View all →</button></div><div className="pipeline">{stages.map(s=><button key={s} onClick={()=>onStage(s)}><span>{s}</span><b>{Number(counts[s]||0)}</b></button>)}</div></div><div className="crm-panel"><div className="panel-title"><h2>Quick Actions</h2></div><div className="quick-actions"><button onClick={onNew}>＋ Create Lead</button><button onClick={onLeads}>◉ Open Leads</button><button onClick={onFollow}>↻ Follow-ups</button></div></div></div></section>}

function LeadTable({leads,onOpen,onDelete,onTransfer,onQuote,onWhatsApp}:{leads:Lead[];onOpen:(l:Lead)=>void;onDelete?:((id:string|number)=>void);onTransfer?:((l:Lead)=>void);onQuote:(l:Lead)=>void;onWhatsApp:(l:Lead)=>void}){return <div className="crm-table-wrap"><table className="crm-table"><thead><tr><th>Customer</th><th>Destination</th><th>Status</th><th>Value</th><th>Salesperson</th><th>Follow-up</th><th>Actions</th></tr></thead><tbody>{leads.length?leads.map((l,i)=><tr key={String(l.id||i)}><td><button className="link-button" onClick={()=>onOpen(l)}>{String(l.name||"Unnamed")}</button><small>{String(l.phone||"")}</small></td><td>{String(l.dest||l.destination||"—")}</td><td><span className="crm-pill">{String(l.status||"New")}</span></td><td>₹{String(l.value||"0")}</td><td>{String(l.salesperson||"Unassigned")}</td><td>{String(l.follow||"—")}</td><td><div className="row-actions"><button onClick={()=>onWhatsApp(l)}>WA</button><button onClick={()=>onQuote(l)}>Quote</button>{onTransfer&&<button onClick={()=>onTransfer(l)}>Assign</button>}{onDelete&&<button onClick={()=>onDelete(l.id!)}>Bin</button>}</div></td></tr>):<tr><td colSpan={7} className="empty-cell">No leads found.</td></tr>}</tbody></table></div>}

function Modal({modal,selected,form,setField,saving,error,isAdmin,salespeople,onClose,onCreate,onUpdate,onDelete,onTransfer,onQuotation,onWhatsApp}:{modal:"new"|"detail"|"transfer"|"quotation";selected:Lead|null;form:Record<string,string>;setField:(k:string,v:string)=>void;saving:boolean;error:string;isAdmin:boolean;salespeople:{salesperson:string;email?:string}[];onClose:()=>void;onCreate:(e:React.FormEvent)=>void;onUpdate:(patch:Record<string,unknown>)=>void;onDelete:(id:string|number)=>void;onTransfer:()=>void;onQuotation:()=>void;onWhatsApp:(l:Lead)=>void}){if(modal==="new")return <div className="crm-modal-bg" onMouseDown={onClose}><div className="crm-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><span className="crm-kicker">NEW ENQUIRY</span><h2>Create Lead</h2></div><button onClick={onClose}>×</button></div>{error&&<div className="crm-error">{error}</div>}<form className="form-grid" onSubmit={onCreate}>{[["name","Customer Name"],["phone","Phone"],["email","Email"],["dest","Destination"],["value","Package Value"],["date","Travel Date"],["trav","Travellers"],["follow","Follow-up Date"]].map(([k,l])=><label key={k}>{l}<input type={k==="date"||k==="follow"?"date":"text"} value={form[k]} onChange={e=>setField(k,e.target.value)} required={k==="name"||k==="phone"}/></label>)}<label>Branch<select value={form.branch} onChange={e=>setField("branch",e.target.value)}>{branches.map(b=><option key={b}>{b}</option>)}</select></label><label>Source<select value={form.source} onChange={e=>setField("source",e.target.value)}>{sources.map(s=><option key={s}>{s}</option>)}</select></label><label>Priority<select value={form.priority} onChange={e=>setField("priority",e.target.value)}><option>Normal</option><option>High</option><option>Urgent</option></select></label><label>Status<select value={form.status} onChange={e=>setField("status",e.target.value)}>{stages.map(s=><option key={s}>{s}</option>)}</select></label><label className="full">Notes<textarea value={form.notes} onChange={e=>setField("notes",e.target.value)}/></label><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={saving}>{saving?"Saving…":"Create Lead"}</button></div></form></div></div>;
 if(!selected)return null;
 if(modal==="detail")return <div className="crm-modal-bg" onMouseDown={onClose}><div className="crm-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><span className="crm-kicker">LEAD DETAILS</span><h2>{String(selected.name||"Lead")}</h2></div><button onClick={onClose}>×</button></div>{error&&<div className="crm-error">{error}</div>}<div className="detail-grid"><div><span>Phone</span><b>{String(selected.phone||"—")}</b></div><div><span>Email</span><b>{String(selected.email||"—")}</b></div><div><span>Destination</span><b>{String(selected.dest||selected.destination||"—")}</b></div><div><span>Value</span><b>₹{String(selected.value||"0")}</b></div><div><span>Salesperson</span><b>{String(selected.salesperson||"Unassigned")}</b></div><div><span>Branch</span><b>{String(selected.branch||"—")}</b></div></div><label>Status<select value={String(selected.status||"New")} onChange={e=>onUpdate({status:e.target.value})}>{stages.map(s=><option key={s}>{s}</option>)}</select></label><label>Follow-up<input type="date" value={String(selected.follow||"")} onChange={e=>onUpdate({follow_up:e.target.value})}/></label><label>Notes<textarea defaultValue={String(selected.notes||"")} onBlur={e=>onUpdate({notes:e.target.value})}/></label><div className="modal-actions"><button onClick={()=>onWhatsApp(selected)}>WhatsApp</button><button onClick={onQuotation}>AI Quotation</button>{isAdmin&&<button onClick={()=>onDelete(selected.id!)}>Move to Bin</button>}<button onClick={onClose}>Close</button></div></div></div>;
 if(modal==="transfer")return <div className="crm-modal-bg" onMouseDown={onClose}><div className="crm-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><span className="crm-kicker">ASSIGN LEAD</span><h2>{String(selected.name||"Lead")}</h2></div><button onClick={onClose}>×</button></div>{error&&<div className="crm-error">{error}</div>}<label>Salesperson<select id="crm-transfer-owner" defaultValue={String(selected.salesperson||"")}><option value="">Select salesperson</option>{salespeople.map(s=><option key={s.salesperson} value={s.salesperson}>{s.salesperson}</option>)}</select></label><div className="modal-actions"><button onClick={onClose}>Cancel</button><button className="primary" onClick={onTransfer} disabled={saving}>{saving?"Assigning…":"Assign Lead"}</button></div></div></div>;
 return <div className="crm-modal-bg" onMouseDown={onClose}><div className="crm-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><span className="crm-kicker">QUOTATION</span><h2>Build with AI Itinerary</h2></div><button onClick={onClose}>×</button></div><p>Continue this lead into the native On A Trip itinerary builder.</p><div className="detail-grid"><div><span>Customer</span><b>{String(selected.name||"—")}</b></div><div><span>Destination</span><b>{String(selected.dest||selected.destination||"—")}</b></div><div><span>Travellers</span><b>{String(selected.trav||"—")}</b></div><div><span>Travel date</span><b>{String(selected.date||"—")}</b></div></div><div className="modal-actions"><button onClick={onClose}>Cancel</button><button className="primary" onClick={onQuotation}>Open AI Itinerary →</button></div></div></div>}

function SearchOverlay({leads,onClose,onOpen}:{leads:Lead[];onClose:()=>void;onOpen:(l:Lead)=>void}){const [q,setQ]=useState("");const results=useMemo(()=>leads.filter(l=>[l.name,l.phone,l.email,l.dest,l.destination,l.salesperson].join(" ").toLowerCase().includes(q.toLowerCase())).slice(0,30),[leads,q]);return <div className="crm-modal-bg" onMouseDown={onClose}><div className="crm-modal search-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><h2>Search CRM</h2><button onClick={onClose}>×</button></div><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Customer, phone, email, destination…"/><div className="search-results">{results.map((l,i)=><button key={String(l.id||i)} onClick={()=>{onOpen(l);onClose()}}><b>{String(l.name||"Unnamed")}</b><span>{String(l.phone||"")} · {String(l.dest||l.destination||"")}</span></button>)}</div></div></div>}
