"use client";
import {useMemo,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import * as XLSX from "xlsx";
import type {CrmSession} from "@/lib/crm-auth";

type Lead=Record<string,unknown>&{id?:string|number;name?:string;phone?:string;email?:string;dest?:string;destination?:string;status?:string;salesperson?:string;source?:string;branch?:string;priority?:string;value?:string|number;notes?:string;created_at?:string};
const stages=["New","Contacted","Qualified","Hot","Quote Sent","Follow-up","Booked","Lost"];
const sources=["Website","Meta Ads","Instagram","Facebook","WhatsApp","Google","Walk-in"];
const branches=["Hyderabad","Vijayawada"];

export default function CrmWorkspace({session,initialLeads}:{session:CrmSession;initialLeads:Lead[]}){
 const router=useRouter(); const [leads,setLeads]=useState(initialLeads); const [view,setView]=useState<"dashboard"|"leads">("dashboard");
 const [q,setQ]=useState(""); const [stage,setStage]=useState("All"); const [source,setSource]=useState("All"); const [branch,setBranch]=useState("All");
 const [modal,setModal]=useState<"new"|"detail"|"transfer"|"import"|null>(null); const [selected,setSelected]=useState<Lead|null>(null); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
 const [form,setForm]=useState<Record<string,string>>({name:"",phone:"",email:"",dest:"",value:"",branch:"Hyderabad",source:"Website",priority:"Normal",notes:"",status:"New"});
 const fileRef=useRef<HTMLInputElement>(null);
 const isAdmin=session.profile.role==="admin";
 const accessible=useMemo(()=>leads.filter(l=>String(l.status||"").toLowerCase()!=="deleted"),[leads]);
 const filtered=useMemo(()=>accessible.filter(l=>{const hay=[l.name,l.phone,l.email,l.dest,l.destination,l.salesperson,l.source,l.status,l.branch].join(" ").toLowerCase();return hay.includes(q.toLowerCase())&&(stage==="All"||String(l.status||"New")===stage)&&(source==="All"||String(l.source||"")===source)&&(branch==="All"||String(l.branch||"")===branch)}),[accessible,q,stage,source,branch]);
 const counts=useMemo(()=>Object.fromEntries(stages.map(s=>[s,accessible.filter(l=>String(l.status||"New")===s).length])),[accessible]);
 const setField=(k:string,v:string)=>setForm(x=>({...x,[k]:v}));
 async function refresh(){const r=await fetch("/crm?refresh=1",{cache:"no-store"}); if(r.ok)router.refresh();}
 async function logout(){await fetch("/api/crm/logout",{method:"POST"});router.push("/crm/login");router.refresh();}
 async function createLead(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");try{const r=await fetch("/api/crm/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d?.message||d?.error||"Could not create lead");setModal(null);setForm({name:"",phone:"",email:"",dest:"",value:"",branch:"Hyderabad",source:"Website",priority:"Normal",notes:"",status:"New"});router.refresh();}catch(e){setError(e instanceof Error?e.message:"Could not create lead");}finally{setSaving(false)}}
 async function updateLead(patch:Record<string,unknown>){if(!selected?.id)return;setSaving(true);setError("");try{const r=await fetch("/api/crm/leads",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:selected.id,...patch})});if(!r.ok)throw new Error("Update failed");setLeads(ls=>ls.map(x=>String(x.id)===String(selected.id)?{...x,...patch}:x));setSelected(x=>x?{...x,...patch}:x); }catch(e){setError(e instanceof Error?e.message:"Update failed");}finally{setSaving(false)}}
 async function deleteLead(id:string|number){if(!confirm("Delete this lead?"))return;const r=await fetch("/api/crm/leads",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});if(r.ok){setLeads(ls=>ls.filter(x=>String(x.id)!==String(id)));setModal(null)}}
 function exportExcel(){const rows=filtered.map(l=>({Name:l.name||"",Phone:l.phone||"",Email:l.email||"",Destination:l.dest||l.destination||"",Value:l.value||"",Branch:l.branch||"",Source:l.source||"",Priority:l.priority||"",Status:l.status||"",Salesperson:l.salesperson||"",Notes:l.notes||"",Created:l.created_at||""}));const ws=XLSX.utils.json_to_sheet(rows);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Leads");XLSX.writeFile(wb,`on-a-trip-crm-${new Date().toISOString().slice(0,10)}.xlsx`)}
 function importExcel(file:File){const reader=new FileReader();reader.onload=e=>{const wb=XLSX.read(e.target?.result,{type:"array"});const rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(wb.Sheets[wb.SheetNames[0]]);setError(`${rows.length} rows read. Import API integration is ready for the next batch.`);};reader.readAsArrayBuffer(file)}
 function openLead(l:Lead){setSelected(l);setError("");setModal("detail")}
 return <main className="crm-shell">
  <aside className="crm-sidebar"><div className="crm-brand"><div className="crm-mark">OAT</div><div><b>ON A TRIP</b><span>HOLIDAYS CRM</span></div></div><nav><button className={view==="dashboard"?"active":""} onClick={()=>setView("dashboard")}>⌂ <span>Dashboard</span></button><button className={view==="leads"?"active":""} onClick={()=>setView("leads")}>◉ <span>Leads</span></button><button onClick={()=>setView("leads")}>↗ <span>Follow-ups</span></button><button onClick={()=>setView("leads")}>▣ <span>Quotations</span></button><button onClick={()=>setView("leads")}>⚙ <span>CRM Settings</span></button></nav><div className="crm-user"><b>{session.profile.salesperson||session.user.email||"Admin"}</b><span>{isAdmin?"Administrator":"Salesperson"}</span><button onClick={logout}>Logout</button></div></aside>
  <section className="crm-content"><header className="crm-top"><div><span className="crm-kicker">ON A TRIP HOLIDAYS</span><strong>{isAdmin?"CRM Control Center":"Sales CRM"}</strong></div><div className="crm-top-actions"><button onClick={()=>setView("leads")}>⌕ Search CRM</button><button>🔔</button><button onClick={()=>router.push("/")}>Website ↗</button></div></header>
   {view==="dashboard"?<section className="crm-page"><div className="crm-welcome"><div><span>CRM WORKSPACE</span><h1>Welcome, {session.profile.salesperson||"Admin"}</h1><p>Manage enquiries, sales ownership, follow-ups and quotations from one place.</p></div><button onClick={()=>setModal("new")}>＋ New Lead</button></div><div className="crm-stats"><div><strong>{accessible.length}</strong><span>Total Leads</span></div>{stages.slice(0,3).map(s=><button key={s} onClick={()=>{setStage(s);setView("leads")}}><strong>{counts[s]}</strong><span>{s}</span></button>)}<button onClick={()=>{setStage("Booked");setView("leads")}}><strong>{counts.Booked}</strong><span>Booked</span></button></div><div className="crm-grid"><div className="crm-panel"><div className="panel-head"><div><span>SALES PIPELINE</span><h2>Lead stages</h2></div><button onClick={()=>setView("leads")}>View all</button></div><div className="pipeline">{stages.map(s=><button key={s} onClick={()=>{setStage(s);setView("leads")}}><b>{counts[s]}</b><span>{s}</span></button>)}</div></div><div className="crm-panel"><div className="panel-head"><div><span>QUICK ACTIONS</span><h2>Work faster</h2></div></div><div className="quick-actions"><button onClick={()=>setModal("new")}>＋ Create new lead</button><button onClick={exportExcel}>⇩ Export Excel</button><button onClick={()=>fileRef.current?.click()}>⇧ Import Excel</button><button onClick={()=>setView("leads")}>◉ Open leads hub</button></div><input ref={fileRef} type="file" accept=".xlsx,.xls,.csv" hidden onChange={e=>e.target.files?.[0]&&importExcel(e.target.files[0])}/></div></div><div className="crm-panel"><div className="panel-head"><div><span>RECENT ENQUIRIES</span><h2>Latest leads</h2></div><button onClick={()=>setView("leads")}>Manage leads →</button></div><LeadTable leads={accessible.slice(0,8)} onOpen={openLead}/></div></section>:
   <section className="crm-page"><div className="crm-heading"><div><span className="crm-kicker">LEADS HUB</span><h1>{isAdmin?"All Real Enquiries":"My Leads"}</h1><p>{isAdmin?"Admin access to the complete enquiry pipeline.":`Only leads assigned to ${session.profile.salesperson||"your salesperson profile"} are shown.`}</p></div><div className="heading-actions"><button onClick={()=>setView("dashboard")}>← Dashboard</button><button className="primary" onClick={()=>setModal("new")}>＋ New Lead</button></div></div><div className="crm-filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search leads, customer, phone, destination…"/><select value={stage} onChange={e=>setStage(e.target.value)}><option>All</option>{stages.map(s=><option key={s}>{s}</option>)}</select><select value={source} onChange={e=>setSource(e.target.value)}><option>All</option>{sources.map(s=><option key={s}>{s}</option>)}</select><select value={branch} onChange={e=>setBranch(e.target.value)}><option>All</option>{branches.map(s=><option key={s}>{s}</option>)}</select><button onClick={exportExcel}>Export</button><button onClick={()=>fileRef.current?.click()}>Import</button><input ref={fileRef} type="file" accept=".xlsx,.xls,.csv" hidden onChange={e=>e.target.files?.[0]&&importExcel(e.target.files[0])}/></div><div className="crm-panel"><div className="result-line"><b>{filtered.length} leads</b><span>{stage!=="All"?stage:"All stages"} · {source!=="All"?source:"All sources"}</span></div><LeadTable leads={filtered} onOpen={openLead} onDelete={isAdmin?deleteLead:undefined}/></div></section>}
  </section>
  {modal==="new"&&<div className="crm-modal-bg"><form className="crm-modal" onSubmit={createLead}><div className="modal-head"><div><span>NEW LEAD</span><h2>Create enquiry</h2></div><button type="button" onClick={()=>setModal(null)}>×</button></div><div className="form-grid">{[["name","Customer name"],["phone","Phone"],["email","Email"],["dest","Destination"],["value","Budget / value"]].map(([k,l])=><label key={k}>{l}<input value={form[k]} onChange={e=>setField(k,e.target.value)} required={k==="name"||k==="phone"}/></label>)}<label>Branch<select value={form.branch} onChange={e=>setField("branch",e.target.value)}>{branches.map(x=><option key={x}>{x}</option>)}</select></label><label>Source<select value={form.source} onChange={e=>setField("source",e.target.value)}>{sources.map(x=><option key={x}>{x}</option>)}</select></label><label>Priority<select value={form.priority} onChange={e=>setField("priority",e.target.value)}><option>Normal</option><option>High</option><option>Hot</option></select></label><label className="full">Notes<textarea value={form.notes} onChange={e=>setField("notes",e.target.value)} rows={4}/></label></div>{error&&<p className="crm-error">{error}</p>}<div className="modal-actions"><button type="button" onClick={()=>setModal(null)}>Cancel</button><button className="primary" disabled={saving}>{saving?"Creating…":"Create Lead"}</button></div></form></div>}
  {modal==="detail"&&selected&&<div className="crm-modal-bg"><div className="crm-modal"><div className="modal-head"><div><span>LEAD DETAILS</span><h2>{selected.name||"Lead"}</h2><p>{selected.phone||""} {selected.email?` · ${selected.email}`:""}</p></div><button onClick={()=>setModal(null)}>×</button></div><div className="detail-grid"><div><span>Destination</span><b>{selected.dest||selected.destination||"—"}</b></div><div><span>Budget</span><b>{String(selected.value||"—")}</b></div><div><span>Branch</span><b>{String(selected.branch||"—")}</b></div><div><span>Source</span><b>{String(selected.source||"—")}</b></div><div><span>Owner</span><b>{String(selected.salesperson||"Unassigned")}</b></div><div><span>Priority</span><b>{String(selected.priority||"Normal")}</b></div></div><label className="status-editor">Status<select value={String(selected.status||"New")} onChange={e=>updateLead({status:e.target.value})}>{stages.map(s=><option key={s}>{s}</option>)}</select></label><div className="detail-notes"><span>Notes</span><p>{String(selected.notes||"No notes")}</p></div>{error&&<p className="crm-error">{error}</p>}<div className="modal-actions"><a className="whatsapp" href={selected.phone?`https://wa.me/${String(selected.phone).replace(/\D/g,"")}`:"#"} target="_blank">WhatsApp</a><a href={selected.phone?`tel:${selected.phone}`:"#"}>Call</a>{isAdmin&&<button className="danger" onClick={()=>deleteLead(selected.id!)}>Delete</button>}<button onClick={()=>setModal(null)}>Close</button></div></div></div>}
 </main>
}

function LeadTable({leads,onOpen,onDelete}:{leads:Lead[];onOpen:(l:Lead)=>void;onDelete?:(id:string|number)=>void}){return <div className="crm-table-wrap"><table><thead><tr><th>Customer</th><th>Phone</th><th>Destination</th><th>Status</th><th>Owner</th><th>Source</th><th>Actions</th></tr></thead><tbody>{leads.map((l,i)=><tr key={String(l.id??i)}><td><button className="link-btn" onClick={()=>onOpen(l)}><b>{String(l.name||"Unknown")}</b><small>{String(l.email||"")}</small></button></td><td>{String(l.phone||"—")}</td><td>{String(l.dest||l.destination||"—")}</td><td><span className={`crm-pill ${String(l.status||"New").toLowerCase().replace(/\s/g,"-")}`}>{String(l.status||"New")}</span></td><td>{String(l.salesperson||"Unassigned")}</td><td>{String(l.source||"—")}</td><td>{onDelete&&<button className="mini-danger" onClick={()=>onDelete(l.id!)}>Delete</button>}</td></tr>)}{!leads.length&&<tr><td colSpan={7} className="crm-empty">No matching leads.</td></tr>}</tbody></table></div>}
