"use client";
import {useEffect,useState} from "react";
import type {CrmSession} from "@/lib/crm-auth";

export default function ItineraryBuilderPrefilled({session}:{session:CrmSession}){
 const [f,setF]=useState({guest:"",dest:"",days:"6",pax:"2",start:"",dates:"",language:"English",type:"Custom",hotel:"3 Star",vehicle:"Private Car",meals:"Breakfast & Dinner",budget:"",special:"",instruction:""});
 const [data,setData]=useState<any>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 const set=(k:string,v:string)=>setF(x=>({...x,[k]:v}));
 useEffect(()=>{const p=new URLSearchParams(window.location.search);setF(x=>({...x,guest:p.get("name")||x.guest,dest:p.get("destination")||x.dest,pax:p.get("travellers")||x.pax,dates:p.get("travelDate")||x.dates}));},[]);
 async function generate(e:React.FormEvent){e.preventDefault();setLoading(true);setError("");try{const r=await fetch("/api/ai-itinerary",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(f)});const d=await r.json();if(!r.ok)throw Error(d.error||"Generation failed");setData(d)}catch(e){setError(e instanceof Error?e.message:"Generation failed")}finally{setLoading(false)}}
 return <main className="crm-page"><div className="crm-heading"><div><span className="crm-kicker">AI ITINERARY MAKER</span><h1>Create Customer Itinerary</h1><p>Generate a professional, destination-specific itinerary using the same CRM workspace.</p></div></div><div className="crm-grid"><form className="crm-panel" onSubmit={generate}><div className="form-grid">{[["guest","Guest name"],["dest","Destination"],["days","Days"],["pax","Travellers"],["start","Start city"],["dates","Travel dates"],["budget","Budget / quote"],["special","Special requirements"]].map(([k,l])=><label key={k}>{l}<input value={(f as any)[k]} onChange={e=>set(k,e.target.value)} required={k==="dest"}/></label>)}<label>Language<select value={f.language} onChange={e=>set("language",e.target.value)}><option>English</option><option>Telugu</option><option>Hindi</option></select></label><label>Trip type<select value={f.type} onChange={e=>set("type",e.target.value)}><option>Custom</option><option>Pilgrimage</option><option>Family</option><option>Couple</option><option>Adventure</option><option>Corporate</option></select></label><label>Hotel<input value={f.hotel} onChange={e=>set("hotel",e.target.value)}/></label><label>Vehicle<input value={f.vehicle} onChange={e=>set("vehicle",e.target.value)}/></label><label>Meals<input value={f.meals} onChange={e=>set("meals",e.target.value)}/></label><label className="full">Extra instruction<textarea rows={4} value={f.instruction} onChange={e=>set("instruction",e.target.value)}/></label></div>{error&&<p className="crm-error">{error}</p>}<button className="primary" disabled={loading}>{loading?"Generating…":"✨ Generate with AI"}</button></form>{data?<section className="crm-panel itinerary-preview"><div className="panel-head"><div><span>ON A TRIP HOLIDAYS</span><h2>{data.title}</h2></div><button type="button" onClick={()=>window.print()}>Print / PDF</button></div><p>{data.summary}</p>{data.days.map((d:any)=><article key={d.day}><h3>Day {d.day} — {d.title}</h3><p>{d.summary}</p><small>Hotel: {d.hotel} · Meals: {d.meals}</small></article>)}<h3>Inclusions</h3><ul>{data.inclusions?.map((x:string)=><li key={x}>{x}</li>)}</ul><h3>Exclusions</h3><ul>{data.exclusions?.map((x:string)=><li key={x}>{x}</li>)}</ul><p><b>Vehicle:</b> {data.vehicle} · <b>Hotels:</b> {data.hotels} · <b>Price:</b> {data.price}</p><p>{data.notes}</p></section>:<section className="crm-panel"><h2>Itinerary preview</h2><p>Fill the destination and trip details, then generate the customer-ready itinerary.</p></section>}</div></main>;
}