"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import type {CrmSession} from "@/lib/crm-auth";

type Package={id:string;slug:string;name:string;category:string;duration:string;route:string;from_location:string;price:string;description:string;image:string;highlights:string[];meals?:string;batch?:string;itinerary?:any[];inclusions?:string[];exclusions?:string[]};
export default function ItinerarySourcePicker({session}:{session:CrmSession}){
 const router=useRouter();const [mode,setMode]=useState<"choose"|"ai"|"package">("choose");const [items,setItems]=useState<Package[]>([]);const [q,setQ]=useState("");const [loading,setLoading]=useState(false);
 useEffect(()=>{if(mode!=="package")return;setLoading(true);fetch("/api/crm/packages").then(r=>r.json()).then(d=>setItems(Array.isArray(d)?d:[])).finally(()=>setLoading(false))},[mode]);
 if(mode==="ai")return <div><button className="source-back" onClick={()=>setMode("choose")}>← Choose another source</button><div className="source-embed"><ItineraryBuilderPrefilled session={session}/></div></div>;
 if(mode==="package")return <main className="crm-page itinerary-builder"><div className="crm-heading"><div><span className="crm-kicker">STEP 1 · WEBSITE PACKAGES</span><h1>Build Itinerary from Our Packages</h1><p>Pick an existing On A Trip Holidays package and carry it directly into the quotation.</p></div><div className="heading-actions"><button onClick={()=>setMode("choose")}>← Back</button></div></div><section className="crm-panel package-picker-panel"><div className="package-picker-tools"><input placeholder="Search website packages…" value={q} onChange={e=>setQ(e.target.value)}/><span>{items.filter(p=>`${p.name} ${p.category} ${p.route}`.toLowerCase().includes(q.toLowerCase())).length} packages</span></div>{loading?<p>Loading website packages…</p>:<div className="package-picker-grid">{items.filter(p=>`${p.name} ${p.category} ${p.route}`.toLowerCase().includes(q.toLowerCase())).map(p=><article className="package-picker-card" key={p.id}><div className="package-picker-image" style={{backgroundImage:p.image?`url(${p.image})`:undefined}}/><div className="package-picker-body"><span>{p.category}</span><h2>{p.name}</h2><p>{p.duration} · {p.from_location}</p><small>{p.route}</small><strong>{p.price}</strong><button className="primary" onClick={()=>{localStorage.setItem("oat_selected_package",JSON.stringify(p));router.push(`/crm/quotation?package=${encodeURIComponent(p.slug)}`)}}>Use Package → Next to Quotation</button></div></article>)}</div>}</section></main>;
 return <main className="crm-page itinerary-source"><div className="crm-heading"><div><span className="crm-kicker">STEP 1 · ITINERARY STUDIO</span><h1>How do you want to create the itinerary?</h1><p>Choose AI for a new custom plan, or use one of our published website packages.</p></div></div><div className="source-choice-grid"><button className="source-choice" onClick={()=>setMode("ai")}><span>✨</span><b>Generate Itinerary with AI</b><small>Create a fresh itinerary from destination, dates, travellers and your instructions.</small></button><button className="source-choice" onClick={()=>setMode("package")}><span>📦</span><b>Generate from Website Package</b><small>Start from an existing On A Trip Holidays package and its published details.</small></button><button className="source-choice" onClick={()=>router.push("/crm/quotation")}><span>🧾</span><b>Package Picker → Make Quotation</b><small>Pick a website package directly and go straight to quotation.</small></button></div></main>;
}
import ItineraryBuilderPrefilled from "./ItineraryBuilderPrefilled";
