"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import type {CrmSession} from "@/lib/crm-auth";

type P={id:string;slug:string;name:string;category:string;duration:string;route:string;from_location:string;price:string;description:string;meals?:string;batch?:string;itinerary?:any[];inclusions?:string[];exclusions?:string[]};
type F={guest:string;dest:string;days:string;pax:string;start:string;dates:string;language:string;type:string;hotel:string;vehicle:string;meals:string;budget:string;special:string;instruction:string};
const blank:F={guest:"",dest:"",days:"6",pax:"2",start:"",dates:"",language:"English",type:"Custom",hotel:"3 Star",vehicle:"Private Car",meals:"Breakfast & Dinner",budget:"",special:"",instruction:""};
const days=(s:string)=>s.match(/(\d+)\s*(?:Days|Day)/i)?.[1]||"";
const price=(s:string)=>{const n=s?.replace(/[^0-9.]/g,"");return n?String(Math.round(Number(n))):""};
export default function ItineraryBuilderV2({session}:{session:CrmSession}){
 const router=useRouter();const [f,setF]=useState<F>(blank);const [data,setData]=useState<any>(null);const [packages,setPackages]=useState<P[]>([]);const [open,setOpen]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{const q=new URLSearchParams(location.search);setF(x=>({...x,guest:q.get("name")||x.guest,dest:q.get("destination")||x.dest,pax:q.get("travellers")||x.pax,dates:q.get("travelDate")||x.dates}))},[]);
 const set=(k:keyof F,v:string)=>setF(x=>({...x,[k]:v}));
 async function ai(){setLoading(true);setError("");try{const r=await fetch("/api/ai-itinerary",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(f)});const d=await r.json();if(!r.ok)throw Error(d.error||"AI generation failed");setData(d)}catch(e){setError(e instanceof Error?e.message:"AI generation failed")}finally{setLoading(false)}}
 async function openPicker(){setOpen(true);setError("");if(packages.length)return;setLoading(true);try{const r=await fetch("/api/crm/packages",{cache:"no-store"});const d=await r.json();if(!r.ok)throw Error(d.error||"Could not load packages");setPackages(Array.isArray(d)?d:[])}catch(e){setError(e instanceof Error?e.message:"Could not load packages")}finally{setLoading(false)}}
 function pick(p:P){const dd=days(p.duration);const next={...f,dest:p.name,days:dd||f.days,start:p.from_location||f.start,budget:price(p.price)||f.budget,meals:p.meals||f.meals,type:p.category==="Pilgrimage"?"Pilgrimage":f.type};setF(next);setOpen(false);setData({title:p.name,summary:p.description||p.route,days:Array.isArray(p.itinerary)?p.itinerary:[],hotels:"As per website package",vehicle:next.vehicle,meals:p.meals||next.meals,price:p.price,inclusions:p.inclusions||[],exclusions:p.exclusions||[],notes:`Website package: ${p.name}${p.batch?` · Batch: ${p.batch}`:""}${p.route?` · ${p.route}`:""}`})}
 function goQuote(){if(!data)return;localStorage.setItem("oat_itinerary_draft",JSON.stringify({form:f,data,updatedAt:new Date().toISOString()}));router.push(`/crm/quotations?name=${encodeURIComponent(f.guest)}&dest=${encodeURIComponent(f.dest)}&pax=${f.pax}&days=${f.days}&dates=${encodeURIComponent(f.dates)}&start=${encodeURIComponent(f.start)}&vehicle=${encodeURIComponent(f.vehicle)}&hotel=${encodeURIComponent(f.hotel)}&meals=${encodeURIComponent(f.meals)}&packagePrice=${encodeURIComponent(f.budget)}`)}
 return <main className="crm-page itinerary-builder"><div className="crm-heading"><div><span className="crm-kicker">STEP 1 · ITINERARY STUDIO</span><h1>Create Customer Itinerary</h1><p>Choose AI for a custom itinerary or pick an official website package, then continue to quotation.</p></div><div className="heading-actions"><button type="button" className="primary" onClick={ai}>✨ Generate Itinerary with AI</button><button type="button" onClick={openPicker}>📦 Pick Website Package</button>{data&&<button type="button" onClick={goQuote}>Next → Make Quotation</button>}</div></div>
 {open&&<div className="admin-modal-backdrop"><section className="admin-modal" style={{maxWidth:900}}><div className="modal-head"><div><span className="crm-kicker">ON A TRIP HOLIDAYS WEBSITE PACKAGES</span><h2>Pick a website package</h2><p>Select an official published package. Its itinerary, route and commercial details will be loaded into Step 1.</p></div><button type="button" onClick={()=>setOpen(false)}>×</button></div>{loading?<div className="admin-panel">Loading packages…</div>:packages.length===0?<div className="admin-panel">No published website packages found.</div>:<div style={{display:"grid",gap:12,maxHeight:"65vh",overflowY:"auto"}}>{packages.map(p=><button type="button" key={p.id||p.slug} onClick={()=>pick(p)} style={{textAlign:"left",padding:16,border:"1px solid #ddd",borderRadius:12,background:"white",cursor:"pointer"}}><b style={{fontSize:17}}>{p.name}</b><div style={{marginTop:5,color:"#555"}}>{p.category} · {p.duration} · {p.from_location||"Start TBC"}</div><div style={{marginTop:5,fontWeight:700}}>{p.price||"Get Quote"}{p.batch?` · ${p.batch}`:""}</div><div style={{marginTop:6,color:"#666"}}>{p.route||p.description}</div></button>)}</div>}{error&&<p className="crm-error">{error}</p>}<div className="modal-actions"><button type="button" onClick={()=>setOpen(false)}>Close</button></div></section></div>}
 <div className="crm-grid"><section className="crm-panel"><div className="panel-head"><div><span>AI</span><h2>Custom AI Itinerary</h2></div></div><div className="form-grid"><label>Guest name<input value={f.guest} onChange={e=>set("guest",e.target.value)}/></label><label>Destination<input required value={f.dest} onChange={e=>set("dest",e.target.value)}/></label><label>Travellers<input type="number" min="1" value={f.pax} onChange={e=>set("pax",e.target.value)}/></label><label>Days<input type="number" min="1" max="30" value={f.days} onChange={e=>set("days",e.target.value)}/></label><label>Start city<input value={f.start} onChange={e=>set("start",e.target.value)}/></label><label>Travel date / dates<input value={f.dates} onChange={e=>set("dates",e.target.value)}/></label><label>Hotel<input value={f.hotel} onChange={e=>set("hotel",e.target.value)}/></label><label>Vehicle<input value={f.vehicle} onChange={e=>set("vehicle",e.target.value)}/></label><label>Meals<input value={f.meals} onChange={e=>set("meals",e.target.value)}/></label><label>Language<input value={f.language} onChange={e=>set("language",e.target.value)}/></label><label className="full">Special requirements<textarea rows={3} value={f.special} onChange={e=>set("special",e.target.value)}/></label><label className="full">AI instructions<textarea rows={3} value={f.instruction} onChange={e=>set("instruction",e.target.value)}/></label></div><button type="button" className="primary" onClick={ai} disabled={loading}>{loading?"Generating…":"✨ Generate Itinerary with AI"}</button>{error&&<p className="crm-error">{error}</p>}</section>
 <section className="crm-panel itinerary-preview">{data?<><div className="print-cover"><span>ON A TRIP HOLIDAYS</span><h2>{data.title}</h2><p>{data.summary}</p><div className="cover-meta"><b>{f.guest||"Valued Guest"}</b><span>{f.days} Days · {f.pax} Travellers</span><span>{f.dates||"Dates TBC"}</span></div></div>{(data.days||[]).map((d:any,i:number)=><article className="itinerary-day" key={i}><div className="day-number">{d.day||i+1}</div><div className="day-content"><h3>{d.title||`Day ${i+1}`}</h3><p>{d.summary||d.description||""}</p><small>🏨 {d.hotel||f.hotel} · 🍽 {d.meals||f.meals}</small></div></article>)}<div className="itinerary-footer"><b>Vehicle:</b> {f.vehicle} · <b>Price:</b> {data.price||f.budget||"On request"}</div><button type="button" className="primary" onClick={goQuote}>Next → Make Quotation</button></>:<div className="itinerary-empty"><h2>Choose an itinerary source</h2><p>Use AI for a custom plan or pick an official website package. Both routes lead to the same quotation workflow.</p><div className="modal-actions"><button type="button" className="primary" onClick={ai}>✨ Use AI</button><button type="button" onClick={openPicker}>📦 Pick Website Package</button></div></div>}</section></div></main>;
}
