import type {ReactNode} from "react";
import SiteShell from "@/components/SiteShell";

type Section={title:string;children:ReactNode};
export default function PolicyPage({kicker,title,intro,updated,sections}:{kicker:string;title:string;intro:string;updated:string;sections:Section[]}){
 return <SiteShell><main className="policy-page">
  <style>{`.policy-page{background:#f7f4ef;padding-bottom:80px}.policy-hero{background:linear-gradient(135deg,#082542,#123f68);color:#fff;padding:72px 0 68px}.policy-wrap{width:min(1000px,calc(100% - 36px));margin:auto}.policy-kicker{color:#ffd074;font-size:11px;font-weight:900;letter-spacing:2px;text-transform:uppercase}.policy-hero h1{font-family:Georgia,'Times New Roman',serif;font-size:clamp(40px,6vw,68px);line-height:1.02;letter-spacing:-2px;margin:12px 0 16px}.policy-hero p{max-width:760px;color:#dce7ed;line-height:1.7;font-size:16px;margin:0}.policy-updated{margin-top:22px;font-size:11px;color:#b9cbd5;font-weight:700}.policy-card{background:#fff;border:1px solid #dfe6ea;border-radius:22px;box-shadow:0 18px 50px rgba(8,37,66,.09);padding:clamp(24px,5vw,48px);margin-top:-32px;position:relative}.policy-section{padding:0 0 28px;margin:0 0 28px;border-bottom:1px solid #e7ecef}.policy-section:last-child{border-bottom:0;margin-bottom:0;padding-bottom:0}.policy-section h2{font-family:Georgia,'Times New Roman',serif;color:#082542;font-size:24px;margin:0 0 12px}.policy-section p,.policy-section li{color:#53687a;font-size:14px;line-height:1.75}.policy-section p{margin:0 0 10px}.policy-section ul{margin:8px 0 0;padding-left:22px}.policy-contact{margin-top:28px;background:#fff7f2;border-left:4px solid #ef5b2a;padding:18px 20px;border-radius:0 12px 12px 0}.policy-contact strong{color:#082542}.policy-nav{display:flex;flex-wrap:wrap;gap:9px;margin-top:22px}.policy-nav a{font-size:11px;font-weight:900;color:#082542;background:#fff;border:1px solid rgba(255,255,255,.2);padding:9px 12px;border-radius:999px}.policy-nav a:hover{background:#fff0e8;color:#ef5b2a}@media(max-width:600px){.policy-hero{padding:52px 0}.policy-card{margin-top:-20px;padding:24px 20px}.policy-section h2{font-size:21px}.policy-section p,.policy-section li{font-size:13px}}`}</style>
  <section className="policy-hero"><div className="policy-wrap"><div className="policy-kicker">{kicker}</div><h1>{title}</h1><p>{intro}</p><div className="policy-updated">Last updated: {updated}</div><div className="policy-nav"><a href="/terms-and-conditions">Booking Terms</a><a href="/privacy-policy">Privacy Policy</a><a href="/cancellation-refund-policy">Cancellation &amp; Refund</a></div></div></section>
  <div className="policy-wrap"><article className="policy-card">{sections.map((section,index)=><section className="policy-section" key={index}><h2>{section.title}</h2>{section.children}</section>)}</article></div>
 </main></SiteShell>
}`}
