export type Category = "Pilgrimage" | "Domestic" | "International";
export type Package = { slug:string; name:string; category:Category; duration:string; route:string; from:string; price:string; description:string; image:string; highlights:string[]; meals?:string; batch?:string };
export const packages:Package[]=[
{slug:"char-dham",name:"Char Dham Yatra",category:"Pilgrimage",duration:"10 Nights / 11 Days",route:"Yamunotri • Gangotri • Kedarnath • Badrinath",from:"Hyderabad / Delhi",price:"₹30,500",description:"A carefully planned Char Dham journey with Telugu-first support, comfortable stays, transport coordination and on-tour assistance.",image:"https://images.unsplash.com/photo-1601821139314-66a4d14cfc00?auto=format&fit=crop&w=1400&q=85",highlights:["Yamunotri & Gangotri","Kedarnath Darshan","Badrinath Darshan","Telugu group support"],meals:"Breakfast & Dinner"},
{slug:"do-dham",name:"Do Dham Yatra",category:"Pilgrimage",duration:"8 Nights / 9 Days",route:"Kedarnath • Badrinath • Tungnath",from:"Dehradun / Delhi",price:"₹22,000",description:"A focused Himalayan pilgrimage covering Kedarnath and Badrinath with a practical pace and dedicated travel coordination.",image:"https://images.unsplash.com/photo-1601821139314-66a4d14cfc00?auto=format&fit=crop&w=1400&q=85",highlights:["Kedarnath","Badrinath","Tungnath","Pilgrimage assistance"],meals:"Breakfast & Dinner"},
{slug:"kedarnath",name:"Kedarnath Yatra",category:"Pilgrimage",duration:"5 Nights / 6 Days",route:"Haridwar • Sonprayag • Kedarnath",from:"Delhi / Haridwar",price:"₹13,499",description:"A straightforward Kedarnath journey with transport planning, stay coordination and assistance for pilgrims.",image:"https://images.unsplash.com/photo-1680531625343-87c96ee30dea?auto=format&fit=crop&w=1400&q=85",highlights:["Sonprayag","Kedarnath trek","Darshan assistance","On-tour support"],meals:"Breakfast & Dinner"},
{slug:"manali",name:"Manali Escape",category:"Domestic",duration:"5 Nights / 6 Days",route:"Delhi • Shimla • Manali • Solang",from:"Delhi",price:"₹8,999",description:"A flexible Himalayan holiday for families, couples and groups, with sightseeing and vehicle options tailored to your travel style.",image:"https://images.unsplash.com/photo-1677820915325-d8ce3184c2a4?auto=format&fit=crop&w=1400&q=85",highlights:["Manali","Solang Valley","Local sightseeing","Flexible vehicle options"],meals:"Breakfast & Dinner",batch:"25 Sep 2026"},
{slug:"kashmir",name:"Kashmir Holiday",category:"Domestic",duration:"5 Nights / 6 Days",route:"Srinagar • Gulmarg • Pahalgam • Sonamarg",from:"Srinagar / Delhi",price:"₹18,999",description:"Explore Kashmir with a balanced route covering valleys, lakes and mountain landscapes with private or group options.",image:"https://images.unsplash.com/photo-1569852837213-00d97a707a83?auto=format&fit=crop&w=1400&q=85",highlights:["Gulmarg","Pahalgam","Sonamarg","Srinagar"],meals:"Breakfast & Dinner",batch:"07 Oct 2026"},
{slug:"ladakh",name:"Ladakh Adventure",category:"Domestic",duration:"6 Nights / 7 Days",route:"Leh • Nubra • Pangong",from:"Leh / Delhi",price:"₹24,999",description:"A high-altitude adventure through Leh, Nubra and Pangong with sensible acclimatization and practical travel guidance.",image:"https://images.unsplash.com/photo-1577500680965-6054e87d944b?auto=format&fit=crop&w=1400&q=85",highlights:["Leh","Nubra Valley","Pangong Lake","Acclimatization"],meals:"Breakfast & Dinner",batch:"01 Oct 2026"},
{slug:"spiti",name:"Spiti Valley Explorer",category:"Domestic",duration:"8 Nights / 9 Days",route:"Delhi • Manali • Kaza • Chitkul",from:"Delhi",price:"₹29,999",description:"A raw Himalayan road trip through Spiti with dramatic landscapes, high passes and carefully planned overnight stops.",image:"https://images.unsplash.com/photo-1638641088375-ddf026f736f4?auto=format&fit=crop&w=1400&q=85",highlights:["Kaza","Chicham","Key Monastery","Chitkul"],meals:"Breakfast & Dinner",batch:"25 Sep 2026"},
{slug:"kerala",name:"Kerala Backwaters & Hills",category:"Domestic",duration:"5 Nights / 6 Days",route:"Kochi • Munnar • Thekkady • Alleppey",from:"Kochi",price:"₹39,500",description:"A relaxed Kerala holiday combining hill country, wildlife and backwaters for couples, families and private groups.",image:"https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1400&q=85",highlights:["Munnar","Thekkady","Alleppey","Private options"],meals:"Breakfast & Dinner"},
{slug:"thailand",name:"Thailand Getaway",category:"International",duration:"5 Nights / 6 Days",route:"Bangkok • Pattaya • Phuket",from:"Hyderabad",price:"₹29,999",description:"A practical Thailand escape with popular city, beach and entertainment experiences, with custom options available.",image:"https://images.unsplash.com/photo-1737516465405-a213dabc832e?auto=format&fit=crop&w=1400&q=85",highlights:["Bangkok","Pattaya","Phuket","Customizable stays"],meals:"Breakfast",batch:"15 Oct 2026"},
{slug:"bali",name:"Bali Escape",category:"International",duration:"5 Nights / 6 Days",route:"Ubud • Kuta • Nusa Dua",from:"Hyderabad",price:"Get Quote",description:"A flexible Bali holiday for couples, families and groups, with hotel and sightseeing choices matched to your budget.",image:"https://images.unsplash.com/photo-1557093793-d149a38a1be8?auto=format&fit=crop&w=1400&q=85",highlights:["Ubud","Kuta","Nusa Dua","Private tours"],meals:"Breakfast"},
{slug:"dubai",name:"Dubai Highlights",category:"International",duration:"4 Nights / 5 Days",route:"Dubai • Desert Safari • City Tour",from:"Hyderabad",price:"Get Quote",description:"See Dubai's signature experiences with flexible hotel categories, transfers and optional activities.",image:"https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1400&q=85",highlights:["City tour","Desert safari","Burj Khalifa","Airport transfers"],meals:"Breakfast"},
{slug:"vietnam",name:"Vietnam Discovery",category:"International",duration:"5 Nights / 6 Days",route:"Hanoi • Ha Long Bay • Da Nang",from:"Hyderabad",price:"Get Quote",description:"A curated Vietnam route with iconic landscapes, local experiences and flexible hotel choices.",image:"https://images.unsplash.com/photo-1669819894338-53ab7afc6958?auto=format&fit=crop&w=1400&q=85",highlights:["Hanoi","Ha Long Bay","Da Nang","Custom itinerary"],meals:"Breakfast"},
{slug:"nepal",name:"Nepal & Muktinath",category:"International",duration:"7 Nights / 8 Days",route:"Kathmandu • Pokhara • Muktinath",from:"Kathmandu / Varanasi",price:"Get Quote",description:"A spiritual and scenic Nepal journey combining Kathmandu, Pokhara and Muktinath with practical travel coordination.",image:"https://images.unsplash.com/photo-1706187975952-33765f844667?auto=format&fit=crop&w=1400&q=85",highlights:["Kathmandu","Pokhara","Muktinath","Flexible transport"],meals:"Breakfast & Dinner"}
];
export const destinationMeta={mountains:{name:"Mountains",description:"Himalayan escapes across Manali, Kashmir, Ladakh and Spiti.",packages:["manali","kashmir","ladakh","spiti"]},temples:{name:"Temples & Yatras",description:"Purpose-built pilgrimage journeys with practical support and clear itineraries.",packages:["char-dham","do-dham","kedarnath"]},kerala:{name:"Kerala",description:"Kerala hills, wildlife and backwaters.",packages:["kerala"]},international:{name:"International",description:"Thailand, Bali, Dubai, Vietnam and Nepal holidays with custom planning.",packages:["thailand","bali","dubai","vietnam","nepal"]}} as const;
export const packageBySlug=(slug:string)=>packages.find(x=>x.slug===slug);
