import type { Metadata } from "next";
import SitePage from "@/components/SitePage";

export const metadata: Metadata = {
  title: "Ladakh Tour Packages from Hyderabad | Leh, Nubra & Pangong",
  description: "Explore Ladakh tour packages from Hyderabad covering Leh, Nubra and Pangong with acclimatisation guidance, route planning and Telugu-friendly support.",
  alternates: { canonical: "/ladakh-tour-packages-from-hyderabad" },
  robots: { index: true, follow: true, "max-image-preview": "large" },
  openGraph: {
    title: "Ladakh Tour Packages from Hyderabad | Leh, Nubra & Pangong",
    description: "Explore Ladakh tour packages from Hyderabad covering Leh, Nubra and Pangong with acclimatisation guidance, route planning and Telugu-friendly support.",
    url: "/ladakh-tour-packages-from-hyderabad",
    siteName: "On A Trip Holidays",
    type: "website",
  },
};

export default function Page() {
  return (
    <SitePage>
      <nav className="nav"><a className="brand" href="/"><img alt="On A Trip Holidays" decoding="async" loading="lazy" src="assets/logo.png" /></a><div className="navlinks"><a href="/packages">Packages</a><a href="/pilgrimage">Pilgrimage</a><a href="/blogs">Blogs</a><a href="/about">About</a><a href="/contact">Contact</a></div><a className="wa" href="https://wa.me/919182894146?text=Hi%20On%20A%20Trip%20Holidays%2C%20I%20want%20a%20Himalayan%20tour%20quote">WhatsApp Us</a></nav>
<main><section className="oat-hero"><div className="eyebrow">ON A TRIP HOLIDAYS • HYDERABAD</div><section className="oat-v15-hero"><div className="oat-v15-hero-inner"><div className="oat-v15-kicker">ON A TRIP HOLIDAYS • HYDERABAD</div><h1>Ladakh Tour Packages from Hyderabad</h1><p>Leh • Nubra • Pangong • High-altitude adventure. Explore a clean, well-planned holiday or pilgrimage journey with practical itinerary guidance, stay and transport options, and Telugu-friendly support.</p><div className="oat-v15-actions"><a className="oat-v15-btn" href="https://wa.me/919182894146?text=Hi%20On%20A%20Trip%20Holidays%2C%20I%20want%20the%20latest%20price%20and%20dates%20for%20Ladakh%20Tour%20Packages%20from%20Hyderabad">Get Latest Price & Dates</a><a className="oat-v15-btn alt" href="#itinerary">View Itinerary</a></div></div></section><section className="oat-v15-facts"><div className="oat-v15-fact"><strong>📍 Departure</strong><span>Hyderabad</span></div><div className="oat-v15-fact"><strong>🗣️ Support</strong><span>Telugu-friendly assistance</span></div><div className="oat-v15-fact"><strong>👨‍👩‍👧 Travel style</strong><span>Group & customised options</span></div><div className="oat-v15-fact"><strong>📲 Enquiry</strong><span>Latest dates & pricing on WhatsApp</span></div></section><div className="oat-v16-trail"><a href="/">Home</a>  ›  <a href="/packages">Tour Packages</a>  ›  Hyderabad Packages</div>
<div className="oat-v16-bar"><div className="oat-v16-bar-inner"><div><strong>Planning from Hyderabad?</strong><div className="oat-v16-mini">Get the latest route, dates, inclusions and price on WhatsApp.</div></div><a href="https://wa.me/919182894146?text=Hi%20On%20A%20Trip%20Holidays%2C%20I%20want%20the%20latest%20package%20details%20from%20Hyderabad.">Get Latest Details →</a></div></div><section className="oat-v15-section"><h2>Destination Highlights</h2><div className="oat-v15-gallery"><figure><img alt="Ladakh Tour Packages from Hyderabad destination travel photograph" decoding="async" loading="lazy" src="https://images.pexels.com/photos/32793602/pexels-photo-32793602.jpeg?auto=compress&amp;cs=tinysrgb&amp;w=1600" /><figcaption>Signature view</figcaption></figure><figure><img alt="Ladakh Tour Packages from Hyderabad destination travel photograph" decoding="async" loading="lazy" src="https://images.pexels.com/photos/7741377/pexels-photo-7741377.jpeg?auto=compress&amp;cs=tinysrgb&amp;w=1600" /><figcaption>Travel highlight</figcaption></figure><figure><img alt="Ladakh Tour Packages from Hyderabad destination travel photograph" decoding="async" loading="lazy" src="https://images.pexels.com/photos/32793599/pexels-photo-32793599.jpeg?auto=compress&amp;cs=tinysrgb&amp;w=1600" /><figcaption>Explore the destination</figcaption></figure></div></section><section className="oat-v15-section"><h2>Plan your trip with clarity</h2><div className="oat-v15-route"><article><b>01 • Choose your dates</b><span>Share preferred dates and group size so we can confirm the latest available option.</span></article><article><b>02 • Get the right itinerary</b><span>Compare route, hotel, transport and sightseeing choices before you book.</span></article><article><b>03 • Enquire directly</b><span>Use WhatsApp for the latest package details and personalised assistance.</span></article></div></section><section className="oat-v15-cta"><h2>Ready to plan your trip from Hyderabad?</h2><p>Send your travel dates and group size. We’ll help you understand the latest itinerary, package inclusions and available options.</p><a className="oat-v15-btn" href="https://wa.me/919182894146?text=Hi%20On%20A%20Trip%20Holidays%2C%20please%20share%20the%20latest%20itinerary%20and%20price">WhatsApp On A Trip Holidays</a></section><p>Discover Ladakh with a carefully paced Himalayan itinerary from Hyderabad. Plan Leh, Nubra Valley and Pangong Lake with accommodation, transfers and sightseeing assistance.</p></section>
<section className="oat-grid"><article className="oat-card"><h2>Leh</h2><p>Build acclimatisation and local sightseeing into your Ladakh route.</p><a href="/packages">Explore Leh →</a></article><article className="oat-card"><h2>Nubra Valley</h2><p>Explore the high-altitude valley and mountain landscapes.</p><a href="/packages">Explore Nubra →</a></article><article className="oat-card"><h2>Pangong Lake</h2><p>Plan a scenic Pangong experience as part of a suitable route.</p><a href="/packages">Explore Pangong →</a></article><article className="oat-card"><h2>Ladakh Group Tours</h2><p>Ask about current seasonal batches and group departure options.</p><a href="/packages">View packages →</a></article></section><section className="oat-cta"><h2>Planning a Himalayan trip from Hyderabad?</h2><p>Send your dates, group size and preferred destinations. We’ll help with itinerary, transport and stay options.</p><a href="https://wa.me/919182894146?text=Hi%20On%20A%20Trip%20Holidays%2C%20I%20want%20a%20Himalayan%20tour%20quote">Get itinerary & price on WhatsApp</a></section>
<section className="oat-faq"><h2>Frequently Asked Questions</h2><details><summary>Can I travel to Ladakh from Hyderabad?</summary><p>Yes. On A Trip Holidays can help plan Ladakh itineraries from Hyderabad, subject to route conditions and seasonal availability.</p></details><details><summary>How many days are suitable for Ladakh?</summary><p>A trip length depends on acclimatisation, permits, route and sightseeing. A well-paced itinerary is more important than simply minimising days.</p></details><details><summary>Can you arrange a customised Ladakh trip?</summary><p>Yes. Share your dates, group size and preferred places for a tailored itinerary.</p></details></section></main><section className="oat-v15-section"><h2>How to plan Ladakh Tour Packages from Hyderabad</h2><div className="oat-v16-steps"><div className="oat-v16-step"><b>1</b><h3>Share your dates</h3><p>Tell us your preferred travel dates, number of travellers and departure city.</p></div><div className="oat-v16-step"><b>2</b><h3>Choose your trip</h3><p>Compare the route, stay plan, transport and inclusions that suit your group.</p></div><div className="oat-v16-step"><b>3</b><h3>Confirm your booking</h3><p>Our team helps with the next booking steps and current trip requirements.</p></div></div><div className="oat-v16-note">Package dates, availability, prices and inclusions can change. Confirm the latest details before booking.</div><div className="oat-v16-cta"><div><h3>Need the latest package details?</h3><p>Message On A Trip Holidays for current dates, pricing and inclusions.</p></div><a href="https://wa.me/919182894146?text=Hi%20On%20A%20Trip%20Holidays%2C%20please%20share%20the%20latest%20package%20details%20from%20Hyderabad.">WhatsApp Us</a></div></section>
    </SitePage>
  );
}
