import type { Metadata } from "next";
import SitePage from "@/components/SitePage";

export const metadata: Metadata = {
  title: "Spiti Valley Tour Packages from Hyderabad | Himachal Adventure",
  description: "Explore Spiti Valley tour packages from Hyderabad with practical route planning, high-altitude travel guidance, stays and Telugu-friendly group or customised options.",
  alternates: { canonical: "/spiti-valley-tour-packages-from-hyderabad" },
  robots: { index: true, follow: true, "max-image-preview": "large" },
  openGraph: {
    title: "Spiti Valley Tour Packages from Hyderabad | Himachal Adventure",
    description: "Explore Spiti Valley tour packages from Hyderabad with practical route planning, high-altitude travel guidance, stays and Telugu-friendly group or customised options.",
    url: "/spiti-valley-tour-packages-from-hyderabad",
    siteName: "On A Trip Holidays",
    type: "website",
  },
};

export default function Page() {
  return (
    <SitePage>
      <nav className="nav"><a className="brand" href="/"><img alt="On A Trip Holidays" decoding="async" loading="lazy" src="assets/logo.png" /></a><div className="navlinks"><a href="/packages">Packages</a><a href="/pilgrimage">Pilgrimage</a><a href="/blogs">Blogs</a><a href="/about">About</a><a href="/contact">Contact</a></div><a className="wa" href="https://wa.me/919182894146?text=Hi%20On%20A%20Trip%20Holidays%2C%20I%20want%20a%20Himalayan%20tour%20quote">WhatsApp Us</a></nav>
<main><section className="oat-hero"><div className="eyebrow">ON A TRIP HOLIDAYS • HYDERABAD</div><section className="oat-v15-hero"><div className="oat-v15-hero-inner"><div className="oat-v15-kicker">ON A TRIP HOLIDAYS • HYDERABAD</div><h1>Spiti Valley Tour Packages from Hyderabad</h1><p>Mountain roads • Monasteries • High-altitude adventure. Explore a clean, well-planned holiday or pilgrimage journey with practical itinerary guidance, stay and transport options, and Telugu-friendly support.</p><div className="oat-v15-actions"><a className="oat-v15-btn" href="https://wa.me/919182894146?text=Hi%20On%20A%20Trip%20Holidays%2C%20I%20want%20the%20latest%20price%20and%20dates%20for%20Spiti%20Valley%20Tour%20Packages%20from%20Hyderabad">Get Latest Price & Dates</a><a className="oat-v15-btn alt" href="#itinerary">View Itinerary</a></div></div></section><section className="oat-v15-facts"><div className="oat-v15-fact"><strong>📍 Departure</strong><span>Hyderabad</span></div><div className="oat-v15-fact"><strong>🗣️ Support</strong><span>Telugu-friendly assistance</span></div><div className="oat-v15-fact"><strong>👨‍👩‍👧 Travel style</strong><span>Group & customised options</span></div><div className="oat-v15-fact"><strong>📲 Enquiry</strong><span>Latest dates & pricing on WhatsApp</span></div></section><div className="oat-v16-trail"><a href="/">Home</a>  ›  <a href="/packages">Tour Packages</a>  ›  Hyderabad Packages</div>
<div className="oat-v16-bar"><div className="oat-v16-bar-inner"><div><strong>Planning from Hyderabad?</strong><div className="oat-v16-mini">Get the latest route, dates, inclusions and price on WhatsApp.</div></div><a href="https://wa.me/919182894146?text=Hi%20On%20A%20Trip%20Holidays%2C%20I%20want%20the%20latest%20package%20details%20from%20Hyderabad.">Get Latest Details →</a></div></div><section className="oat-v15-section"><h2>Destination Highlights</h2><div className="oat-v15-gallery"><figure><img alt="Spiti Valley Tour Packages from Hyderabad destination travel photograph" decoding="async" loading="lazy" src="https://images.pexels.com/photos/37484348/pexels-photo-37484348.jpeg?auto=compress&amp;cs=tinysrgb&amp;w=1600" /><figcaption>Signature view</figcaption></figure><figure><img alt="Spiti Valley Tour Packages from Hyderabad destination travel photograph" decoding="async" loading="lazy" src="https://images.pexels.com/photos/30255569/pexels-photo-30255569.jpeg?auto=compress&amp;cs=tinysrgb&amp;w=1600" /><figcaption>Travel highlight</figcaption></figure><figure><img alt="Spiti Valley Tour Packages from Hyderabad destination travel photograph" decoding="async" loading="lazy" src="https://images.pexels.com/photos/31874833/pexels-photo-31874833.jpeg?auto=compress&amp;cs=tinysrgb&amp;w=1600" /><figcaption>Explore the destination</figcaption></figure></div></section><section className="oat-v15-section"><h2>Plan your trip with clarity</h2><div className="oat-v15-route"><article><b>01 • Choose your dates</b><span>Share preferred dates and group size so we can confirm the latest available option.</span></article><article><b>02 • Get the right itinerary</b><span>Compare route, hotel, transport and sightseeing choices before you book.</span></article><article><b>03 • Enquire directly</b><span>Use WhatsApp for the latest package details and personalised assistance.</span></article></div></section><section className="oat-v15-cta"><h2>Ready to plan your trip from Hyderabad?</h2><p>Send your travel dates and group size. We’ll help you understand the latest itinerary, package inclusions and available options.</p><a className="oat-v15-btn" href="https://wa.me/919182894146?text=Hi%20On%20A%20Trip%20Holidays%2C%20please%20share%20the%20latest%20itinerary%20and%20price">WhatsApp On A Trip Holidays</a></section><p>Plan an adventure through the stark landscapes of Spiti Valley with a route designed around altitude, road conditions, accommodation and realistic travel time.</p></section>
<section className="oat-grid"><article className="oat-card"><h2>Manali–Spiti Route</h2><p>Explore a popular gateway route when road and seasonal conditions permit.</p><a href="/package-spiti-manali">Explore route →</a></article><article className="oat-card"><h2>Kaza</h2><p>Base yourself in Spiti for monasteries, villages and mountain landscapes.</p><a href="/package-spiti-manali">Explore Kaza →</a></article><article className="oat-card"><h2>Spiti Valley Villages</h2><p>Experience remote Himalayan landscapes and local culture.</p><a href="/package-spiti-manali">Explore Spiti →</a></article><article className="oat-card"><h2>Himalayan Adventure</h2><p>Ask for current departure dates and custom group options.</p><a href="/packages">View packages →</a></article></section><section className="oat-cta"><h2>Planning a Himalayan trip from Hyderabad?</h2><p>Send your dates, group size and preferred destinations. We’ll help with itinerary, transport and stay options.</p><a href="https://wa.me/919182894146?text=Hi%20On%20A%20Trip%20Holidays%2C%20I%20want%20a%20Himalayan%20tour%20quote">Get itinerary & price on WhatsApp</a></section>
<section className="oat-faq"><h2>Frequently Asked Questions</h2><details><summary>Can I book Spiti Valley from Hyderabad?</summary><p>Yes. We can assist with planning a Spiti Valley trip from Hyderabad, subject to seasonal road conditions and route availability.</p></details><details><summary>Is Spiti suitable for everyone?</summary><p>Spiti involves high altitude and long road journeys. Route choice, acclimatisation, weather and fitness considerations should be discussed before booking.</p></details><details><summary>Can Spiti itineraries be customised?</summary><p>Yes. Customisation can consider travel dates, group size, route, stay preferences and available road conditions.</p></details></section></main><section className="oat-v15-section"><h2>How to plan Spiti Valley Tour Packages from Hyderabad</h2><div className="oat-v16-steps"><div className="oat-v16-step"><b>1</b><h3>Share your dates</h3><p>Tell us your preferred travel dates, number of travellers and departure city.</p></div><div className="oat-v16-step"><b>2</b><h3>Choose your trip</h3><p>Compare the route, stay plan, transport and inclusions that suit your group.</p></div><div className="oat-v16-step"><b>3</b><h3>Confirm your booking</h3><p>Our team helps with the next booking steps and current trip requirements.</p></div></div><div className="oat-v16-note">Package dates, availability, prices and inclusions can change. Confirm the latest details before booking.</div><div className="oat-v16-cta"><div><h3>Need the latest package details?</h3><p>Message On A Trip Holidays for current dates, pricing and inclusions.</p></div><a href="https://wa.me/919182894146?text=Hi%20On%20A%20Trip%20Holidays%2C%20please%20share%20the%20latest%20package%20details%20from%20Hyderabad.">WhatsApp Us</a></div></section>
    </SitePage>
  );
}
