import type { Metadata } from "next";
import SitePage from "@/components/SitePage";

export const metadata: Metadata = {
  title: "Pilgrimage Tour Packages | Char Dham, Kedarnath & More",
  description: "Book pilgrimage tour packages from Hyderabad and Telangana with Telugu travel support. Explore Char Dham, Kedarnath, Badrinath, Vaishno Devi, Amarnath and Ujjain trips.",
  alternates: { canonical: "/pilgrimage" },
  robots: { index: true, follow: true, "max-image-preview": "large" },
  openGraph: {
    title: "Pilgrimage Tour Packages | Char Dham, Kedarnath & More",
    description: "Book pilgrimage tour packages from Hyderabad and Telangana with Telugu travel support. Explore Char Dham, Kedarnath, Badrinath, Vaishno Devi, Amarnath and Ujjain trips.",
    url: "/pilgrimage",
    siteName: "On A Trip Holidays",
    type: "website",
  },
};

export default function Page() {
  return (
    <SitePage>
      <nav className="nav"><a className="brand" href="/"><img alt="On A Trip Holidays" src="assets/logo.png" /></a><div className="navlinks"><a href="/packages">Packages</a><a href="/pilgrimage">Pilgrimage</a><a href="/itineraries">Itineraries</a><a href="packages.html#batches">Batches</a><a href="/blogs">Blogs</a><a href="blogs.html#new-destination-guides">Guides</a><a href="/about">About</a><a href="/contact">Contact</a></div><a className="wa" href="https://wa.me/919182894146?text=Hi%20On%20A%20Trip%20Holidays%2C%20I%20want%20a%20travel%20quote">WhatsApp Us</a></nav><section className="hero"><div className="hero-inner"><div className="eyebrow">On A Trip Temple</div><h1>Pilgrimage with comfort.</h1><p>Char Dham, Kedarnath, Amarnath, Vaishno Devi and South/North Indian temple circuits.</p></div></section><section className="section"><div className="grid"><article className="card" data-cat="Pilgrimage" data-name="char dham yatra" data-price="30500">
<div className="cardimg"><img alt="Char Dham Yatra" src="https://images.unsplash.com/photo-1767974008887-97fde62d645c?auto=format&amp;fit=crop&amp;fm=jpg&amp;q=85&amp;w=3000" /><span className="badge">Bestseller</span><span className="days">11 Days</span></div>
<div className="cardbody"><span className="pill">Pilgrimage</span><h3>Char Dham Yatra</h3><div className="route">Kedarnath • Badrinath • Gangotri • Yamunotri</div><div className="price">From ₹30,500</div><div className="cardactions"><a className="btn" href="/package-char-dham">View Details</a><a className="small" href="contact.html?package=char-dham">Enquire →</a></div></div></article><article className="card" data-cat="Pilgrimage" data-name="kedarnath yatra" data-price="13499">
<div className="cardimg"><img alt="Kedarnath Yatra" src="https://images.unsplash.com/photo-1767974008887-97fde62d645c?auto=format&amp;fit=crop&amp;fm=jpg&amp;q=85&amp;w=3000" /><span className="badge">Popular</span><span className="days">6 Days</span></div>
<div className="cardbody"><span className="pill">Pilgrimage</span><h3>Kedarnath Yatra</h3><div className="route">Kedarnath • Sonprayag • Guptkashi</div><div className="price">From ₹13,499</div><div className="cardactions"><a className="btn" href="/package-kedarnath">View Details</a><a className="small" href="contact.html?package=kedarnath">Enquire →</a></div></div></article><article className="card" data-cat="Pilgrimage" data-name="do dham yatra" data-price="22000">
<div className="cardimg"><img alt="Do Dham Yatra" src="https://images.unsplash.com/photo-1767974008887-97fde62d645c?auto=format&amp;fit=crop&amp;fm=jpg&amp;q=85&amp;w=3000" /><span className="badge">Pilgrimage</span><span className="days">9 Days</span></div>
<div className="cardbody"><span className="pill">Pilgrimage</span><h3>Do Dham Yatra</h3><div className="route">Kedarnath • Badrinath • Tungnath</div><div className="price">From ₹22,000</div><div className="cardactions"><a className="btn" href="/package-do-dham">View Details</a><a className="small" href="contact.html?package=do-dham">Enquire →</a></div></div></article><article className="card" data-cat="Pilgrimage" data-name="amarnath yatra" data-price="18999">
<div className="cardimg"><img alt="Amarnath Yatra" src="https://images.unsplash.com/photo-1767974008887-97fde62d645c?auto=format&amp;fit=crop&amp;fm=jpg&amp;q=85&amp;w=3000" /><span className="badge">Pilgrimage</span><span className="days">5 Days</span></div>
<div className="cardbody"><span className="pill">Pilgrimage</span><h3>Amarnath Yatra</h3><div className="route">Srinagar • Pahalgam • Baltal • Amarnath</div><div className="price">From ₹18,999</div><div className="cardactions"><a className="btn" href="/package-amarnath">View Details</a><a className="small" href="contact.html?package=amarnath">Enquire →</a></div></div></article><article className="card" data-cat="Pilgrimage" data-name="vaishno devi yatra" data-price="12999">
<div className="cardimg"><img alt="Vaishno Devi Yatra" src="https://images.unsplash.com/photo-1767974008887-97fde62d645c?auto=format&amp;fit=crop&amp;fm=jpg&amp;q=85&amp;w=3000" /><span className="badge">Pilgrimage</span><span className="days">4 Days</span></div>
<div className="cardbody"><span className="pill">Pilgrimage</span><h3>Vaishno Devi Yatra</h3><div className="route">Katra • Vaishno Devi • Patnitop</div><div className="price">From ₹12,999</div><div className="cardactions"><a className="btn" href="/package-vaishno-devi">View Details</a><a className="small" href="contact.html?package=vaishno-devi">Enquire →</a></div></div></article><article className="card" data-cat="Pilgrimage" data-name="ujjain mahakal + omkareshwar" data-price="14999">
<div className="cardimg"><img alt="Ujjain Mahakal + Omkareshwar" src="https://images.unsplash.com/photo-1767974008887-97fde62d645c?auto=format&amp;fit=crop&amp;fm=jpg&amp;q=85&amp;w=3000" /><span className="badge">Temple Special</span><span className="days">3 Nights</span></div>
<div className="cardbody"><span className="pill">Pilgrimage</span><h3>Ujjain Mahakal + Omkareshwar</h3><div className="route">Mahakaleshwar • Omkareshwar • Ujjain</div><div className="price">From ₹14,999</div><div className="cardactions"><a className="btn" href="/package-ujjain">View Details</a><a className="small" href="contact.html?package=ujjain">Enquire →</a></div></div></article><article className="card" data-cat="Pilgrimage" data-name="kashi + ayodhya" data-price="16999">
<div className="cardimg"><img alt="Kashi + Ayodhya" src="https://images.unsplash.com/photo-1767974008887-97fde62d645c?auto=format&amp;fit=crop&amp;fm=jpg&amp;q=85&amp;w=3000" /><span className="badge">Pilgrimage</span><span className="days">4 Nights</span></div>
<div className="cardbody"><span className="pill">Pilgrimage</span><h3>Kashi + Ayodhya</h3><div className="route">Varanasi • Ayodhya • Sarnath</div><div className="price">From ₹16,999</div><div className="cardactions"><a className="btn" href="/package-kashi-ayodhya">View Details</a><a className="small" href="contact.html?package=kashi-ayodhya">Enquire →</a></div></div></article><article className="card" data-cat="Pilgrimage" data-name="tirupati + srisailam" data-price="11999">
<div className="cardimg"><img alt="Tirupati + Srisailam" src="https://images.unsplash.com/photo-1767974008887-97fde62d645c?auto=format&amp;fit=crop&amp;fm=jpg&amp;q=85&amp;w=3000" /><span className="badge">Temple Special</span><span className="days">3 Nights</span></div>
<div className="cardbody"><span className="pill">Pilgrimage</span><h3>Tirupati + Srisailam</h3><div className="route">Tirupati • Srisailam</div><div className="price">From ₹11,999</div><div className="cardactions"><a className="small" href="contact.html?package=tirupati-srisailam">Enquire →</a></div></div></article></div></section><section className="section seo-city-links"><div className="head"><div><div className="eyebrow">TRAVEL FROM HYDERABAD</div><h2>Popular Hyderabad Travel Searches</h2></div><p>Explore destination guides and packages built around common travel searches from Hyderabad.</p></div><div className="grid"><article className="blog"><h3><a href="/hyderabad-to-kashmir-tour-packages">Kashmir Tour Packages from Hyderabad </a></h3><p>Kashmir tour packages from Hyderabad with Srinagar, Gulmarg, Pahalgam and Sonamarg. Explore group and customised Kashmir holidays with Telugu travel support.</p></article><article className="blog"><h3><a href="/hyderabad-to-ladakh-tour-packages">Ladakh Tour Packages from Hyderabad </a></h3><p>Leh Ladakh tour packages from Hyderabad covering Leh, Nubra, Pangong and high-altitude routes. Get group and customised Ladakh trip planning with Telugu support.</p></article><article className="blog"><h3><a href="/hyderabad-to-char-dham-yatra">Char Dham Yatra from Hyderabad </a></h3><p>Char Dham Yatra packages from Hyderabad covering Yamunotri, Gangotri, Kedarnath and Badrinath with organised transport, stays, meals and Telugu support.</p></article><article className="blog"><h3><a href="/hyderabad-to-kedarnath-yatra">Kedarnath Yatra from Hyderabad </a></h3><p>Kedarnath Yatra packages from Hyderabad with travel planning, accommodation, transfers and practical trek preparation guidance.</p></article><article className="blog"><h3><a href="/hyderabad-to-manali-tour-packages">Manali Tour Packages from Hyderabad </a></h3><p>Manali tour packages from Hyderabad for families, couples and friends covering Manali, Solang Valley, Rohtang region and nearby Himalayan attractions.</p></article><article className="blog"><h3></h3><p>Kerala tour packages from Hyderabad covering Munnar, Thekkady, Alleppey and Kerala backwaters. Compare group and customised holidays.</p></article><article className="blog"><h3></h3><p>Sikkim tour packages from Hyderabad covering Gangtok, Pelling and scenic Himalayan attractions with flexible itineraries and travel support.</p></article><article className="blog"><h3><a href="/hyderabad-to-nepal-tour-packages">Nepal Tour Packages from Hyderabad </a></h3><p>Nepal tour packages from Hyderabad covering Kathmandu, Pokhara and optional Muktinath with practical route planning and travel support.</p></article></div></section><div aria-label="Go to top" className="v18-page-top"><button aria-label="Go to top" type="button">⌃</button></div>
<div className="v18-wa"><a aria-label="WhatsApp us" href="https://wa.me/919182894146?text=Hi%20On%20A%20Trip%20Holidays%2C%20I%20want%20to%20plan%20a%20trip"><svg aria-hidden="true" viewBox="0 0 32 32"><path d="M19.11 17.29c-.27-.14-1.58-.78-1.82-.87-.24-.09-.42-.14-.6.14-.18.27-.69.87-.85 1.05-.16.18-.31.2-.58.07-.27-.14-1.14-.42-2.17-1.34-.8-.71-1.34-1.59-1.5-1.86-.16-.27-.02-.42.12-.56.12-.12.27-.31.4-.47.13-.16.18-.27.27-.45.09-.18.04-.34-.02-.47-.07-.14-.6-1.44-.82-1.97-.22-.52-.44-.45-.6-.46h-.51c-.18 0-.47.07-.71.34-.24.27-.93.91-.93 2.22s.96 2.57 1.09 2.75c.13.18 1.89 2.88 4.58 4.04.64.28 1.14.44 1.53.56.64.2 1.22.17 1.68.1.51-.08 1.58-.65 1.8-1.27.22-.62.22-1.15.16-1.27-.07-.11-.24-.18-.51-.31z" fill="currentColor"></path><path d="M16.03 3.2c-7.07 0-12.8 5.72-12.8 12.77 0 2.25.59 4.36 1.63 6.19L3.2 28.8l6.83-1.64a12.78 12.78 0 0 0 6 1.48h.01c7.06 0 12.79-5.73 12.79-12.78S23.1 3.2 16.03 3.2zm0 23.36h-.01a10.58 10.58 0 0 1-5.39-1.47l-.39-.23-4.05.97.98-3.95-.25-.41a10.56 10.56 0 1 1 9.11 5.09z" fill="currentColor"></path></svg></a></div>
<footer className="oat-company-footer">
<h3 className="oat-company-name">ON A TRIP HOLIDAYS</h3>
<p className="oat-company-tag">Trusted travel company for Telangana & Andhra Pradesh — Telugu-first support for pilgrimage, domestic, adventure and international holidays.</p>
<div className="oat-company-details">
<a href="mailto:travel@onatripholidays.com">travel@onatripholidays.com</a>
<a href="tel:+919182894146">+91 91828 94146</a>
<span>Hyderabad • Vijayawada • Telangana & Andhra Pradesh</span>
</div>
<div aria-label="Social links" className="oat-socials">
<a aria-label="Instagram" href="https://www.instagram.com/onatriphyd/" rel="noopener" target="_blank">IG</a>
<a aria-label="WhatsApp" href="https://wa.me/919182894146" rel="noopener" target="_blank">WA</a>
<a aria-label="Email" href="mailto:travel@onatripholidays.com">@</a>
</div>
<div aria-hidden="true" className="oat-skyline">✦ • 🕌 • 🛕 • 🏔️ • ✈ • 🌴 • 🛕 • 🕌 • ✦</div>
<div className="oat-footer-links">
<a href="/packages">All Packages</a><a href="/pilgrimage">Pilgrimage</a><a href="packages.html#batches">Batch Dates</a><a href="/blogs">Travel Blog</a><a href="blogs.html#new-destination-guides">Guides</a><a href="/about">About Us</a><a href="/contact">Contact Us</a>
</div>
<div className="oat-footer-divider"></div>
<div className="oat-copy">© 2026 On A Trip Holidays. All rights reserved.</div>
</footer><section><h2>Explore all destination landing pages from Hyderabad</h2><p>Find dedicated pages for pilgrimage, Himalayas, South India, North East and Bhutan.</p><a href="/destinations-from-hyderabad">View all destinations from Hyderabad →</a></section><section><h2>SEO Priority Pilgrimage Pages</h2><ul><li><a href="/kedarnath-yatra-packages-from-hyderabad">Kedarnath Yatra from Hyderabad</a></li><li><a href="/do-dham-yatra-packages-from-hyderabad">Do Dham Yatra from Hyderabad</a></li><li><a href="/char-dham-yatra-packages-from-hyderabad">Char Dham Yatra from Hyderabad</a></li></ul></section><section className="section"><div className="v13-wrap"><h2>More Jyotirlinga Pilgrimage Tours from Hyderabad</h2><div className="v13-grid"><article className="v13-card"><h3>Maharashtra 3 Jyotirlingas</h3><p>Trimbakeshwar • Bhimashankar • Grishneshwar</p><a href="/maharashtra-3-jyotirlinga-yatra-from-hyderabad">Explore Yatra →</a></article><article className="v13-card"><h3>Somnath–Dwarka–Nageshwar</h3><p>Gujarat temple pilgrimage</p><a href="/somnath-dwarka-nageshwar-yatra-from-hyderabad">Explore Yatra →</a></article><article className="v13-card"><h3>Ujjain–Omkareshwar</h3><p>Mahakaleshwar • Omkareshwar</p><a href="/ujjain-omkareshwar-yatra-from-hyderabad">Explore Yatra →</a></article></div></div></section><div><h2>Explore Uttarakhand</h2><p><a href="/uttarakhand-tour-packages-from-hyderabad">Uttarakhand Tour Packages from Hyderabad</a></p></div>
    </SitePage>
  );
}
